all1:: $(LIBRARY)
# options compilation a modifier sous hp & solaris
$(LIBRARY): $(OBJS)
	@echo Creation of $(LIBRARY)
	@$(RM) $@;
	@echo "linking";
	@$(LD) -b -o $@ $(OBJS) $(DEFAULTS) $(LIBR) $(TCLTK_LIBS) $(XLIBS)  $(TERMCAPLIB) $(FLIBS);
