#!/bin/sh
#
# $Id: ipcfree,v 1.1 2001/04/26 07:47:08 scilab Exp $
#
# ipcfree
#
# Delete any shared memory or semaphores lying around after a PVM
# program bombs out or is killed ungracefully.
# Run it if you're getting error messages like:
#   semget: ... No space left on device
#   shmget: ... No space left on device
# when using one of the *MP PVM architectures.
#

if [ "$USER" = "" ]; then
	USER=` whoami `
fi

m=` ipcs | awk '$1~/^[ms]$/ && $5~/'$USER'/ {print "-"$1, $2}' `

case "$m" in
?*) echo "deleting $m"
    ipcrm $m
;;
*) echo "didn't find anything"
;;
esac

exit 0

