/* Allan CORNET */
/* INRIA 2005 */
#ifndef _WARNINGSH_
#define _WARNINGSH_

#define MSG_WARNING1 "Running out of memory\r\n"
#define MSG_WARNING2 "WinExec of %s failed \r\n"
#define MSG_WARNING3 " Could not exec %s\r\n"
#define MSG_WARNING4 "\nDANGER: gets() used\n"
#define MSG_WARNING5 "Problem on line %d of %s\n"
#define MSG_WARNING6 "Menu is too deep at line %d of %s\n"
#define MSG_WARNING7 "Too many menu items at line %d of %s\n"
#define MSG_WARNING8 "Problem on line %d of %s\n"
#define MSG_WARNING9 "Out of space for storing menu macros\n at line %d of %s\n"
#define MSG_WARNING10 "Can't add a menu item in scilab main menu \r\n"
#define MSG_WARNING11 "Can't add a menu item in scilab graphic %d menu \r\n"
#define MSG_WARNING12 "Out of space for storing menu macros\n"
#define MSG_WARNING13 "Can't add a menu item \r\n"
#define MSG_WARNING14 "Out of space for storing menu macros\n"
#define MSG_WARNING15 "Cannot find environment variable TMPDIR\r\n"
#define MSG_WARNING16 "Insufficient Memory to Copy Clipboard"
#define MSG_WARNING17 "hdc for backing store failed \r\n"
#define MSG_WARNING18 "Allocating pixmap for backing store failed \r\n"
#define MSG_WARNING19 "Can't resize pixmap\r\n"
#define MSG_WARNING20 "Don't Find Scilab Process"
#define MSG_WARNING21 "Attention"
#define MSG_WARNING22 "Warning"
#define MSG_WARNING23 "Couldn't Execute a new Scilab"
#define MSG_WARNING24 "Couldn't Open Web Browser"
#define MSG_WARNING25 "Couldn't Open Email Client"
#define MSG_WARNING26 "Impossible d'ouvrir le fichier Licence.txt"
#define MSG_WARNING27 "Couldn't Open License.txt"
#define MSG_WARNING28 "\n Not in screen \n"
#define MSG_WARNING29 "\n Not in console mode \n"
#define MSG_WARNING30 "Scilab has performed a illegal operation\nand will be shutdown.\n Please save your work ..."
#define MSG_WARNING31 "  Only in Graphical Version.\n"
#define MSG_WARNING32 "Impossible d'ouvrir le fichier release_notes.txt"
#define MSG_WARNING33 "Couldn't Open release_notes.txt"
#endif /*_WARNINGSH_*/
