#include "SwingScilabMenu.hxx"
/* Generated by GIWS (version 1.0) */
/*

Copyright 2007 INRIA

Author : Sylvestre Ledru

This software is a computer program whose purpose is to hide the complexity
of accessing Java objects/methods from C++ code.

This software is governed by the CeCILL-B license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the CeCILL-B
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL-B license and that you accept its terms.
*/

namespace org_scilab_modules_gui_bridge_menu {

// Returns the current env

JNIEnv * SwingScilabMenu::getCurrentEnv() {
JNIEnv * curEnv = NULL;
this->jvm->AttachCurrentThread((void **) &curEnv, NULL);
return curEnv;
}
// Destructor

SwingScilabMenu::~SwingScilabMenu() {
JNIEnv * curEnv = NULL;
this->jvm->AttachCurrentThread((void **) &curEnv, NULL);

curEnv->DeleteGlobalRef(this->instance);
curEnv->DeleteGlobalRef(this->instanceClass);
}
// Constructors

SwingScilabMenu::SwingScilabMenu(JavaVM * jvm_) {
jmethodID constructObject = NULL ;
jobject localInstance ;
jclass localClass ;
const std::string construct="<init>";
const std::string param="()V";
jvm=jvm_;

JNIEnv * curEnv = getCurrentEnv();

localClass = curEnv->FindClass( this->className().c_str() ) ;
if (localClass == NULL) {
std::cerr << "Could not get the Class " << this->className() <<  std::endl;
exit(EXIT_FAILURE);
}

this->instanceClass = (jclass) curEnv->NewGlobalRef(localClass) ;
if (this->instanceClass == NULL) {
std::cerr << "Could not create a Global Ref of " << this->className() <<  std::endl;
exit(EXIT_FAILURE);
}

constructObject = curEnv->GetMethodID( this->instanceClass, construct.c_str() , param.c_str() ) ;
if(constructObject == NULL){
std::cerr << "Could not retrieve the constructor of the class " << this->className() << " with the profile : " << construct << param << std::endl;
exit(EXIT_FAILURE);
}

localInstance = curEnv->NewObject( this->instanceClass, constructObject ) ;
if(localInstance == NULL){
std::cerr << "Could not instantiate the object " << this->className() << " with the constructor : " << construct << param << std::endl;
exit(EXIT_FAILURE);
}
 
this->instance = curEnv->NewGlobalRef(localInstance) ;
if(this->instance == NULL){
std::cerr << "Could not create a new global ref of " << this->className() << std::endl;
exit(EXIT_FAILURE);
}
                /* Methods ID set to NULL */
voidsetTextjstringID=NULL; 
voidsetParentjintID=NULL; 
voidsetCallbackjstringID=NULL; 
voiddisplayID=NULL; 
voidshowID=NULL; 
voiddestroyID=NULL; 


}

SwingScilabMenu::SwingScilabMenu(JavaVM * jvm_, jobject JObj) {
        jvm=jvm_;

        JNIEnv * curEnv = getCurrentEnv();

        this->instanceClass = (jclass) curEnv->NewGlobalRef(curEnv->GetObjectClass(JObj));
        if (this->instanceClass == NULL) {
               std::cerr << "Could not create a Global Ref of " << this->instanceClass <<  std::endl;
               exit(EXIT_FAILURE);
        }

        this->instance = curEnv->NewGlobalRef(JObj) ;
        if(this->instance == NULL){
               std::cerr << "Could not create a new global ref of " << this->instanceClass << std::endl;
               exit(EXIT_FAILURE);
        }
        /* Methods ID set to NULL */
        voidsetTextjstringID=NULL; 
voidsetParentjintID=NULL; 
voidsetCallbackjstringID=NULL; 
voiddisplayID=NULL; 
voidshowID=NULL; 
voiddestroyID=NULL; 


}

// Generic methods


void SwingScilabMenu::synchronize() {
if (getCurrentEnv()->MonitorEnter(instance) != JNI_OK) {
std::cerr << "Fail to enter monitor." << std::endl;
exit(EXIT_FAILURE);
}
}


void SwingScilabMenu::endSynchronize() {
if ( getCurrentEnv()->MonitorExit(instance) != JNI_OK) {
std::cerr << "Fail to exit monitor." << std::endl;
exit(EXIT_FAILURE);
}
}

// Method(s)

void SwingScilabMenu::setText (char * newText){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetTextjstringID==NULL) { /* Use the cache Luke */ voidsetTextjstringID = curEnv->GetMethodID(this->instanceClass, "setText", "(Ljava/lang/String;)V" ) ;
if (voidsetTextjstringID == NULL) {
std::cerr << "Could not access to the method " << "setText" << std::endl;
exit(EXIT_FAILURE);
}
}
jstring newText_ = curEnv->NewStringUTF( newText );

                         curEnv->CallVoidMethod( this->instance, voidsetTextjstringID ,newText_);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void SwingScilabMenu::setParent (long parentIndex){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetParentjintID==NULL) { /* Use the cache Luke */ voidsetParentjintID = curEnv->GetMethodID(this->instanceClass, "setParent", "(I)V" ) ;
if (voidsetParentjintID == NULL) {
std::cerr << "Could not access to the method " << "setParent" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidsetParentjintID ,parentIndex);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void SwingScilabMenu::setCallback (char * callback){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetCallbackjstringID==NULL) { /* Use the cache Luke */ voidsetCallbackjstringID = curEnv->GetMethodID(this->instanceClass, "setCallback", "(Ljava/lang/String;)V" ) ;
if (voidsetCallbackjstringID == NULL) {
std::cerr << "Could not access to the method " << "setCallback" << std::endl;
exit(EXIT_FAILURE);
}
}
jstring callback_ = curEnv->NewStringUTF( callback );

                         curEnv->CallVoidMethod( this->instance, voidsetCallbackjstringID ,callback_);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void SwingScilabMenu::display (){

JNIEnv * curEnv = getCurrentEnv();

if (voiddisplayID==NULL) { /* Use the cache Luke */ voiddisplayID = curEnv->GetMethodID(this->instanceClass, "display", "()V" ) ;
if (voiddisplayID == NULL) {
std::cerr << "Could not access to the method " << "display" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voiddisplayID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void SwingScilabMenu::show (){

JNIEnv * curEnv = getCurrentEnv();

if (voidshowID==NULL) { /* Use the cache Luke */ voidshowID = curEnv->GetMethodID(this->instanceClass, "show", "()V" ) ;
if (voidshowID == NULL) {
std::cerr << "Could not access to the method " << "show" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidshowID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void SwingScilabMenu::destroy (){

JNIEnv * curEnv = getCurrentEnv();

if (voiddestroyID==NULL) { /* Use the cache Luke */ voiddestroyID = curEnv->GetMethodID(this->instanceClass, "destroy", "()V" ) ;
if (voiddestroyID == NULL) {
std::cerr << "Could not access to the method " << "destroy" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voiddestroyID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

}
