# in sync at least with v5.0
# English is the original language of Scipad
# Scipad tcl/tk source should use english texts
# for instance [mc "your text in english here"]
# Translations are provided in other msg files
# except for "expanded" text, like preference variables description


#helps.tcl
::msgcat::mcset eng aboutme_message \
                    "\n Originated by Joseph Acosta, joeja@mindspring.com.\n\
                    Modified by Scilab Consortium.\n\
                    Revised by Enrico Segre 2003-2005.\n\
                    Miscellaneous improvements, particularly debug tools,\
                    by Francois Vogel 2004-2005.\n\
                    Swedish translation by Gunnar Lindholm 2005.\n\
                    Norwegian translation by Torbjørn Pettersen 2005.\n\
                    German translation by Dirk Reusch 2005."


# popupmenus.tcl
::msgcat::mcset eng "AddWatch" "Add %s as watch"


#preference variables description
::msgcat::mcset eng "BGCOLOR" "Background"
::msgcat::mcset eng "FGCOLOR" "Plain text"
::msgcat::mcset eng "CURCOLOR" "Cursor"
::msgcat::mcset eng "PARCOLOR" "Parentheses ()"
::msgcat::mcset eng "BRAKCOLOR" "Brackets \\\[\\\]"
::msgcat::mcset eng "BRACCOLOR" "Braces {}"
::msgcat::mcset eng "PUNCOLOR"  "Punctuation"
::msgcat::mcset eng "KEYWCOLOR" "Scilab internals"
::msgcat::mcset eng "OPCOLOR"   "Operators"
::msgcat::mcset eng "QTXTCOLOR"  "String text"
::msgcat::mcset eng "REMCOLOR" "Comments"
::msgcat::mcset eng "XMLCOLOR" "XML tags"
::msgcat::mcset eng "NUMCOLOR" "Numbers"
::msgcat::mcset eng "SELCOLOR" "Selection"
::msgcat::mcset eng "BREAKPOINTCOLOR" "Breakpoint background"
::msgcat::mcset eng "LFUNCOLOR" "Library functions"
::msgcat::mcset eng "PDEFCOLOR" "Predefined variables"
::msgcat::mcset eng "FOUNDTEXTCOLOR" "Matched text"
