# in sync with v3.44
# English is the original language of Scipad
# Scipad tcl/tk source should use english texts
# for instance [mc "your text in english here"]
# Translations are provided in other msg files

# except for "expanded" text, like preference variables description
::msgcat::mcset eng "BGCOLOR" "Background"
::msgcat::mcset eng "FGCOLOR" "Plain text"
::msgcat::mcset eng "CURCOLOR" "Cursor"
::msgcat::mcset eng "PARCOLOR" "Parentheses ()"
::msgcat::mcset eng "BRAKCOLOR" "Brackets \\\[\\\]"
::msgcat::mcset eng "BRACCOLOR" "Braces {}"
::msgcat::mcset eng "PUNCOLOR"  "Punctuation"
::msgcat::mcset eng "KEYWCOLOR" "Scilab internals"
::msgcat::mcset eng "OPCOLOR"   "Operators"
::msgcat::mcset eng "QTXTCOLOR"  "String text"
::msgcat::mcset eng "REMCOLOR" "Comments"
::msgcat::mcset eng "XMLCOLOR" "XML tags"
::msgcat::mcset eng "NUMCOLOR" "Numbers"
::msgcat::mcset eng "SELCOLOR" "Selection"
::msgcat::mcset eng "BREAKPOINTCOLOR" "Breakpoint background"
::msgcat::mcset eng "LFUNCOLOR" "Library functions"
::msgcat::mcset eng "PDEFCOLOR" "Predefined variables"
::msgcat::mcset eng "FOUNDTEXTCOLOR" "Matched text"
