/*
 *  Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
 *  Copyright (C) 2010-2010 - DIGITEO - Bruno JOFRET
 *
 *  This file must be used under the terms of the CeCILL.
 *  This source file is licensed as described in the file COPYING, which
 *  you should have received as part of this distribution.  The terms
 *  are also available at
 *  http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.txt
 *
 */

/*
 * -=- This is a generated file, please do not edit by hand             -=-
 * -=- Please see properties definitions in                             -=-
 * -=- SCI/modules/graphic_objects/src/scripts/propertiesMap.properties -=-
 */

#ifndef  __GRAPHIC_OBJECT_PROPERTIES_H__
#define __GRAPHIC_OBJECT_PROPERTIES_H__

#define __GO_ARC__ 0
#define __GO_AXES__ 1
#define __GO_AXESMODEL__ 2
#define __GO_AXIS__ 3
#define __GO_CHAMP__ 4
#define __GO_COMPOUND__ 5
#define __GO_FAC3D__ 6
#define __GO_FEC__ 7
#define __GO_FIGURE__ 8
#define __GO_FIGUREMODEL__ 9
#define __GO_GRAYPLOT__ 10
#define __GO_LABEL__ 11
#define __GO_LEGEND__ 12
#define __GO_MATPLOT__ 13
#define __GO_PLOT3D__ 14
#define __GO_POLYLINE__ 15
#define __GO_RECTANGLE__ 16
#define __GO_SEGS__ 17
#define __GO_TEXT__ 18
#define __GO_UICONTROL__ 19
#define __GO_UIMENU__ 20
#define __GO_UICONTEXTMENU__ 21
#define __GO_CHILDREN__ 22
#define __GO_CHILDREN_COUNT__ 23
#define __GO_PARENT__ 24
#define __GO_USER_DATA__ 25
#define __GO_USER_DATA_SIZE__ 26
#define __GO_VISIBLE__ 27
#define __GO_HIDDEN__ 28
#define __GO_TYPE__ 29
#define __GO_DATA_MODEL__ 30
#define __GO_PARENT_FIGURE__ 31
#define __GO_PARENT_AXES__ 32
#define __GO_HAS_LEGEND_CHILD__ 33
#define __GO_LEGEND_CHILD__ 34
#define __GO_SELECTED_CHILD__ 35
#define __GO_CALLBACK__ 36
#define __GO_CALLBACKTYPE__ 37
#define __GO_DATA_MODEL_COORDINATES__ 38
#define __GO_DATA_MODEL_X__ 39
#define __GO_DATA_MODEL_Y__ 40
#define __GO_DATA_MODEL_Z__ 41
#define __GO_DATA_MODEL_X_COORDINATES_SHIFT__ 42
#define __GO_DATA_MODEL_Y_COORDINATES_SHIFT__ 43
#define __GO_DATA_MODEL_Z_COORDINATES_SHIFT__ 44
#define __GO_DATA_MODEL_X_COORDINATES_SHIFT_SET__ 45
#define __GO_DATA_MODEL_Y_COORDINATES_SHIFT_SET__ 46
#define __GO_DATA_MODEL_Z_COORDINATES_SHIFT_SET__ 47
#define __GO_DATA_MODEL_NUM_ELEMENTS__ 48
#define __GO_DATA_MODEL_NUM_ELEMENTS_ARRAY__ 49
#define __GO_DATA_MODEL_NUM_VERTICES_PER_GON__ 50
#define __GO_DATA_MODEL_NUM_GONS__ 51
#define __GO_DATA_MODEL_Z_COORDINATES_SET__ 52
#define __GO_DATA_MODEL_COLORS__ 53
#define __GO_DATA_MODEL_NUM_COLORS__ 54
#define __GO_DATA_MODEL_NUM_VERTICES__ 55
#define __GO_DATA_MODEL_NUM_INDICES__ 56
#define __GO_DATA_MODEL_INDICES__ 57
#define __GO_DATA_MODEL_VALUES__ 58
#define __GO_DATA_MODEL_FEC_TRIANGLES__ 59
#define __GO_DATA_MODEL_NUM_X__ 60
#define __GO_DATA_MODEL_NUM_Y__ 61
#define __GO_DATA_MODEL_NUM_Z__ 62
#define __GO_DATA_MODEL_GRID_SIZE__ 63
#define __GO_DATA_MODEL_X_DIMENSIONS__ 64
#define __GO_DATA_MODEL_Y_DIMENSIONS__ 65
#define __GO_MATPLOT_TRANSLATE__ 66
#define __GO_MATPLOT_SCALE__ 67
#define __GO_DATA_MODEL_MATPLOT_BOUNDS__ 68
#define __GO_DATA_MODEL_MATPLOT_TYPE__ 69
#define __GO_DATA_MODEL_MATPLOT_GL_TYPE__ 70
#define __GO_DATA_MODEL_MATPLOT_DATA_INFOS__ 71
#define __GO_DATA_MODEL_MATPLOT_DATA_TYPE__ 72
#define __GO_DATA_MODEL_MATPLOT_DATA_ORDER__ 73
#define __GO_DATA_MODEL_MATPLOT_IMAGE_TYPE__ 74
#define __GO_DATA_MODEL_MATPLOT_IMAGE_DATA__ 75
#define __GO_DATA_MODEL_MATPLOT_IMAGE_DATASIZE__ 76
#define __GO_REFERENCED__ 77
#define __GO_VALID__ 78
#define __GO_POSITION__ 79
#define __GO_SIZE__ 80
#define __GO_CANVAS__ 81
#define __GO_AUTORESIZE__ 82
#define __GO_VIEWPORT__ 83
#define __GO_AXES_SIZE__ 84
#define __GO_FIGURE_NAME__ 85
#define __GO_NAME__ 86
#define __GO_ID__ 87
#define __GO_INFO_MESSAGE__ 88
#define __GO_COLORMAP__ 89
#define __GO_COLORMAP_SIZE__ 90
#define __GO_RENDERING_MODE__ 91
#define __GO_PIXMAP__ 92
#define __GO_PIXEL_DRAWING_MODE__ 93
#define __GO_ANTIALIASING__ 94
#define __GO_IMMEDIATE_DRAWING__ 95
#define __GO_BACKGROUND__ 96
#define __GO_EVENTHANDLER__ 97
#define __GO_EVENTHANDLER_NAME__ 98
#define __GO_EVENTHANDLER_ENABLE__ 99
#define __GO_TAG__ 100
#define __GO_ROTATION_TYPE__ 101
#define __GO_RESIZEFCN__ 102
#define __GO_CLOSEREQUESTFCN__ 103
#define __GO_UPPER_LEFT_POINT__ 104
#define __GO_WIDTH__ 105
#define __GO_HEIGHT__ 106
#define __GO_START_ANGLE__ 107
#define __GO_END_ANGLE__ 108
#define __GO_ARC_DRAWING_METHOD__ 109
#define __GO_X_AXIS_VISIBLE__ 110
#define __GO_X_AXIS_REVERSE__ 111
#define __GO_X_AXIS_GRID_COLOR__ 112
#define __GO_X_AXIS_LABEL__ 113
#define __GO_X_AXIS_LOCATION__ 114
#define __GO_X_AXIS_LOG_FLAG__ 115
#define __GO_X_AXIS_TICKS__ 116
#define __GO_X_AXIS_AUTO_TICKS__ 117
#define __GO_X_AXIS_NUMBER_TICKS__ 118
#define __GO_X_AXIS_TICKS_LOCATIONS__ 119
#define __GO_X_AXIS_TICKS_LABELS__ 120
#define __GO_X_AXIS_SUBTICKS__ 121
#define __GO_Y_AXIS_VISIBLE__ 122
#define __GO_Y_AXIS_REVERSE__ 123
#define __GO_Y_AXIS_GRID_COLOR__ 124
#define __GO_Y_AXIS_LABEL__ 125
#define __GO_Y_AXIS_LOCATION__ 126
#define __GO_Y_AXIS_LOG_FLAG__ 127
#define __GO_Y_AXIS_TICKS__ 128
#define __GO_Y_AXIS_AUTO_TICKS__ 129
#define __GO_Y_AXIS_NUMBER_TICKS__ 130
#define __GO_Y_AXIS_TICKS_LOCATIONS__ 131
#define __GO_Y_AXIS_TICKS_LABELS__ 132
#define __GO_Y_AXIS_SUBTICKS__ 133
#define __GO_Z_AXIS_VISIBLE__ 134
#define __GO_Z_AXIS_REVERSE__ 135
#define __GO_Z_AXIS_GRID_COLOR__ 136
#define __GO_Z_AXIS_LABEL__ 137
#define __GO_Z_AXIS_LOCATION__ 138
#define __GO_Z_AXIS_LOG_FLAG__ 139
#define __GO_Z_AXIS_TICKS__ 140
#define __GO_Z_AXIS_AUTO_TICKS__ 141
#define __GO_Z_AXIS_NUMBER_TICKS__ 142
#define __GO_Z_AXIS_TICKS_LOCATIONS__ 143
#define __GO_Z_AXIS_TICKS_LABELS__ 144
#define __GO_Z_AXIS_SUBTICKS__ 145
#define __GO_AUTO_SUBTICKS__ 146
#define __GO_GRID_POSITION__ 147
#define __GO_TITLE__ 148
#define __GO_AUTO_CLEAR__ 149
#define __GO_FILLED__ 150
#define __GO_CAMERA__ 151
#define __GO_VIEW__ 152
#define __GO_ISOVIEW__ 153
#define __GO_CUBE_SCALING__ 154
#define __GO_ROTATION_ANGLES__ 155
#define __GO_ROTATION_ANGLES_3D__ 156
#define __GO_BOX_TYPE__ 157
#define __GO_HIDDEN_AXIS_COLOR__ 158
#define __GO_TIGHT_LIMITS__ 159
#define __GO_DATA_BOUNDS__ 160
#define __GO_REAL_DATA_BOUNDS__ 161
#define __GO_ZOOM_ENABLED__ 162
#define __GO_ZOOM_BOX__ 163
#define __GO_AUTO_SCALE__ 164
#define __GO_FIRST_PLOT__ 165
#define __GO_MARGINS__ 166
#define __GO_AXES_BOUNDS__ 167
#define __GO_CLIP_PROPERTY__ 168
#define __GO_CLIP_STATE__ 169
#define __GO_CLIP_BOX__ 170
#define __GO_CLIP_BOX_SET__ 171
#define __GO_LINE__ 172
#define __GO_LINE_MODE__ 173
#define __GO_LINE_STYLE__ 174
#define __GO_LINE_THICKNESS__ 175
#define __GO_LINE_COLOR__ 176
#define __GO_FILL_MODE__ 177
#define __GO_MARK__ 178
#define __GO_MARK_MODE__ 179
#define __GO_MARK_STYLE__ 180
#define __GO_MARK_SIZE_UNIT__ 181
#define __GO_MARK_SIZE__ 182
#define __GO_MARK_FOREGROUND__ 183
#define __GO_MARK_BACKGROUND__ 184
#define __GO_TICKS_DIRECTION__ 185
#define __GO_X_NUMBER_TICKS__ 186
#define __GO_Y_NUMBER_TICKS__ 187
#define __GO_X_TICKS_COORDS__ 188
#define __GO_Y_TICKS_COORDS__ 189
#define __GO_TICKS_COLOR__ 190
#define __GO_TICKS_SEGMENT__ 191
#define __GO_TICKS_STYLE__ 192
#define __GO_SUBTICKS__ 193
#define __GO_NUMBER_TICKS_LABELS__ 194
#define __GO_TICKS_LABELS__ 195
#define __GO_FORMATN__ 196
#define __GO_FONT__ 197
#define __GO_FONT_STYLE__ 198
#define __GO_FONT_SIZE__ 199
#define __GO_FONT_COLOR__ 200
#define __GO_FONT_FRACTIONAL__ 201
#define __GO_Z_BOUNDS__ 202
#define __GO_OUTSIDE_COLOR__ 203
#define __GO_COLOR_RANGE__ 204
#define __GO_DATA_MAPPING__ 205
#define __GO_FONT_ANGLE__ 206
#define __GO_AUTO_POSITION__ 207
#define __GO_CORNERS__ 208
#define __GO_AUTO_ROTATION__ 209
#define __GO_LINKS__ 210
#define __GO_LINKS_COUNT__ 211
#define __GO_LEGEND_LOCATION__ 212
#define __GO_CLOSED__ 213
#define __GO_ARROW_SIZE_FACTOR__ 214
#define __GO_POLYLINE_STYLE__ 215
#define __GO_INTERP_COLOR_VECTOR__ 216
#define __GO_INTERP_COLOR_VECTOR_SET__ 217
#define __GO_INTERP_COLOR_MODE__ 218
#define __GO_X_SHIFT__ 219
#define __GO_Y_SHIFT__ 220
#define __GO_Z_SHIFT__ 221
#define __GO_BAR_WIDTH__ 222
#define __GO_SURFACE_MODE__ 223
#define __GO_COLOR_MODE__ 224
#define __GO_COLOR_FLAG__ 225
#define __GO_ALIGNMENT__ 226
#define __GO_BOX__ 227
#define __GO_TEXT_BOX__ 228
#define __GO_TEXT_BOX_MODE__ 229
#define __GO_AUTO_DIMENSIONING__ 230
#define __GO_FORMATTED_TEXT__ 231
#define __GO_TEXT_ARRAY_DIMENSIONS__ 232
#define __GO_TEXT_STRINGS__ 233
#define __GO_BASE__ 234
#define __GO_BASE_X__ 235
#define __GO_BASE_Y__ 236
#define __GO_BASE_Z__ 237
#define __GO_DIRECTION__ 238
#define __GO_DIRECTION_X__ 239
#define __GO_DIRECTION_Y__ 240
#define __GO_DIRECTION_Z__ 241
#define __GO_ARROW_SIZE__ 242
#define __GO_SEGS_COLORS__ 243
#define __GO_COLORED__ 244
#define __GO_ARROWS__ 245
#define __GO_NUMBER_ARROWS__ 246
#define __GO_CHAMP_DIMENSIONS__ 247
#define __GO_BOUNDING_BOX__ 248
#define __GO_MAX_LENGTH__ 249
#define __GO_MAX_USABLE_LENGTH__ 250
#define __GO_HIDDEN_COLOR__ 251
#define __GO_STYLE__ 252
#define __GO_UI_CHECKBOX__ 253
#define __GO_UI_EDIT__ 254
#define __GO_UI_FRAME__ 255
#define __GO_UI_IMAGE__ 256
#define __GO_UI_LISTBOX__ 257
#define __GO_UI_POPUPMENU__ 258
#define __GO_UI_PUSHBUTTON__ 259
#define __GO_UI_RADIOBUTTON__ 260
#define __GO_UI_SLIDER__ 261
#define __GO_UI_TABLE__ 262
#define __GO_UI_TEXT__ 263
#define __GO_UI_BACKGROUNDCOLOR__ 264
#define __GO_UI_ENABLE__ 265
#define __GO_UI_FONTANGLE__ 266
#define __GO_UI_FONTNAME__ 267
#define __GO_UI_FONTSIZE__ 268
#define __GO_UI_FONTUNITS__ 269
#define __GO_UI_FONTWEIGHT__ 270
#define __GO_UI_FOREGROUNDCOLOR__ 271
#define __GO_UI_HORIZONTALALIGNMENT__ 272
#define __GO_UI_LISTBOXTOP__ 273
#define __GO_UI_LISTBOXTOP_SIZE__ 274
#define __GO_UI_MAX__ 275
#define __GO_UI_MIN__ 276
#define __GO_UI_RELIEF__ 277
#define __GO_UI_STRING__ 278
#define __GO_UI_STRING_SIZE__ 279
#define __GO_UI_STRING_COLNB__ 280
#define __GO_UI_TOOLTIPSTRING__ 281
#define __GO_UI_TOOLTIPSTRING_SIZE__ 282
#define __GO_UI_SLIDERSTEP__ 283
#define __GO_UI_UNITS__ 284
#define __GO_UI_VALUE__ 285
#define __GO_UI_VALUE_SIZE__ 286
#define __GO_UI_VERTICALALIGNMENT__ 287
#define __GO_UIPARENTMENU__ 288
#define __GO_UICHILDMENU__ 289
#define __GO_UICHECKEDMENU__ 290
#define __GO_UI_CHECKED__ 291
#define __GO_UI_LABEL__ 292
#define __GO_UI_MNEMONIC__ 293
#define __GO_UI_ACCELERATOR__ 294
#define __GO_UI_SEPARATOR__ 295
#define __GO_UI_ICON__ 296
#define __GO_CONSOLE__ 297
#define __GO_SHOWHIDDENHANDLES__ 298
#define __GO_WAITBAR__ 299
#define __GO_PROGRESSIONBAR__ 300
#define __GO_UI_MESSAGE__ 301
#define __GO_UI_MESSAGE_SIZE__ 302
#define __GO_DATATIP__ 303
#define __GO_DATATIP_DATA__ 304
#define __GO_DATATIP_ORIENTATION__ 305
#define __GO_DATATIP_3COMPONENT__ 306
#define __GO_DATATIP_AUTOORIENTATION__ 307
#define __GO_DATATIP_INTERP_MODE__ 308
#define __GO_DATATIP_DISPLAY_FNC__ 309
#define __GO_DATATIP_BOX_MODE__ 310
#define __GO_DATATIP_LABEL_MODE__ 311
#define __GO_AMBIENTCOLOR__ 312
#define __GO_DIFFUSECOLOR__ 313
#define __GO_SPECULARCOLOR__ 314
#define __GO_COLOR_MATERIAL__ 315
#define __GO_MATERIAL_SHININESS__ 316
#define __GO_LIGHT__ 317
#define __GO_LIGHT_TYPE__ 318
#define __GO_DATATIPS__ 319
#define __GO_DATATIPS_COUNT__ 320
#define __GO_DATATIP_INDEXES__ 321
#define __GO_DATA_MODEL_DISPLAY_FUNCTION__ 322
#define __GO_DATA_MODEL_DISPLAY_FUNCTION_SIZE__ 323
#define __GO_RESIZE__ 324
#define __GO_TOOLBAR__ 325
#define __GO_TOOLBAR_VISIBLE__ 326
#define __GO_MENUBAR__ 327
#define __GO_MENUBAR_VISIBLE__ 328
#define __GO_INFOBAR_VISIBLE__ 329
#define __GO_DOCKABLE__ 330
#define __GO_LAYOUT__ 331
#define __GO_LAYOUT_SET__ 332
#define __GO_UI_BORDER_CONSTRAINTS__ 333
#define __GO_UI_GRID_CONSTRAINTS__ 334
#define __GO_UI_TABGROUP__ 335
#define __GO_UI_TAB__ 336

#endif /* !__GRAPHIC_OBJECT_PROPERTIES_H__ */
