SHELL = /bin/sh

include ../../Path.incl
include ../../Version.incl
include ../../Makefile.incl

FFLAGS = $(FC_OPTIONS) $(FC_PICFLAGS) -I$(SCIDIR)/routines
CFLAGS = $(CC_OPTIONS) $(CC_PICFLAGS) -I$(SCIDIR)/routines
all:: 

