@del /Q LibScilab.def
@del /Q *.bak
@del /Q boolean.vcdef
@del /Q boolean_f.vcdef
@del /Q cacsd.vcdef
@del /Q cacsd_f.vcdef
@del /Q core.vcdef
@del /Q core_f.vcdef
@del /Q data_structures.vcdef
@del /Q data_structures_f.vcdef
@del /Q differential_equations.vcdef
@del /Q differential_equations_f.vcdef
@del /Q double.vcdef
@del /Q double_f.vcdef
@del /Q elementary_functions.vcdef
@del /Q elementary_functions_f.vcdef
@del /Q sparse.vcdef
@del /Q special_functions.vcdef
@del /Q special_functions_f.vcdef

