
@del /Q LibScilab.def
@del /Q *.bak
@del /Q boolean.vcdef
@del /Q boolean_f.vcdef
@del /Q cacsd.vcdef
@del /Q cacsd_f.vcdef
@del /Q core.vcdef
@del /Q core_f.vcdef
@del /Q data_structures.vcdef
@del /Q data_structures_f.vcdef
@del /Q dcd_f.vcdef
@del /Q differential_equations.vcdef
@del /Q differential_equations_f.vcdef
@del /Q double.vcdef
@del /Q double_f.vcdef
@del /Q elementaries_functions.vcdef
@del /Q elementaries_functions_f.vcdef
@del /Q fileio.vcdef
@del /Q gd.vcdef
@del /Q graphics.vcdef
@del /Q GUI.vcdef
@del /Q GUI_f.vcdef
@del /Q integer.vcdef
@del /Q integer_f.vcdef
@del /Q interpolation.vcdef
@del /Q interpolation_f.vcdef
@del /Q intersci.vcdef
@del /Q io.vcdef
@del /Q io_f.vcdef
@del /Q linear_algebra.vcdef
@del /Q linear_algebra_f.vcdef
@del /Q metanet.vcdef
@del /Q optim.vcdef
@del /Q optim_f.vcdef
@del /Q polynomials.vcdef
@del /Q polynomials_f.vcdef
@del /Q randlib.vcdef
@del /Q randlib_f.vcdef
@del /Q scicos.vcdef
@del /Q scicos_f.vcdef
@del /Q signal.vcdef
@del /Q signal_f.vcdef
@del /Q slicot_f.vcdef
@del /Q sparse.vcdef
@del /Q special_functions.vcdef
@del /Q special_functions_f.vcdef
@del /Q statistics.vcdef
@del /Q string.vcdef
@del /Q string_f.vcdef
@del /Q symbolic.vcdef
@del /Q symbolic_f.vcdef
@del /Q Wintools.vcdef
@del /Q wsci.vcdef
@del /Q xdr.vcdef
