#include "CenteredTextDrawerGL.hxx"
/* Generated by GIWS (version 1.0) */
/*

Copyright 2007 INRIA

Author : Sylvestre Ledru

This software is a computer program whose purpose is to hide the complexity
of accessing Java objects/methods from C++ code.

This software is governed by the CeCILL-B license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the CeCILL-B
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL-B license and that you accept its terms.
*/

namespace org_scilab_modules_renderer_textDrawing {

// Returns the current env

JNIEnv * CenteredTextDrawerGL::getCurrentEnv() {
JNIEnv * curEnv = NULL;
this->jvm->AttachCurrentThread((void **) &curEnv, NULL);
return curEnv;
}
// Destructor

CenteredTextDrawerGL::~CenteredTextDrawerGL() {
JNIEnv * curEnv = NULL;
this->jvm->AttachCurrentThread((void **) &curEnv, NULL);

curEnv->DeleteGlobalRef(this->instance);
curEnv->DeleteGlobalRef(this->instanceClass);
curEnv->DeleteGlobalRef(this->stringArrayClass);}
// Constructors

CenteredTextDrawerGL::CenteredTextDrawerGL(JavaVM * jvm_) {
jmethodID constructObject = NULL ;
jobject localInstance ;
jclass localClass ;
const std::string construct="<init>";
const std::string param="()V";
jvm=jvm_;

JNIEnv * curEnv = getCurrentEnv();

localClass = curEnv->FindClass( this->className().c_str() ) ;
if (localClass == NULL) {
std::cerr << "Could not get the Class " << this->className() <<  std::endl;
exit(EXIT_FAILURE);
}

this->instanceClass = (jclass) curEnv->NewGlobalRef(localClass) ;
if (this->instanceClass == NULL) {
std::cerr << "Could not create a Global Ref of " << this->className() <<  std::endl;
exit(EXIT_FAILURE);
}

/* localClass is not needed anymore */
curEnv->DeleteLocalRef(localClass);

constructObject = curEnv->GetMethodID( this->instanceClass, construct.c_str() , param.c_str() ) ;
if(constructObject == NULL){
std::cerr << "Could not retrieve the constructor of the class " << this->className() << " with the profile : " << construct << param << std::endl;
exit(EXIT_FAILURE);
}

localInstance = curEnv->NewObject( this->instanceClass, constructObject ) ;
if(localInstance == NULL){
std::cerr << "Could not instantiate the object " << this->className() << " with the constructor : " << construct << param << std::endl;
exit(EXIT_FAILURE);
}
 
this->instance = curEnv->NewGlobalRef(localInstance) ;
if(this->instance == NULL){
std::cerr << "Could not create a new global ref of " << this->className() << std::endl;
exit(EXIT_FAILURE);
}
/* localInstance not needed anymore */
curEnv->DeleteLocalRef(localInstance);

                /* Methods ID set to NULL */
voiddisplayID=NULL; 
voidinitializeDrawingjintID=NULL; 
voidendDrawingID=NULL; 
voidshowjintID=NULL; 
voiddestroyjintID=NULL; 
voidsetFigureIndexjintID=NULL; 
voidsetTextParametersjintjintjintjdoublejdoublejintjintID=NULL; 
voidsetTextContentjobjectArrayjintjintID=NULL; 

jclass localStringArrayClass = curEnv->FindClass("Ljava/lang/String;");
stringArrayClass = (jclass) curEnv->NewGlobalRef(localStringArrayClass);
curEnv->DeleteLocalRef(localStringArrayClass);
voidsetCenterPositionjdoublejdoublejdoubleID=NULL; 
voiddrawTextContentID=NULL; 
jdoubleArraygetBoundingRectangleID=NULL; 
jintArraygetScreenBoundingBoxID=NULL; 


}

CenteredTextDrawerGL::CenteredTextDrawerGL(JavaVM * jvm_, jobject JObj) {
        jvm=jvm_;

        JNIEnv * curEnv = getCurrentEnv();

jclass localClass = curEnv->GetObjectClass(JObj);
        this->instanceClass = (jclass) curEnv->NewGlobalRef(localClass);
        curEnv->DeleteLocalRef(localClass);

        if (this->instanceClass == NULL) {
               std::cerr << "Could not create a Global Ref of " << this->instanceClass <<  std::endl;
               exit(EXIT_FAILURE);
   
        }

        this->instance = curEnv->NewGlobalRef(JObj) ;
        if(this->instance == NULL){
               std::cerr << "Could not create a new global ref of " << this->instanceClass << std::endl;
               exit(EXIT_FAILURE);
        }
        /* Methods ID set to NULL */
        voiddisplayID=NULL; 
voidinitializeDrawingjintID=NULL; 
voidendDrawingID=NULL; 
voidshowjintID=NULL; 
voiddestroyjintID=NULL; 
voidsetFigureIndexjintID=NULL; 
voidsetTextParametersjintjintjintjdoublejdoublejintjintID=NULL; 
voidsetTextContentjobjectArrayjintjintID=NULL; 

jclass localStringArrayClass = curEnv->FindClass("Ljava/lang/String;");
stringArrayClass = (jclass) curEnv->NewGlobalRef(localStringArrayClass);
curEnv->DeleteLocalRef(localStringArrayClass);
voidsetCenterPositionjdoublejdoublejdoubleID=NULL; 
voiddrawTextContentID=NULL; 
jdoubleArraygetBoundingRectangleID=NULL; 
jintArraygetScreenBoundingBoxID=NULL; 


}

// Generic methods


void CenteredTextDrawerGL::synchronize() {
if (getCurrentEnv()->MonitorEnter(instance) != JNI_OK) {
std::cerr << "Fail to enter monitor." << std::endl;
exit(EXIT_FAILURE);
}
}


void CenteredTextDrawerGL::endSynchronize() {
if ( getCurrentEnv()->MonitorExit(instance) != JNI_OK) {
std::cerr << "Fail to exit monitor." << std::endl;
exit(EXIT_FAILURE);
}
}

// Method(s)

void CenteredTextDrawerGL::display (){

JNIEnv * curEnv = getCurrentEnv();

if (voiddisplayID==NULL) { /* Use the cache Luke */ voiddisplayID = curEnv->GetMethodID(this->instanceClass, "display", "()V" ) ;
if (voiddisplayID == NULL) {
std::cerr << "Could not access to the method " << "display" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voiddisplayID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::initializeDrawing (long figureIndex){

JNIEnv * curEnv = getCurrentEnv();

if (voidinitializeDrawingjintID==NULL) { /* Use the cache Luke */ voidinitializeDrawingjintID = curEnv->GetMethodID(this->instanceClass, "initializeDrawing", "(I)V" ) ;
if (voidinitializeDrawingjintID == NULL) {
std::cerr << "Could not access to the method " << "initializeDrawing" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidinitializeDrawingjintID ,figureIndex);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::endDrawing (){

JNIEnv * curEnv = getCurrentEnv();

if (voidendDrawingID==NULL) { /* Use the cache Luke */ voidendDrawingID = curEnv->GetMethodID(this->instanceClass, "endDrawing", "()V" ) ;
if (voidendDrawingID == NULL) {
std::cerr << "Could not access to the method " << "endDrawing" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidendDrawingID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::show (long figureIndex){

JNIEnv * curEnv = getCurrentEnv();

if (voidshowjintID==NULL) { /* Use the cache Luke */ voidshowjintID = curEnv->GetMethodID(this->instanceClass, "show", "(I)V" ) ;
if (voidshowjintID == NULL) {
std::cerr << "Could not access to the method " << "show" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidshowjintID ,figureIndex);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::destroy (long parentFigureIndex){

JNIEnv * curEnv = getCurrentEnv();

if (voiddestroyjintID==NULL) { /* Use the cache Luke */ voiddestroyjintID = curEnv->GetMethodID(this->instanceClass, "destroy", "(I)V" ) ;
if (voiddestroyjintID == NULL) {
std::cerr << "Could not access to the method " << "destroy" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voiddestroyjintID ,parentFigureIndex);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::setFigureIndex (long figureIndex){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetFigureIndexjintID==NULL) { /* Use the cache Luke */ voidsetFigureIndexjintID = curEnv->GetMethodID(this->instanceClass, "setFigureIndex", "(I)V" ) ;
if (voidsetFigureIndexjintID == NULL) {
std::cerr << "Could not access to the method " << "setFigureIndex" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidsetFigureIndexjintID ,figureIndex);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::setTextParameters (long textAlignment, long color, long fontStyle, double fontSize, double rotationAngle, long boxWidth, long boxHeight){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetTextParametersjintjintjintjdoublejdoublejintjintID==NULL) { /* Use the cache Luke */ voidsetTextParametersjintjintjintjdoublejdoublejintjintID = curEnv->GetMethodID(this->instanceClass, "setTextParameters", "(IIIDDII)V" ) ;
if (voidsetTextParametersjintjintjintjdoublejdoublejintjintID == NULL) {
std::cerr << "Could not access to the method " << "setTextParameters" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidsetTextParametersjintjintjintjdoublejdoublejintjintID ,textAlignment, color, fontStyle, fontSize, rotationAngle, boxWidth, boxHeight);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::setTextContent (char ** text, int textSize, long nbRow, long nbCol){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetTextContentjobjectArrayjintjintID==NULL) { /* Use the cache Luke */ voidsetTextContentjobjectArrayjintjintID = curEnv->GetMethodID(this->instanceClass, "setTextContent", "([Ljava/lang/String;II)V" ) ;
if (voidsetTextContentjobjectArrayjintjintID == NULL) {
std::cerr << "Could not access to the method " << "setTextContent" << std::endl;
exit(EXIT_FAILURE);
}
}jclass stringArrayClass = curEnv->FindClass("Ljava/lang/String;");

// create java array of strings.
jobjectArray text_ = curEnv->NewObjectArray( textSize, stringArrayClass, NULL);
if (text_ == NULL)
{
std::cerr << "Could not allocate Java string array, memory full." << std::endl;
exit(EXIT_FAILURE);
}

// convert each char * to java strings and fill the java array.
for ( int i = 0; i < textSize; i++)
{
jstring TempString = curEnv->NewStringUTF( text[i] );
if (TempString == NULL)
{
std::cerr << "Could not convert C string to Java UTF string, memory full." << std::endl;
exit(EXIT_FAILURE);
}

curEnv->SetObjectArrayElement( text_, i, TempString);

// avoid keeping reference on to many strings
curEnv->DeleteLocalRef(TempString);
}
                         curEnv->CallVoidMethod( this->instance, voidsetTextContentjobjectArrayjintjintID ,text_, nbRow, nbCol);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        curEnv->DeleteLocalRef(stringArrayClass);
curEnv->DeleteLocalRef(text_);

}

void CenteredTextDrawerGL::setCenterPosition (double centerX, double centerY, double centerZ){

JNIEnv * curEnv = getCurrentEnv();

if (voidsetCenterPositionjdoublejdoublejdoubleID==NULL) { /* Use the cache Luke */ voidsetCenterPositionjdoublejdoublejdoubleID = curEnv->GetMethodID(this->instanceClass, "setCenterPosition", "(DDD)V" ) ;
if (voidsetCenterPositionjdoublejdoublejdoubleID == NULL) {
std::cerr << "Could not access to the method " << "setCenterPosition" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voidsetCenterPositionjdoublejdoublejdoubleID ,centerX, centerY, centerZ);
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

void CenteredTextDrawerGL::drawTextContent (){

JNIEnv * curEnv = getCurrentEnv();

if (voiddrawTextContentID==NULL) { /* Use the cache Luke */ voiddrawTextContentID = curEnv->GetMethodID(this->instanceClass, "drawTextContent", "()V" ) ;
if (voiddrawTextContentID == NULL) {
std::cerr << "Could not access to the method " << "drawTextContent" << std::endl;
exit(EXIT_FAILURE);
}
}
                         curEnv->CallVoidMethod( this->instance, voiddrawTextContentID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
}

double * CenteredTextDrawerGL::getBoundingRectangle (){

JNIEnv * curEnv = getCurrentEnv();

if (jdoubleArraygetBoundingRectangleID==NULL) { /* Use the cache Luke */ jdoubleArraygetBoundingRectangleID = curEnv->GetMethodID(this->instanceClass, "getBoundingRectangle", "()[D" ) ;
if (jdoubleArraygetBoundingRectangleID == NULL) {
std::cerr << "Could not access to the method " << "getBoundingRectangle" << std::endl;
exit(EXIT_FAILURE);
}
}
                        jdoubleArray res =  (jdoubleArray) curEnv->CallObjectMethod( this->instance, jdoubleArraygetBoundingRectangleID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
jsize len = curEnv->GetArrayLength(res);
jboolean isCopy = JNI_FALSE;

/* faster than getXXXArrayElements */
jdouble *resultsArray = (jdouble *) curEnv->GetPrimitiveArrayCritical(res, &isCopy);
double * myArray= new double[len];

for (jsize i = 0; i < len; i++){
myArray[i]=resultsArray[i];
}
curEnv->ReleasePrimitiveArrayCritical(res, resultsArray, JNI_ABORT);

                        curEnv->DeleteLocalRef(res);

return myArray;

}

long * CenteredTextDrawerGL::getScreenBoundingBox (){

JNIEnv * curEnv = getCurrentEnv();

if (jintArraygetScreenBoundingBoxID==NULL) { /* Use the cache Luke */ jintArraygetScreenBoundingBoxID = curEnv->GetMethodID(this->instanceClass, "getScreenBoundingBox", "()[I" ) ;
if (jintArraygetScreenBoundingBoxID == NULL) {
std::cerr << "Could not access to the method " << "getScreenBoundingBox" << std::endl;
exit(EXIT_FAILURE);
}
}
                        jintArray res =  (jintArray) curEnv->CallObjectMethod( this->instance, jintArraygetScreenBoundingBoxID );
                        
if (curEnv->ExceptionOccurred()) {
curEnv->ExceptionDescribe() ;
}

                        
jsize len = curEnv->GetArrayLength(res);
jboolean isCopy = JNI_FALSE;

/* faster than getXXXArrayElements */
jint *resultsArray = (jint *) curEnv->GetPrimitiveArrayCritical(res, &isCopy);
long * myArray= new long[len];

for (jsize i = 0; i < len; i++){
myArray[i]=resultsArray[i];
}
curEnv->ReleasePrimitiveArrayCritical(res, resultsArray, JNI_ABORT);

                        curEnv->DeleteLocalRef(res);

return myArray;

}

}
