//
// Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
// Copyright (C) 2008 - INRIA - Serge Steer <Serge.Steer@scilab.org>
//
// This file is distributed under the same license as the Scilab package.
//

function update_height(h)
  global levitron_controls
  Slider_Height=levitron_controls(1,1)
  Value_Height=levitron_controls(1,2)
  if argn(2)==1 then
    Slider_Height.Value=(h-1.6)*100/0.2;
  else
    h=Slider_Height.Value
    h=max(0.001,1.6+h*0.2/100)
  end
  Value_Height.String=msprintf("%.3f",h)
  update_state(3,h)
endfunction
function update_theta(t)
  global levitron_controls
  Slider_Theta=levitron_controls(2,1)
  Value_Theta=levitron_controls(2,2)
  if argn(2)==1 then
    Slider_Theta.Value=t*100;
  else
    t=Slider_Theta.Value
    t=t/100
  end
  Value_Theta.String=msprintf("%.3f",t)
  update_state(4,t)
endfunction
function update_phi(p)
  global levitron_controls
  Slider_Phi=levitron_controls(3,1)
  Value_Phi=levitron_controls(3,2)
  if argn(2)==1 then
    Slider_Phi.Value=p*100/360;
  else
    p=Slider_Phi.Value
    p=360*p/100
  end
  Value_Phi.String=msprintf("%.3f",p)
  update_state(5,p)
endfunction
function update_psi(p)
  global levitron_controls
  Slider_Psi=levitron_controls(4,1)
  Value_Psi=levitron_controls(4,2)
  if argn(2)==1 then
    Slider_Psi.Value=p*100/360;
  else
    p=Slider_Psi.Value
    p=360*p/100
  end
  Value_Psi.String=msprintf("%.3f",p)
  update_state(6,p)
endfunction

function levitron_gui()
  global levitron_controls
  fig=gcf();
  w=fig.axes_size;
  m=20;
  lslider=150;h=20;
  lv=40;
  xs=w(1)-lslider-lv-m-10;
  xv=xs+lslider+10;
  SliderStep=[0.001 0.001]
  
  yh=w(2)-(m+h);
  Height_title = uicontrol( ...
      "parent"              , fig,...
      "style"               , "text",...
      "string"              , "Height",...
      "units"               , "pixels",...
      "position"            , [xs yh+h lslider h],...
      "fontunits"           , "points",...
      "fontsize"            , 9,...
      "horizontalalignment" , "center", ...
      "background"          , [1 1 1], ...
      "tag"                 , "HeightTitle" ...
      );

  
  Slider_Height=uicontrol("parent",fig,..
	      "style","slider",..
	      "Min",0,..
	      "Max",100,..
	      "Value",1+100*0.72,..
	      "units","pixels",..
              "position"            , [xs yh lslider h],...
	      "tag"                 , "Height", ...
	      "callback"            , "update_height()" ...
	      );
  Value_Height = uicontrol("parent",fig,..
			   "Position"  , [xv yh lv h],...
			   "Style"     , "text",...
			   "String"    , "70",...
			   "BackgroundColor",[1 1 1]);
  
  yt=yh-(m+h);
  Theta_title = uicontrol( ...
      "parent"              , fig,...
      "style"               , "text",...
      "string"              , "Theta",...
      "units"               , "pixels",...
      "position"            , [xs yt+h lslider h],...
      "fontunits"           , "points",...
      "fontsize"            , 9,...
      "horizontalalignment" , "center", ...
      "background"          , [1 1 1], ...
      "tag"                 , "ThetaTitle" ...
      );

  Slider_Theta=uicontrol("parent",fig,..
			 "style","slider",..
			 "Min",0,..
			 "Max",100,..
			 "Value",70,..
			 "units","pixels",..
			 "position"            , [xs yt lslider h],...
			 "tag"                 , "Theta", ...
			 "callback"            , "update_theta()" ...
			 );
  Value_Theta = uicontrol("parent",fig,..
			   "Position"  , [xv yt lv h],...
			   "Style"     , "text",...
			   "String"    , "70",...
			   "BackgroundColor",[1 1 1]);
  yphi=yt-(m+h);
  Phi_title = uicontrol( ...
      "parent"              , fig,...
      "style"               , "text",...
      "string"              , "Phi",...
      "units"               , "pixels",...
      "position"            , [xs yphi+h lslider h],...
      "fontunits"           , "points",...
      "fontsize"            , 9,...
      "horizontalalignment" , "center", ...
      "background"          , [1 1 1], ...
      "tag"                 , "PhiTitle" ...
      );

  Slider_Phi=uicontrol("parent",fig,..
		       "style","slider",..
		       "Min",0,..
		       "Max",100,..
		       "Value",70,..
		       "units","pixels",..
		       "position"            , [xs yphi l h],...
		       "tag"                 , "Phi", ...
		       "callback"            , "update_phi()" ...
		       );
  Value_Phi = uicontrol("parent",fig,..
			"Position"  , [xv yphi lv h],...
			"Style"     , "text",...
			"String"    , "70",...
			"BackgroundColor",[1 1 1]);

  ypsi=yphi-(m+h);
  Psi_title = uicontrol( ...
      "parent"              , fig,...
      "style"               , "text",...
      "string"              , "Psi",...
      "units"               , "pixels",...
      "position"            , [xs ypsi+h lslider h],...
      "fontunits"           , "points",...
      "fontsize"            , 9,...
      "horizontalalignment" , "center", ...
      "background"          , [1 1 1], ...
      "tag"                 , "PsiTitle" ...
      );

  Slider_Psi=uicontrol("parent",fig,..
		       "style","slider",..
		       "Min",0,..
		       "Max",100,..
		       "Value",70,..
		       "units","pixels",..
		       "position"            , [xs ypsi l h],...
		       "tag"                 , "Psi", ...
		       "callback"            , "update_psi()" ...
		       );
    Value_Psi = uicontrol("parent",fig,..
			"Position"  , [xv ypsi lv h],...
			"Style"     , "text",...
			"String"    , "70",...
			"BackgroundColor",[1 1 1]);

    ybtn= ypsi -(m+h);  
    wb=40;eb=13;
    Start = uicontrol("parent",fig, ..
		       "Position"  , [xs ybtn wb h],...
		       "Style"     , "pushbutton",...
		       "String"    , "Start",...
		       "callback"  , "levitron_start()");
    Stop = uicontrol("parent",fig, ..
		       "Position"  , [xs+wb+eb ybtn wb h],...
		       "Style"     , "pushbutton",...
		       "String"    , "Stop",...
		       "callback"  , "levitron_stop()");
    Reinit = uicontrol("parent",fig, ..
		       "Position"  , [xs+2*(wb+eb) ybtn wb h],...
		       "Style"     , "pushbutton",...
		       "String"    , "Reinit",...
		       "callback"  , "levitron_reinit()");


    levitron_controls=[Slider_Height Value_Height
		       Slider_Theta Value_Theta
		       Slider_Phi Value_Phi
		       Slider_Psi Value_Psi]
    
    update_height(1.72)
    update_theta(0.28)
    update_phi(0)
    update_psi(0)
endfunction
function levitron_start()
  global  Stop;Stop=%f;
  show();
endfunction
function levitron_stop()
  global Stop;Stop=%t
endfunction
function levitron_reinit()
  global y0 y1  Stop
  Stop=%t
  y1=y0
  update_height(1.72)
  update_theta(0.28)
  update_phi(0)
  update_psi(0)
endfunction
