SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include ../../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = scsthresholdlib
NAM = SCI/macros/scicos_blocks/Threshold

MACROS= GENERAL_f.sci  NEGTOPOS_f.sci  POSTONEG_f.sci  ZCROSS_f.sci

include ../../Make.lib
