/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class ObjectDataJNI {

  static {
    try {
        System.loadLibrary("scigraphic_objects");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native Object getChampX(String jarg1);
  public final static native Object getChampY(String jarg1);
  public final static native Object getArrows(String jarg1);
  public final static native Object getSegsData(String jarg1);
  public final static native Object getFecTriangles(String jarg1);
  public final static native Object getFecData(String jarg1);
  public final static native Object getArcUpperLeftPoint(String jarg1);
  public final static native Object getArcData(String jarg1);
}
