/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class ObjectData {
    public static Object getChampX(String uid) {
        return ObjectDataJNI.getChampX(uid);
    }

    public static Object getChampY(String uid) {
        return ObjectDataJNI.getChampY(uid);
    }

    public static Object getArrows(String uid) {
        return ObjectDataJNI.getArrows(uid);
    }

    public static Object getSegsData(String uid) {
        return ObjectDataJNI.getSegsData(uid);
    }

    public static Object getFecTriangles(String uid) {
        return ObjectDataJNI.getFecTriangles(uid);
    }

    public static Object getFecData(String uid) {
        return ObjectDataJNI.getFecData(uid);
    }

}
