/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class PolylineData {
    public static Object getDataX(String uid) {
        return PolylineDataJNI.getDataX(uid);
    }

    public static Object getDataY(String uid) {
        return PolylineDataJNI.getDataY(uid);
    }

    public static Object getDataZ(String uid) {
        return PolylineDataJNI.getDataZ(uid);
    }

    public static Object getShiftX(String uid) {
        return PolylineDataJNI.getShiftX(uid);
    }

    public static Object getShiftY(String uid) {
        return PolylineDataJNI.getShiftY(uid);
    }

    public static Object getShiftZ(String uid) {
        return PolylineDataJNI.getShiftZ(uid);
    }

    public static int isZCoordSet(String uid) {
        return PolylineDataJNI.isZCoordSet(uid);
    }

    public static int isXShiftSet(String uid) {
        return PolylineDataJNI.isXShiftSet(uid);
    }

    public static int isYShiftSet(String uid) {
        return PolylineDataJNI.isYShiftSet(uid);
    }

    public static int isZShiftSet(String uid) {
        return PolylineDataJNI.isZShiftSet(uid);
    }

    public static String createPolylineData(String uidFrom, String uidTo) {
        return PolylineDataJNI.createPolylineData(uidFrom, uidTo);
    }

    public static int translatePolyline(String uid, double x, double y, double z, int flagX, int flagY, int flagZ) {
        return PolylineDataJNI.translatePolyline(uid, x, y, z, flagX, flagY, flagZ);
    }

    public static int translatePoint(String uid, int index, double x, double y, double z, int flagX, int flagY, int flagZ) {
        return PolylineDataJNI.translatePoint(uid, index, x, y, z, flagX, flagY, flagZ);
    }

    public static int setPointValue(String uid, int index, double x, double y, double z) {
        return PolylineDataJNI.setPointValue(uid, index, x, y, z);
    }

    public static int insertPoint(String uid, int index, double x, double y, double z) {
        return PolylineDataJNI.insertPoint(uid, index, x, y, z);
    }

    public static int removePoint(String uid, int index) {
        return PolylineDataJNI.removePoint(uid, index);
    }

}
