/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class ScilabNativeWebView {
  public static void ScilabNativeWebView__createObject(int id) {
    ScilabNativeWebViewJNI.ScilabNativeWebView__createObject(id);
  }

  public static void ScilabNativeWebView__deleteObject(int id) {
    ScilabNativeWebViewJNI.ScilabNativeWebView__deleteObject(id);
  }

  public static void ScilabNativeWebView__updateObject(int id, int iProperty) {
    ScilabNativeWebViewJNI.ScilabNativeWebView__updateObject(id, iProperty);
  }

}
