exec ext1c.sce
exec ext1f.sce
exec ext2c.sce
exec ext2f.sce
exec ext3c.sce
exec ext3f.sce
exec ext4c.sce
exec ext4f.sce
exec ext5c.sce
exec ext5f.sce
exec ext6c.sce
exec ext6f.sce
exec ext7c.sce
exec ext7f.sce
exec ext8c.sce
exec ext8f.sce
exec ext9c.sce
exec ext9f.sce
exec ext10c.sce
exec ext10f.sce
exec ext11c.sce
exec ext11f.sce
exec ext12c.sce
exec ext12f.sce
exec ext13c.sce
exec ext13f.sce
exec ext14c.sce
exec ext14f.sce
