#define SCI_ERRMSG1				"incorrect assignment"
#define SCI_ERRMSG2				"invalid factor"
#define SCI_ERRMSG3				"waiting for right parenthesis"
#define SCI_ERRMSG4				"undefined variable : %s"
#define SCI_ERRMSG5				"inconsistent column/row dimensions"
#define SCI_ERRMSG6				"inconsistent row/column dimensions"
#define SCI_ERRMSG7				"dot cannot be used as modifier for this operator"
#define SCI_ERRMSG8				"inconsistent addition"
#define SCI_ERRMSG9				"inconsistent subtraction"
#define SCI_ERRMSG10			"inconsistent multiplication"
#define SCI_ERRMSG11			"inconsistent right division "
#define SCI_ERRMSG12			"inconsistent left division"
#define SCI_ERRMSG13			"redefining permanent variable"
#define SCI_ERRMSG14			"eye variable undefined in this context"
#define SCI_ERRMSG15			"submatrix incorrectly defined"
#define SCI_ERRMSG16			"incorrect command!"
#define SCI_ERRMSG17_1			"stack size exceeded! (Use stacksize function to increase it)"
#define SCI_ERRMSG17_2			"Memory used for variables :"
#define SCI_ERRMSG17_3			"Intermediate memory needed:"
#define SCI_ERRMSG17_4			"Total  memory available   :"
#define SCI_ERRMSG18			"too many variables!"
#define SCI_ERRMSG19			"Problem is singular"
#define SCI_ERRMSG20_1			"th argument must be square matrix"
#define SCI_ERRMSG20_2			"first argument must be square matrix"
#define SCI_ERRMSG21			"invalid index"
#define SCI_ERRMSG22			" recursion problems. Sorry...."
#define SCI_ERRMSG23			" Matrix norms available are 1, 2, inf, and fro"
#define SCI_ERRMSG24			"convergence problem..."
#define SCI_ERRMSG25			"bad call to primitive :"
#define SCI_ERRMSG26			"too complex recursion! (recursion tables are full))"
#define SCI_ERRMSG27			"division by zero..."
#define SCI_ERRMSG28			"empty function..."
#define SCI_ERRMSG29			"matrix is not positive definite"
#define SCI_ERRMSG30			"invalid exponent"
#define SCI_ERRMSG31			"incorrect string"
#define SCI_ERRMSG32			"singularity of log or tan function"
#define SCI_ERRMSG33			"too many ':'"
#define SCI_ERRMSG34			"incorrect control intruction syntax"
#define SCI_ERRMSG35_1			"Syntax error in an if instruction"
#define SCI_ERRMSG35_2			"Syntax error in a while instruction"
#define SCI_ERRMSG35_3 			"Syntax error in a select/case instruction"
#define SCI_ERRMSG36_1			"th argument is incorrect here"
#define SCI_ERRMSG36_2			"first argument is incorrect"
#define SCI_ERRMSG37			"incorrect function at line	"
#define SCI_ERRMSG38			"file name incorrect"
#define SCI_ERRMSG39			"incorrect number of arguments"
#define SCI_ERRMSG40			"waiting for end of command"
#define SCI_ERRMSG41			"incompatible LHS"
#define SCI_ERRMSG42			"incompatible RHS"
#define SCI_ERRMSG43			"not implemented in scilab...."
#define SCI_ERRMSG44_1			"th argument is incorrect"
#define SCI_ERRMSG44_2 			"first argument is incorrect"
#define SCI_ERRMSG45			"null matrix (argument #"
#define SCI_ERRMSG46			"incorrect syntax"
#define SCI_ERRMSG47			" end or else is missing..."
#define SCI_ERRMSG48			" input line longer than buffer size:"
#define SCI_ERRMSG49			"incorrect file or format"
#define SCI_ERRMSG50			"subroutine not found :	"
#define SCI_ERRMSG51			"th argument must be a real matrix"
#define SCI_ERRMSG52_1 			"th argument must be a real matrix"
#define SCI_ERRMSG52_2 			"argument must be a real matrix"
#define SCI_ERRMSG53_1 			"th input is invalid (waiting for real or complex matrix)	"
#define SCI_ERRMSG53_2 			"invalid input (waiting for real or complex matrix)	"
#define SCI_ERRMSG54_1			"th argument type must be polynomial"
#define SCI_ERRMSG54_2			"argument type must be polynomial"
#define SCI_ERRMSG55_1			"th argument type must be character string"
#define SCI_ERRMSG55_2			"argument type must be  character string"
#define SCI_ERRMSG56_1			"th argument must be a list"
#define SCI_ERRMSG56_2			"argument must be a list"
#define SCI_ERRMSG57			"problem with comparison symbol..."
#define SCI_ERRMSG58_1			"function has no input argument..."
#define SCI_ERRMSG58_2			"incorrect number of arguments in function call..."
#define SCI_ERRMSG58_3			"arguments are :"
#define SCI_ERRMSG59_1			"function has no output"
#define SCI_ERRMSG59_2			"incorrect # of outputs in the function"
#define SCI_ERRMSG59_3			"arguments are :"
#define SCI_ERRMSG60			"argument with incompatible dimensions"
#define SCI_ERRMSG61			"direct acces : give format"
#define SCI_ERRMSG62			"end of file at line	"
#define SCI_ERRMSG63			"graphic terminal?"
#define SCI_ERRMSG64			"integration fails"
#define SCI_ERRMSG65			": logical unit already used"
#define SCI_ERRMSG66			"no more logical units available!"
#define SCI_ERRMSG67			"unknown file format "
#define SCI_ERRMSG68_1			"fatal error!!! your variables are saved in file :"
#define SCI_ERRMSG68_2			" bad call to a scilab function ? check"
#define SCI_ERRMSG68_3			" ... otherwise send a bug report to : the Scilab group"
#define SCI_ERRMSG69			"floating point exception"
#define SCI_ERRMSG70			"too many arguments in fort (max 30)"
#define SCI_ERRMSG71			"this variable is not valid in fort"
#define SCI_ERRMSG72			"is not valid in this context"
#define SCI_ERRMSG73			"error while linking"
#define SCI_ERRMSG74			"Leading coefficient is zero"
#define SCI_ERRMSG75			"Too high degree (max 100)"
#define SCI_ERRMSG76_1			"for x=val with type(val)="
#define SCI_ERRMSG76_2			" is not implemented in Scilab"
#define SCI_ERRMSG77			" : wrong number of rhs arguments"
#define SCI_ERRMSG78			" : wrong number of lhs arguments"
#define SCI_ERRMSG80			" incorrect function (argument n:"
#define SCI_ERRMSG81_1			"Argument "
#define SCI_ERRMSG81_2			" : wrong type argument, expecting a "
#define SCI_ERRMSG81_3			" real or complex matrix"
#define SCI_ERRMSG82_1			"Argument "
#define SCI_ERRMSG82_2			" : wrong type argument, expecting a real matrix"
#define SCI_ERRMSG83_1			"Argument "
#define SCI_ERRMSG83_2			" : wrong type argument, expecting a real vector"
#define SCI_ERRMSG84_1			"Argument "
#define SCI_ERRMSG84_2			" : wrong type argument, expecting a scalar"
#define SCI_ERRMSG85			"host does not answer..."
#define SCI_ERRMSG86			"uncontrollable system"
#define SCI_ERRMSG87			"unobservable system"
#define SCI_ERRMSG88			"sfact : singular  or assymetric problem"
#define SCI_ERRMSG89_1			"th argument has incorrect dimensions"
#define SCI_ERRMSG89_2			"argument has incorrect dimensions"
#define SCI_ERRMSG90_1			"th argument must be a transfer matrix"
#define SCI_ERRMSG90_2			"argument must be a transfer matrix"
#define SCI_ERRMSG91_1			"th argument must be in state space form"
#define SCI_ERRMSG91_2			"argument must be in state space form"
#define SCI_ERRMSG92_1			"th argument must be a rational matrix"
#define SCI_ERRMSG92_2			"argument must be a rational matrix"
#define SCI_ERRMSG93_1			"th argument must be in continuous time"
#define SCI_ERRMSG93_2			"waiting for continuous time..."
#define SCI_ERRMSG94_1			"th argument must be in discrete time"
#define SCI_ERRMSG94_2			"argument must be in discrete time"
#define SCI_ERRMSG95_1			"th argument must "
#define SCI_ERRMSG95_2			"argument must be SISO"
#define SCI_ERRMSG96_1			"time domain of "
#define SCI_ERRMSG96_2			" th argument is not defined"
#define SCI_ERRMSG96_3			"time domain of argument is not defined"
#define SCI_ERRMSG97_1			"th argument must be a system "
#define SCI_ERRMSG97_2			"in state space or transfer matrix form"
#define SCI_ERRMSG97_3			"input argument must be a system in state space or transfer matrix form"
#define SCI_ERRMSG98			" variable returned by scilab argument function is incorrect"
#define SCI_ERRMSG99_1			" elements of "
#define SCI_ERRMSG99_2			"th must be in increasing order!"
#define SCI_ERRMSG99_3			"elements of first argument are not (strictly) increasing"
#define SCI_ERRMSG100_1			"the elements of "
#define SCI_ERRMSG100_2			"th argument are not in (strictly) decreasing order"
#define SCI_ERRMSG100_3			"elements of first argument are not in (strictly) decreasing order"
#define SCI_ERRMSG101_1			"last element of "
#define SCI_ERRMSG101_2			"th argument <>  first"
#define SCI_ERRMSG101_3			"last element of first argument does not matches the first one"
#define SCI_ERRMSG102_1			"variable or function "
#define SCI_ERRMSG102_2			" is not in file "
#define SCI_ERRMSG103_1			" variable "
#define SCI_ERRMSG103_2			" is not a valid rational function "
#define SCI_ERRMSG104_1			" variable "
#define SCI_ERRMSG104_2			" is not a valid state space representation"
#define SCI_ERRMSG105			"undefined fonction"
#define SCI_ERRMSG106			" fonction name already used"
#define SCI_ERRMSG107_1			"too many functions are defined (maximum #:"
#define SCI_ERRMSG108			"too complex for scilab, may be a too longcontrol instruction"
#define SCI_ERRMSG109			"too large, can't be displayed"
#define SCI_ERRMSG110_1			" was a function when"
#define SCI_ERRMSG110_2			" compiled but is now a primitive!"
#define SCI_ERRMSG111			"trying to re-define  function "
#define SCI_ERRMSG112			"Cannot allocate more memory"
#define SCI_ERRMSG113			"too large string"
#define SCI_ERRMSG114			"too many linked routines"
#define SCI_ERRMSG115_1			"Stack problem detected within a loop"
#define SCI_ERRMSG115_2			" a primitive function has been called with wrong number"
#define SCI_ERRMSG115_3			" of lhs arguments. No lhs test made for this function "
#define SCI_ERRMSG115_4			" please report this bug"
#define SCI_ERRMSG116_1			"th argument has incorrect value"
#define SCI_ERRMSG116_2			"first argument has incorrect value"
#define SCI_ERRMSG117_1			"List element"
#define SCI_ERRMSG117_2			" is Undefined"
#define SCI_ERRMSG118_1			"th argument must be a named variable not an expression"
#define SCI_ERRMSG118_2			"argument must be a named variable not an expression "
#define SCI_ERRMSG120			"indices for non-zero elements must be given by a 2 column matrix"
#define SCI_ERRMSG121			"incompatible indices for non-zero elements "
#define SCI_ERRMSG122			" logical unit number should be   larger than "
#define SCI_ERRMSG123			" function not bounded from below"
#define SCI_ERRMSG125			" problem may be unbounded :too high distance between two consecutive iterations"
#define SCI_ERRMSG126			"Inconsistent constraints"
#define SCI_ERRMSG127			"no feasible solution"
#define SCI_ERRMSG128			"degenerate starting point"
#define SCI_ERRMSG129			"no feasible point has been found"
#define SCI_ERRMSG130			"  optimization fails: back to initial point"
#define SCI_ERRMSG131			" optim: stop requested by simulator (ind=0)"
#define SCI_ERRMSG132			" optim: incorrect input parameters"
#define SCI_ERRMSG133			" too small memory"
#define SCI_ERRMSG134			"optim: problem with initial constants in simul "
#define SCI_ERRMSG135			"optim : bounds and initial guess are incompatible"
#define SCI_ERRMSG136			"optim : this method is NOT implemented "
#define SCI_ERRMSG137			"NO hot restart available in this method"
#define SCI_ERRMSG138			"optim : incorrect stopping parameters"
#define SCI_ERRMSG139			"optim : incorrect bounds"
#define SCI_ERRMSG141			" incorrect function (argument n:"
#define SCI_ERRMSG142			"hot restart : dimension of working table (argument n:"
#define SCI_ERRMSG143			"optim : df0 must be positive !"
#define SCI_ERRMSG144_1			"Undefined operation for the given operands"
#define SCI_ERRMSG144_2			"  check or define function "
#define SCI_ERRMSG144_3			" for overloading"

#define SCI_ERRMSG201_1			"Argument "
#define SCI_ERRMSG201_2			" : wrong type argument,"
#define SCI_ERRMSG201_3			" expecting a real or complex matrix"
#define SCI_ERRMSG202_1			"Argument "
#define SCI_ERRMSG202_2			" : wrong type argument,"
#define SCI_ERRMSG202_3			" expecting a real matrix"
#define SCI_ERRMSG203_1 			"Argument "
#define SCI_ERRMSG203_2			" : wrong type argument,"
#define SCI_ERRMSG203_3			" expecting a real vector"
#define SCI_ERRMSG204_1			"Argument "
#define SCI_ERRMSG204_2			", wrong type argument:"
#define SCI_ERRMSG204_3			" expecting a scalar"
#define SCI_ERRMSG205_1			"Argument "
#define SCI_ERRMSG205_2			" : wrong matrix size ("
#define SCI_ERRMSG205_3			") expected "
#define SCI_ERRMSG206_1			"Argument "
#define SCI_ERRMSG206_2			" of "
#define SCI_ERRMSG206_3			" : wrong vector size ("
#define SCI_ERRMSG206_4			") expected "
#define SCI_ERRMSG207_1			"Argument "
#define SCI_ERRMSG207_2			" of "
#define SCI_ERRMSG207_3			" : wrong type argument, expecting a matrix of strings"
#define SCI_ERRMSG208_1			"Argument "
#define SCI_ERRMSG208_2			" : wrong type argument, expecting a booleen matrix"
#define SCI_ERRMSG209_1			"Argument "
#define SCI_ERRMSG209_2			" of "
#define SCI_ERRMSG209_3			" : wrong type argument, expecting a matrix"
#define SCI_ERRMSG210_1			"Argument "
#define SCI_ERRMSG210_2			" of "
#define SCI_ERRMSG210_3			" : wrong type argument, expecting a list"
#define SCI_ERRMSG211_1 		"Argument "
#define SCI_ERRMSG211_2			" of "
#define SCI_ERRMSG211_3			" : wrong type argument, expecting a function"
#define SCI_ERRMSG211_4			" or string (external function)"
#define SCI_ERRMSG212_1			"Argument "
#define SCI_ERRMSG212_2			" of "
#define SCI_ERRMSG212_3			" : wrong type argument, expecting a polynomial matrix"
#define SCI_ERRMSG213_1 		"Argument "
#define SCI_ERRMSG213_2			" : wrong type argument, expecting a working"
#define SCI_ERRMSG213_3			" integer matrix"
#define SCI_ERRMSG214_1			"Argument "
#define SCI_ERRMSG214_2			" of "
#define SCI_ERRMSG214_3			" : wrong type argument,"
#define SCI_ERRMSG214_4			" expecting a  vector"
#define SCI_ERRMSG215_1			"th argument type must be boolean"
#define SCI_ERRMSG215_2			"argument type must be boolean"
#define SCI_ERRMSG216_1			"th argument type must be boolean or scalar"
#define SCI_ERRMSG216_2			"argument type must be boolean or scalar"
#define SCI_ERRMSG217_1			"th argument  must be a sparse matrix of scalars"
#define SCI_ERRMSG217_2			"argument type must be a sparse matrix of scalars"
#define SCI_ERRMSG218_1			"th argument  must be a  handle to sparse lu factors"
#define SCI_ERRMSG218_2			"argument type must be a  handle to sparse lu factors"
#define SCI_ERRMSG219_1			"th argument  must be a sparse or full scalar matrix"
#define SCI_ERRMSG219_2			"argument type must be a sparse or full scalar matrix"
#define SCI_ERRMSG220			"null variable cannot be used here"
#define SCI_ERRMSG221			"A sparse matrix entry is defined with two differents values"
#define SCI_ERRMSG222			"lusolve not yet implemented for full RHS"
#define SCI_ERRMSG223_1			"It is not possible to redefine the "
#define SCI_ERRMSG223_2			" primitive this way (see clearfun)."
#define SCI_ERRMSG224			"Type data base is full"
#define SCI_ERRMSG225			"This data type is already defined"
#define SCI_ERRMSG226			"Inequality comparison with empty matrix"
#define SCI_ERRMSG227			"Missing index"
#define SCI_ERRMSG228			"reference to the cleared global variable "
#define SCI_ERRMSG230			"semidef fails"
#define SCI_ERRMSG231			"First argument must be a single string"
#define SCI_ERRMSG232			"Entry name not found"
#define SCI_ERRMSG233			"Maximum number of dynamic interfaces reached"
#define SCI_ERRMSG234			"link: expecting more than one argument"
#define SCI_ERRMSG235			"link: problem with one of the entry point"
#define SCI_ERRMSG236			"link: the shared archive was not loaded"
#define SCI_ERRMSG237			"link: Only one entry point allowed On this operating system"
#define SCI_ERRMSG238			"link: First argument  cannot be a number"
#define SCI_ERRMSG239			"You cannot link more functions, maxentry reached"
#define SCI_ERRMSG240_1			"File "
#define SCI_ERRMSG240_2			" already exists or "
#define SCI_ERRMSG240_3			"directory write access denied "
#define SCI_ERRMSG241_1			"File "
#define SCI_ERRMSG241_2			" does not exist or "
#define SCI_ERRMSG241_3			"read access denied "
#define SCI_ERRMSG242			"binary direct acces files must be opened by 'file'"
#define SCI_ERRMSG243			"C file logical unit not allowed here"
#define SCI_ERRMSG244			"Fortran file logical unit not allowed here"
#define SCI_ERRMSG245			"No input file associated to logical unit "
#define SCI_ERRMSG246_1			"function not defined for given argument type(s),"
#define SCI_ERRMSG246_2			"  check arguments or define function "
#define SCI_ERRMSG246_3			" for overloading"
#define SCI_ERRMSG248_1			"th argument is not a valid variable name"
#define SCI_ERRMSG248_2			"argument is not a valid variable name"
#define SCI_ERRMSG249_1 		"th argument must not be an empty string"
#define SCI_ERRMSG249_2			"argument must not be an empty string"
#define SCI_ERRMSG250			"Recursive extraction is not valid in this context"
#define SCI_ERRMSG251			"bvode: ipar dimensioned at least 11"
#define SCI_ERRMSG252			"bvode: ltol must be of size ipar(4)"
#define SCI_ERRMSG253			"bvode: fixpnt must be of size ipar(11)"
#define SCI_ERRMSG254			"bvode: ncomp < 20 requested "
#define SCI_ERRMSG255			"bvode: m must be of size ncomp"
#define SCI_ERRMSG256			"bvode: sum(m) must be less than 40"
#define SCI_ERRMSG257			"bvode: sum(m) must be less than 40"
#define SCI_ERRMSG258			"bvode: input data error"
#define SCI_ERRMSG259			"bvode: no. of subintervals exceeds storage"
#define SCI_ERRMSG260			"bvode: Th colocation matrix is singular"
#define SCI_ERRMSG261			"Interface property table is full"
#define SCI_ERRMSG262			"too many global variables!,max number is "
#define SCI_ERRMSG263			"Error while writing in file,(disk full or deleted file)"
#define SCI_ERRMSG264_1			"th argument must not contain NaN or Inf"
#define SCI_ERRMSG264_2 		"argument must not  contain NaN or Inf"
#define SCI_ERRMSG265			"A and B must have equal number of rows"
#define SCI_ERRMSG266			"A and B must have equal number of columns"
#define SCI_ERRMSG267			"A and B must have equal dimensions"
#define SCI_ERRMSG268 			"invalid return value for function passed in argument "
#define SCI_ERRMSG269_1 		"th argument eigenvalues must have negative real parts"
#define SCI_ERRMSG269_2			"argument eigenvalues must have negative real parts"
#define SCI_ERRMSG270_1			"th argument eigenvalues modulus must be less than one"
#define SCI_ERRMSG270_2			"argument eigenvalues modulus must be less than one"
#define SCI_ERRMSG271_1			"Size varying argument a*eye(), (arg "
#define SCI_ERRMSG271_2 		") not allowed here"
#define SCI_ERRMSG271_3			"Size varying argument a*eye() not allowed here"
#define SCI_ERRMSG272			"endfunction is missing"
#define SCI_ERRMSG273			"Instruction left hand side: waiting for a dot or a left parenthesis"
#define SCI_ERRMSG274			"Instruction left hand side: waiting for a name"
#define SCI_ERRMSG275			"varargout keyword cannot be used here"
#define SCI_ERRMSG276			"Missing operator, comma, or semicolon"
#define SCI_ERRMSG277			"Too many commands defined"
 


