"Xscilab*Viewport*allowVert:		True",
"Xscilab*Viewport*allowHoriz:		False",
"Xscilab*Viewport*forceBars:		True",
"Xscilab*Viewport.preferredPaneSize:	160",
"Xscilab*Viewport.vertical.width:	15",
"Xscilab*List*font:		*-fixed-medium-r-*-*-13-*-*-*-*-*-iso8859-*",
"Xscilab*List*verticalList:	True",
"Xscilab*List*height:		150",
"Xscilab*Grip*height:		5",
"Xscilab*Grip*width:		5",
"Xscilab*Label.borderWidth:		0",
"Xscilab*Label.internalWidth:		0",
"Xscilab*Text*Label.internalWidth:	1",
"Xscilab*Label.resize:			True",
"Xscilab*Label.resizable:		True",
"Xscilab*outerPaned.orientation:	vertical",
"Xscilab*buttonForm.skipAdjust: True",
"Xscilab*buttonForm.showGrip: False",
"Xscilab*buttonForm*helpButton.label:		Help",
"Xscilab*buttonForm*helpButton.translations:#override\\n\
	<BtnDown>,<BtnUp>:	help()\\n",
"Xscilab*helpShell.title:		Scilab Help Panel",
"Xscilab*helpShell.translations:#override\\n\
	<Message>WM_PROTOCOLS:	help-done()\\n",
"Xscilab*helpShell.allowShellResize:		False",
"Xscilab*helpForm*Text*borderWidth:	1",
"Xscilab*helpForm.Label*resizable:	True",
"Xscilab*helpForm*helpLabel.borderWidth:	0",
"Xscilab*helpForm*helpViewport.fromVert:	helpLabel",
"Xscilab*helpForm*helpViewport.width:	650",
"Xscilab*helpForm*helpViewport.height:	150",
"Xscilab*helpForm*helpViewport.left:	chainLeft",
"Xscilab*helpForm*helpViewport.right:	chainLeft",
"Xscilab*helpForm*helpViewport1.fromVert:	helpViewport",
"Xscilab*helpForm*helpViewport1.width:	650",
"Xscilab*helpForm*helpViewport1.height:	50",
"Xscilab*helpForm*helpViewport1.left:	chainLeft",
"Xscilab*helpForm*helpViewport1.right:	chainLeft",
"Xscilab*helpForm*helpList*font:			*-fixed-medium-r-*-*-13-*-*-*-*-*-iso8859-*",
"Xscilab*helpForm*helpList*verticalList:		true",
"Xscilab*helpForm*helpList*defaultColumns:	1",
"Xscilab*helpForm*helpList*forceColumns:		true",
"Xscilab*helpForm*helpList*maxSelectable: 	1",
"Xscilab*helpForm*helpList*height:		150",
"Xscilab*helpForm*helpList*width:		600",
"Xscilab*helpForm*helpList1*font:			*-fixed-medium-r-*-*-13-*-*-*-*-*-iso8859-*",
"Xscilab*helpForm*helpList1*verticalList:		true",
"Xscilab*helpForm*helpList1*defaultColumns:	1",
"Xscilab*helpForm*helpList1*forceColumns:		true",
"Xscilab*helpForm*helpList1*maxSelectable: 	1",
"Xscilab*helpForm*helpList1*height:		150",
"Xscilab*helpForm*helpList1*width:		600",
"Xscilab*helpForm*helpDoneButton.label:		Done",
"Xscilab*helpForm*helpDoneButton.fromVert:	helpViewport1",
"Xscilab*helpForm*helpDoneButton.translations:#override\\n\
	<BtnDown>,<BtnUp>:	help-done() \\n",
"Xscilab*helpForm*aproposLabel.label:		Apropos:",
"Xscilab*helpForm*aproposText.width:		410",
"Xscilab*helpForm*aproposText.height:		20",
"Xscilab*helpForm*aproposLabel.fromVert:	helpDoneButton",
"Xscilab*helpForm*aproposText.fromHoriz:	aproposLabel",
"Xscilab*helpForm*aproposText.fromVert:	helpDoneButton",
"Xscilab*helpForm*aproposText*editType: 	edit",
"Xscilab*helpForm*aproposText.translations:#override\\n\
	<Enter>:	display-caret(True) \\n\
	<Leave>:	display-caret(False) \\n\
	<Key>Return:	query-apropos() \\n",
"Xscilab*allowShellResize:		True",
