/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.localization;


 /** 
   * @author Sylvestre LEDRU
   * @copyright DIGITEO 2009
   */
public class MessagesJNI {

  /**
    * Constructor
    */
  protected MessagesJNI() {
	throw new UnsupportedOperationException();
  }

  static {
    try {
        System.loadLibrary("scilocalization");
    } catch (SecurityException e) {
		System.err.println("A security manager exists and does not allow the loading of the specified dynamic library :");
		e.printStackTrace(System.err);
	} catch (UnsatisfiedLinkError e)	{
		System.err.println("The native library scilocalization does not exist or cannot be found.");
		e.printStackTrace(System.err);
    }
  }

  public final static native String gettext(String jarg1);
}
