/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.javasci;


import org.scilab.modules.types.scilabTypes.ScilabTypeEnum;

 /**
   * Connector for Javasci v2
   * @author Sylvestre LEDRU
   * @copyright DIGITEO
   */
public class Call_Scilab {

 /**
   * Constructor
   */
 protected Call_Scilab() {
	throw new UnsupportedOperationException();
 }
  public static boolean StartScilab(String SCIpath, String ScilabStartup, SWIGTYPE_p_int Stacksize) {
    return Call_ScilabJNI.StartScilab(SCIpath, ScilabStartup, SWIGTYPE_p_int.getCPtr(Stacksize));
  }

  public static boolean TerminateScilab(String ScilabQuit) {
    return Call_ScilabJNI.TerminateScilab(ScilabQuit);
  }

  public static int SendScilabJob(String job) {
    return Call_ScilabJNI.SendScilabJob(job);
  }

  public static int SendScilabJobs(String[] jobs, int numberjobs) {
    return Call_ScilabJNI.SendScilabJobs(jobs, numberjobs);
  }

  public static int ScilabHaveAGraph() {
    return Call_ScilabJNI.ScilabHaveAGraph();
  }

  public static int GetLastErrorCode() {
    return Call_ScilabJNI.GetLastErrorCode();
  }

  public static ScilabTypeEnum getVariableType(String varname) {
    return ScilabTypeEnum.swigToEnum(Call_ScilabJNI.getVariableType(varname));
  }

  public static double[][] getDouble(String variableName) {
    return Call_ScilabJNI.getDouble(variableName);
  }

  public static int putDouble(String variableName, double[][] variable) {
    return Call_ScilabJNI.putDouble(variableName, variable);
  }

  public static int putDoubleComplex(String variableName, double[][] variable, double[][] variableImg, int nbRow, int nbCol) {
    return Call_ScilabJNI.putDoubleComplex(variableName, variable, variableImg, nbRow, nbCol);
  }

}
