#!/bin/sh 
# Copyright INRIA
epsfile=`basename $1 .tex`.ps

echo '\\fbox{\\begin{picture}(300.00,212.00)' >$2
echo "\\special{psfile=\\Figdir epsfile hscale=100.00 vscale=100.00}" >>$2
echo "\\end{picture}}"  >>$2
