SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = tkscilib
NAM = SCI/macros/tksci

MACROS = tk_getfile.sci tk_getdir.sci

include ../Make.lib
