SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include ../../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = scssourceslib
NAM = SCI/macros/scicos_blocks/Sources

MACROS= CLKINV_f.sci CONST_f.sci GENSIN_f.sci IN_f.sci READC_f.sci SLIDER_f.sci \
	CLKIN_f.sci CURV_f.sci GENSQR_f.sci RAND_f.sci RFILE_f.sci TIME_f.sci \
	CLOCK_f.sci INIMPL_f.sci READAU_f.sci SAWTOOTH_f.sci \

include ../../Make.lib
