/* Copyright INRIA/ENPC */

#include "../machine.h"

/** only used to force the linker to load all calelm functions **/

#ifndef WIN32

extern void 
	C2F(dgelqf)(), 
	C2F(dgels)(), 
	C2F(dgeqrf)(), 
	C2F(dlae2)(), 
	C2F(dlaev2)(), 
	C2F(dlarf)(), 
	C2F(dlarfg)(), 
	C2F(dlartg)(), 
	C2F(dlascl)(), 
	C2F(dlaset)(), 
	C2F(dlasr)(), 
	C2F(dlasrt)(), 
	C2F(dlassq)(), 
	C2F(dopgtr)(), 
	C2F(dorg2l)(), 
	C2F(dorg2r)(), 
	C2F(dormqr)(), 
	C2F(dpptrf)(), 
	C2F(dspev)(), 
	C2F(dspgst)(), 
	C2F(dspgv)(),  
	C2F(dsptrd)(), 
	C2F(dsptrf)(), 
	C2F(dorgqr)(), 
	C2F(dsteqr)(),  
	C2F(lsame)(), 
	C2F(dtrcon)(), 
	C2F(dgebal)(), 
	C2F(dgebak)(), 
	C2F(ilaenv)(), 
	C2F(dlamch)(), 
	C2F(dlabad)(), 
	C2F(dlange)(), 
	C2F(dormlq)(), 
	C2F(dlansp)(), 
	C2F(dsterf)(), 
	C2F(dgeqr2)(), 
	C2F(dlarft)(), 
	C2F(dlarfb)(), 
	C2F(dorm2r)(), 
	C2F(dgelq2)(), 
	C2F(dlanst)(), 
	C2F(dlapy2)(), 
	C2F(dlantr)(), 
	C2F(dlacon)(), 
	C2F(dlatrs)(), 
	C2F(drscl)(), 
	C2F(dorml2)(), 
	C2F(slamch)(), 
	C2F(dggbal)(), 
	C2F(dggbak)(), 
	C2F(dlacpy)(), 
	C2F(dlaic1)(), 
	C2F(dgeqpf)(), 
	C2F(dlatzm)(), 
	C2F(dtzrqf)(), 
	C2F(dgerqf)(), 
	C2F(dorgrq)(), 
	C2F(dgerq2)(), 
	C2F(dgerfs)(), 
	C2F(dgetrs)(), 
	C2F(dlaswp)(), 
	C2F(dorgr2)(), 
	C2F(dormrq)(), 
	C2F(dormr2)(), 
	C2F(dlapmt)(), 
	C2F(dlansy)(), 
	C2F(dgees)(), 
	C2F(dgehrd)(), 
	C2F(dorghr)(), 
	C2F(dhseqr)(), 
	C2F(dtrsen)(), 
	C2F(dlahrd)(), 
	C2F(dgehd2)(), 
	C2F(dlahqr)(), 
	C2F(dlanhs)(), 
	C2F(dlarfx)(), 
	C2F(dtrexc)(), 
	C2F(dtrsyl)(), 
	C2F(dlanv2)(), 
	C2F(dlaexc)(), 
	C2F(dlaln2)(), 
	C2F(dlasy2)(), 
	C2F(dladiv)(), 
	C2F(dgeesx)(), 
	C2F(dgesvx)(), 
	C2F(dgeequ)(), 
	C2F(dlaqge)(), 
	C2F(dgetrf)(), 
	C2F(dgecon)(), 
	C2F(dgetf2)(), 
	C2F(dsytrf)(), 
	C2F(dlasyf)(), 
	C2F(dsytf2)(), 
	C2F(dsytri)(), 
	C2F(dlasv2)(), 
	C2F(dtrti2)(), 
	C2F(dlapy3)(), 
	C2F(dgelsx)(), 
	C2F(dgetri)(), 
	C2F(dtrtri)(), 
	C2F(dgebrd)(), 
	C2F(dorgbr)(), 
	C2F(dbdsqr)(), 
	C2F(dlabrd)(), 
	C2F(dgebd2)(), 
	C2F(dorglq)(), 
	C2F(dlasq1)(), 
	C2F(dlas2)(), 
	C2F(dorgl2)(), 
	C2F(dlasq2)(), 
	C2F(dlasq3)(), 
	C2F(dlasq4)(), 
	C2F(dormhr)(), 
	C2F(dormql)(), 
	C2F(dgeqlf)(), 
	C2F(dpotrs)(), 
	C2F(dorgql)(), 
	C2F(dorgtr)(), 
	C2F(dsytrd)(), 
	C2F(dsyev)(), 
	C2F(dsytrs)(), 
	C2F(dsycon)(), 
	C2F(dpocon)(), 
	C2F(dpotrf)(), 
	C2F(dgghrd)(), 
	C2F(dhgeqz)(), 
	C2F(dtgevc)(), 
	C2F(dlag2)(), 
	C2F(dgges)(), 
	C2F(dgegs)(), 
	C2F(dgesvd)(), 
	C2F(dormbr)(), 
	C2F(zlacpy)(), 
	C2F(zgeqrf)(), 
	C2F(zgeqpf)(), 
	C2F(zungqr)(), 
	C2F(zgeqr2)(), 
	C2F(zlarft)(), 
	C2F(zlarfb)(), 
	C2F(zlarfg)(), 
	C2F(zung2r)(), 
	C2F(zunm2r)(), 
	C2F(zlarf)(), 
	C2F(zlacgv)(), 
	C2F(zladiv)(), 
	C2F(dgelsy)(), 
	C2F(dgesv)(), 
	C2F(dormrz)(), 
	C2F(dtrtrs)(), 
	C2F(dtzrzf)(),
	C2F(dgeqp3)(), 
	C2F(dlarzb)(),
	C2F(dlarzt)(),
	C2F(dlatrz)(),
	C2F(dormr3)(),
	C2F(dgelss)(),
	C2F(zgeqp3)(),
	C2F(zlaic1)(),
	C2F(zlaqp2)(),
	C2F(zlaqps)(),
	C2F(zunmqr)(),
	C2F(dsysv)(),
	C2F(zgees)(),
	C2F(zgesvd)(),
	C2F(zgetrf)(),
	C2F(zgetri)(),
	C2F(zlange)(),
	C2F(zlascl)(),
	C2F(zlaset)(),
	C2F(zbdsqr)(),
        C2F(zgebak)(), 
	C2F(zgebal)(),
	C2F(zgebrd)(),
	C2F(zgehrd)(),
	C2F(zgelqf)(),
	C2F(zgetf2)(),
	C2F(zhseqr)(),
	C2F(zlassq)(),
	C2F(zlaswp)(),
	C2F(ztrsen)(),
	C2F(ztrtri)(),
	C2F(zungbr)(),
	C2F(zunghr)(),
	C2F(zunglq)(),
	C2F(zunmbr)(),
	C2F(zdrot)(), 
	C2F(zgebd2)(), 
	C2F(zgehd2)(), 
	C2F(zgelq2)(),
	C2F(zlabrd)(), 
	C2F(zlacon)(), 
	C2F(zlahqr)(),	
	C2F(zlahrd)(),
	C2F(zlanhs)(),	
	C2F(zlarfx)(), 
	C2F(zlasr)(),  
	C2F(ztrexc)(), 
	C2F(ztrsyl)(), 
	C2F(ztrti2)(),  
	C2F(zungl2)(), 
	C2F(zunmlq)(),
	C2F(dzsum1)(),
	C2F(izmax1)(),
	C2F(zlartg)(),
	C2F(zrot)(),
	C2F(zunml2)(),
	C2F(zgelsy)(),
	C2F(ztzrzf)(),
	C2F(zunmrz)(),
	C2F(zlarzb)(),
	C2F(zlarzt)(),
	C2F(zlatrz)(),
	C2F(zunmr3)(),
	C2F(zlarz)(),
	C2F(dgeev)(),
	C2F(zgeev)(),
	C2F(dtrevc)(),
	C2F(ztrevc)();
    

void Lapack_contents(int x)
{
  if ( x== 1) 
    {
	C2F(dgelqf)(); 
	C2F(dgels)(); 
	C2F(dgeqrf)(); 
	C2F(dlae2)(); 
	C2F(dlaev2)(); 
	C2F(dlarf)(); 
	C2F(dlarfg)(); 
	C2F(dlartg)(); 
	C2F(dlascl)(); 
	C2F(dlaset)(); 
	C2F(dlasr)(); 
	C2F(dlasrt)(); 
	C2F(dlassq)(); 
	C2F(dopgtr)(); 
	C2F(dorg2l)(); 
	C2F(dorg2r)(); 
	C2F(dormqr)(); 
	C2F(dpptrf)(); 
	C2F(dspev)(); 
	C2F(dspgst)(); 
	C2F(dspgv)();  
	C2F(dsptrd)(); 
	C2F(dsptrf)(); 
	C2F(dorgqr)(); 
	C2F(dsteqr)();  
	C2F(lsame)(); 
	C2F(dtrcon)(); 
	C2F(dgebal)(); 
	C2F(dgebak)(); 
	C2F(ilaenv)(); 
	C2F(dlamch)(); 
	C2F(dlabad)(); 
	C2F(dlange)(); 
	C2F(dormlq)(); 
	C2F(dlansp)(); 
	C2F(dsterf)(); 
	C2F(dgeqr2)(); 
	C2F(dlarft)(); 
	C2F(dlarfb)(); 
	C2F(dorm2r)(); 
	C2F(dgelq2)(); 
	C2F(dlanst)(); 
	C2F(dlapy2)(); 
	C2F(dlantr)(); 
	C2F(dlacon)(); 
	C2F(dlatrs)(); 
	C2F(drscl)(); 
	C2F(dorml2)(); 
	C2F(slamch)(); 
	C2F(dggbal)(); 
	C2F(dggbak)(); 
	C2F(dlacpy)(); 
	C2F(dlaic1)(); 
	C2F(dgeqpf)(); 
	C2F(dlatzm)(); 
	C2F(dtzrqf)(); 
	C2F(dgerqf)(); 
	C2F(dorgrq)(); 
	C2F(dgerq2)(); 
	C2F(dgerfs)(); 
	C2F(dgetrs)(); 
	C2F(dlaswp)(); 
	C2F(dorgr2)(); 
	C2F(dormrq)(); 
	C2F(dormr2)(); 
	C2F(dlapmt)(); 
	C2F(dlansy)(); 
	C2F(dgees)(); 
	C2F(dgehrd)(); 
	C2F(dorghr)(); 
	C2F(dhseqr)(); 
	C2F(dtrsen)(); 
	C2F(dlahrd)(); 
	C2F(dgehd2)(); 
	C2F(dlahqr)(); 
	C2F(dlanhs)(); 
	C2F(dlarfx)(); 
	C2F(dtrexc)(); 
	C2F(dtrsyl)(); 
	C2F(dlanv2)(); 
	C2F(dlaexc)(); 
	C2F(dlaln2)(); 
	C2F(dlasy2)(); 
	C2F(dladiv)(); 
	C2F(dgeesx)(); 
	C2F(dgesvx)(); 
	C2F(dgeequ)(); 
	C2F(dlaqge)(); 
	C2F(dgetrf)(); 
	C2F(dgecon)(); 
	C2F(dgetf2)(); 
	C2F(dsytrf)(); 
	C2F(dlasyf)(); 
	C2F(dsytf2)(); 
	C2F(dsytri)(); 
	C2F(dlasv2)(); 
	C2F(dtrti2)(); 
	C2F(dlapy3)(); 
	C2F(dgelsx)(); 
	C2F(dgetri)(); 
	C2F(dtrtri)(); 
	C2F(dgebrd)(); 
	C2F(dorgbr)(); 
	C2F(dbdsqr)(); 
	C2F(dlabrd)(); 
	C2F(dgebd2)(); 
	C2F(dorglq)(); 
	C2F(dlasq1)(); 
	C2F(dlas2)(); 
	C2F(dorgl2)(); 
	C2F(dlasq2)(); 
	C2F(dlasq3)(); 
	C2F(dlasq4)(); 
	C2F(dormhr)(); 
	C2F(dormql)(); 
	C2F(dgeqlf)(); 
	C2F(dpotrs)(); 
	C2F(dorgql)(); 
	C2F(dorgtr)(); 
	C2F(dsytrd)(); 
	C2F(dsyev)(); 
	C2F(dsytrs)(); 
	C2F(dsycon)(); 
	C2F(dpocon)(); 
	C2F(dpotrf)(); 
	C2F(dgghrd)(); 
	C2F(dhgeqz)(); 
	C2F(dtgevc)(); 
	C2F(dlag2)(); 
	C2F(dgges)(); 
	C2F(dgegs)(); 
	C2F(dgesvd)(); 
	C2F(dormbr)(); 
	C2F(zlacpy)(); 
	C2F(zgeqrf)(); 
	C2F(zgeqpf)(); 
	C2F(zungqr)(); 
	C2F(zgeqr2)(); 
	C2F(zlarft)(); 
	C2F(zlarfb)(); 
	C2F(zlarfg)(); 
	C2F(zung2r)(); 
	C2F(zunm2r)(); 
	C2F(zlarf)(); 
	C2F(zlacgv)(); 
	C2F(zladiv)(); 
	C2F(dgelsy)(); 
	C2F(dgesv)(); 
	C2F(dormrz)(); 
	C2F(dtrtrs)(); 
	C2F(dtzrzf)();
	C2F(dgeqp3)(); 
	C2F(dlarzb)();
	C2F(dlarzt)();
	C2F(dlatrz)();
	C2F(dormr3)();
	C2F(dgelss)();
	C2F(zgeqp3)();
	C2F(zlaic1)();
	C2F(zlaqp2)();
	C2F(zlaqps)();
	C2F(zunmqr)();
	C2F(dsysv)();
	C2F(zgees)();
	C2F(zgesvd)();
	C2F(zgetrf)();
	C2F(zgetri)();
	C2F(zlange)();
	C2F(zlascl)();
	C2F(zlaset)();
	C2F(zbdsqr)();
        C2F(zgebak)(); 
	C2F(zgebal)();
	C2F(zgebrd)();
	C2F(zgehrd)();
	C2F(zgelqf)();
	C2F(zgetf2)();
	C2F(zhseqr)();
	C2F(zlassq)();
	C2F(zlaswp)();
	C2F(ztrsen)();
	C2F(ztrtri)();
	C2F(zungbr)();
	C2F(zunghr)();
	C2F(zunglq)();
	C2F(zunmbr)();
	C2F(zdrot)(); 
	C2F(zgebd2)(); 
	C2F(zgehd2)(); 
	C2F(zgelq2)();
	C2F(zlabrd)(); 
	C2F(zlacon)(); 
	C2F(zlahqr)();	
	C2F(zlahrd)();
	C2F(zlanhs)();	
	C2F(zlarfx)(); 
	C2F(zlasr)();  
	C2F(ztrexc)(); 
	C2F(ztrsyl)(); 
	C2F(ztrti2)();  
	C2F(zungl2)(); 
	C2F(zunmlq)();
	C2F(dzsum1)();
	C2F(izmax1)();
	C2F(zlartg)();
	C2F(zrot)();
	C2F(zunml2)();
	C2F(zgelsy)();
	C2F(ztzrzf)();
	C2F(zunmrz)();
	C2F(zlarzb)();
	C2F(zlarzt)();
	C2F(zlatrz)();
	C2F(zunmr3)();
	C2F(zlarz)();
	C2F(dgeev)();
	C2F(zgeev)();
	C2F(dtrevc)();
	C2F(ztrevc)();
    }
}

#endif
