      LOGICAL FUNCTION  SELECT( PAR1, PAR2 )
C
C     RELEASE 4.0, WGS COPYRIGHT 1999.
C
C     Void logical function for DGEES.
C
      DOUBLE PRECISION  PAR1, PAR2
C
      SELECT = .TRUE.
      RETURN
      END
