function [state]=loadDefaultGraphicState()

// Create a default graphic state. This function is 
// called by fig(). 

global myWorld

if length(myWorld)==0
   graphinit();
end

global myWorld

globalGraphicState=myWorld('globalGraphicState');

state=tlist(['graphicState';
'axisList';
'mainAxis';
'nextPlot';
'viewport';
'ech';
'cbech';
'xlech';
'ylech';
'titech';
'background';
'foreground';
'frameColor';
'subplotState';
'axis';
'axisMode';
'Xscale';
'Yscale';
'colormap';
'RGBcolormap';
'RGBcolormaptable';
'caxisMode';
'caxis';
'listOfPlots';
'margin';
'colorbar'],...
[],...
[],...
'erase',...
globalGraphicState('defaultViewport'),...
[],...
[],...
[],...
[],...
[],...
globalGraphicState.bg,...
globalGraphicState.fg,...
globalGraphicState.fbg,...
'normal',...
[0 0 1 1],...
'normal',...
'linear',...
'linear',...
 globalGraphicState('defaultColormap'),...
 globalGraphicState('defaultRGBcolormap'),...
 [],...
 'auto',...
 [],...
 list(),...
 1/10,...
 'off');

// end of loadDefaultGraphicState

