SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = HighLevelPlottinglib
NAM = SCI/macros/HighLevelPlotting

MACROS = activateRGBColormap.sci  dir.sci             mainPlot3d.sci              parseLight.sci          setFontSize.sci \
addPlot3.sci             doThePlot3d1.sci             mainPlot.sci                parseMargin.sci         shg.sci \
addPlot.sci              doThePlot3d.sci              meshgrid.sci                parseScale.sci          slide.sci \
axis.sci                 draw2DAxis.sci               mesh.sci                    parseShading.sci        subplot.sci \
blackbg.sci              eval3dPolygons.sci           nonParametricDiffData.sci   parseView.sci           surfl.sci \
bluecolormap.sci         fig.sci                      nonParametricDiffDeriv.sci  pcolor.sci              surfnorm.sci \
bonecolormap.sci         fliplr.sci                   nonParametricNormals.sci    plot3.sci               surf.sci \
caxis.sci                flipud.sci                   plotlibver.sci              title.sci \
changeVP.sci             gcw.sci                      parametricDiffData.sci      plot.sci                triangle.sci \
check2dFun.sci           generate3dPolygons.sci       parametricDiffDeriv.sci     process2DAxis.sci       trimesh.sci \
check3dFun.sci           getColorNumber.sci           parametricNormals.sci       process2DPrelim.sci     tripcolor.sci \
checkXYPair.sci          graphinit.sci                parseAxis.sci               process3DPrelim.sci     triplot.sci \
checkXYZQuadruple.sci    greencolormap.sci            parseColorBar.sci           processColorBar.sci     trisurfl.sci \
clearWindow.sci          hold.sci                     parseColormap.sci           processLegendOld.sci    trisurf.sci \
clf.sci                  legend.sci                   parseColor.sci              processLegend.sci       whitebg.sci \
colormap.sci             lighten.sci                  parseFontSize.sci           processSFB.sci          xlabel.sci \
computeLight.sci         loadDefaultColormap.sci      parseGrid.sci               redcolormap.sci         ylabel.sci \
coolcolormap.sci         loadDefaultGraphicState.sci  parseHiddenMode.sci         saveGraphicState.sci \
coppercolormap.sci       loadGlobalGraphicState.sci   parseHideMode.sci           semilogx.sci \
loadGraphicState.sci         parseLabel.sci              semilogy.sci \
diffuse.sci              loglog.sci                   parseLegend.sci             setCurrentViewport.sci \
parseBackFaceLighting.sci

include ../Make.lib
