--------------------Configuration: makefile - Win32 Debug--------------------


Microsoft (R) Program Maintenance Utility   Version 1.62.7022
Copyright (C) Microsoft Corp 1988-1997. All rights reserved.




makefile.exe - 0 error(s), 0 warning(s)
