/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.history_manager;


/* It is generated code. Disable checkstyle */
//CHECKSTYLE:OFF
 /**
   * All Scilab history management used in Java console
   * @author Vincent COUVERT
   * @author Allan CORNET
   * @copyright INRIA
   */
class HistoryManagementJNI {

 /**
   * Constructor
   */
 protected HistoryManagementJNI() {
        throw new UnsupportedOperationException();
 }

  static {
    try {
        System.loadLibrary("scihistory_manager");
    } catch (SecurityException e) {
        System.err.println("A security manager exists and does not allow the loading of the specified dynamic library.");
        System.err.println(e.getLocalizedMessage());
        e.printStackTrace(System.err);
    } catch (UnsatisfiedLinkError e)    {
        System.err.println("The native library scihistory_manager does not exist or cannot be found.");
        System.err.println(e.getLocalizedMessage());
        e.printStackTrace(System.err);
    }
  }

  public final static native boolean appendLineToScilabHistory(String jarg1);
  public final static native boolean appendLinesToScilabHistory(String[] jarg1, int jarg2);
  public final static native void displayScilabHistory();
  public final static native boolean writeScilabHistoryToFile(String jarg1);
  public final static native boolean loadScilabHistoryFromFile(String jarg1);
  public final static native boolean setFilenameScilabHistory(String jarg1);
  public final static native String getFilenameScilabHistory();
  public final static native boolean setDefaultFilenameScilabHistory();
  public final static native void resetScilabHistory();
  public final static native String[] getAllLinesOfScilabHistory();
  public final static native int getSizeAllLinesOfScilabHistory();
  public final static native boolean setSearchedTokenInScilabHistory(String jarg1);
  public final static native boolean resetSearchedTokenInScilabHistory();
  public final static native String getSearchedTokenInScilabHistory();
  public final static native String getPreviousLineInScilabHistory();
  public final static native String getNextLineInScilabHistory();
  public final static native int getNumberOfLinesInScilabHistory();
  public final static native void setSaveConsecutiveDuplicateLinesInScilabHistory(boolean jarg1);
  public final static native boolean getSaveConsecutiveDuplicateLinesInScilabHistory();
  public final static native void setAfterHowManyLinesScilabHistoryIsSaved(int jarg1);
  public final static native int getAfterHowManyLinesScilabHistoryIsSaved();
  public final static native String getNthLineInScilabHistory(int jarg1);
  public final static native boolean deleteNthLineScilabHistory(int jarg1);
  public final static native int getSizeScilabHistory();
  public final static native boolean historyIsEnabled();
  public final static native boolean setSizeMaxScilabHistory(int jarg1);
  public final static native boolean InitializeHistoryManager();
  public final static native boolean TerminateHistoryManager();
}
