.TH macroname 2 "April 1993" "Scilab Group" "Scilab Function"
.so sci.an
.SH NAME
macroname - keywords for whatis
.SH CALLING SEQUENCE
.nf
[out1,out2] = macroname(input1,input2, [optional])
.fi
.SH PARAMETERS
.TP 10
input1
: real matrix, meaning.
.TP 10 
input2
: character string, meaning.
.TP
out1
: polynomial matrix
.SH DESCRIPTION
This is an example of a documentation item.
Here, what the macro is doing. \fVX\fR (will appear in verb mode in Latex) 
is something ... \fVout1\fR is something else
and the result is again something else. If \fVinput1\fR is a list then 
something else is made and blablabla.
\"LaTeX \ignore{
.nf
          --n
          \\
       x= |  alpha(k)**2
          /  
          --k=0 
.fi
\"LaTeX }
.IG
.nf
          --n
          \\
       x= |  alpha(k)**2
          /  
          --k=0 
.fi
.FI
\"LaTeX \[ x=\sum_{k=0}^n \alpha_k^2 \]
.LA \[ x=\sum_{k=0}^n \alpha_k^2 \]
.PP 
.ul 1
underline text
.PP
.B bold text
.PP
.I italic text
.PP
.PP
.Vb verb in Latex x\y*%pi
.PP
Here a new paragraph which is indented in latex. 
This paragraph contains various  comments.
.LP 
Here a new paragraph which is not indented in latex.
.SH USING TP AND IP
IP and TP are used to produce description or itemize or enumerate in
\"LaTeX \LaTeX.
The  tag for TP is translated in verb mode. One can mix sequences 
of TP or IP and indented levels are obtained with .RS 
in verb mode.
.TP 20
verb-tag
: the item description in TP
.TP
verb-tag
: the item description in TP
.RS
.IP 1
an IP-list inserted in TP and surrounded with RS,RE.
.IP 2
second IP-item description. IP is used to produce enumerate itemize or 
description
.RE
.TP
verb-tag
: the item description in TP
.LP
.IP Roman 
: the item description of an IP-list 
.IP \fIItalic
: the item description of an IP-list 
.IP \fBBod
: the item description of an IP-list 
.IP \fVVerb 
: the item description of an IP-list 
.LP
.SH REMARK
Note that ...
.SH SEE ALSO
name1,name2,nam_e3
.SH AUTHOR
your name
