fd=mopen('Makefile','wt');
mputl('SOURCES=*.java',fd);
mputl(' ',fd);
mputl('SCIDIR='+SCI,fd);
mputl(' ',fd);
mputl('JAVAC=javac -deprecation -d $(SCIDIR)/bin -classpath $(SCIDIR)/bin -g ',fd);
mputl(' ',fd);
mputl(' ',fd);
mputl('all:',fd);
mputl(ascii(9)+'$(JAVAC) $(SOURCES)',fd);
mputl(' ',fd);
mputl('clean:',fd);
mputl(ascii(9)+'$(RM) -f $(SCIDIR)/bin/*.class',fd);
mputl(' ',fd);	
mputl(' ',fd);
mclose(fd);
