// =============================================================================
// Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
// Copyright (C) 2022 - ESI Group - Antoine ELIAS
//
//  This file is distributed under the same license as the Scilab package.
// =============================================================================

// <-- CLI SHELL MODE -->
// <-- NO CHECK REF -->

tests = list(...
    1, ...
    "ABC", ...
    "\", ...
    "\t", ...
    %f, ...
    %t, ...
    [1 2 3], ...
    [1 2 3;4 5 6], ...
    [%t %f %t], ...
    [%t %f %t;%f %t %f], ...
    ["\\" """" "\t"], ...
    ["\\" """" "\t";"\\" """" "\t"], ...
    ["1" "2" "3"], ...
    ["1" "2" "3";"4" "5" "6"], ...
    struct("A", [1 2 3], "B", ["toto", "titi", "tata"], "C", [%t %f %t]), ...
    list([1 2 3], ["A" "B" "C"], [%t %f %t]))

for t = tests
    assert_checkequal(fromJSON(toJSON(t)), t);
end
