/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.commons;


 /**
   * Some commons values from Scilab engine to Java
   * @author Sylvestre LEDRU
   * @copyright DIGITEO 2010
   */
public class ScilabCommons {

 /**
   * Constructor
   */
 protected ScilabCommons() {
    throw new UnsupportedOperationException();
 }
  
 /**
   * Get SCIHOME variable from Scilab
   * @return SCIHOME value
   */
public static String getSCIHOME() {
    return ScilabCommonsJNI.getSCIHOME();
  }

  public static String getTMPDIR() {
    return ScilabCommonsJNI.getTMPDIR();
  }

  public static String getlanguage() {
    return ScilabCommonsJNI.getlanguage();
  }

  public static String createtempfilename(String prefix, int bShortFormat) {
    return ScilabCommonsJNI.createtempfilename(prefix, bShortFormat);
  }

}
