SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include ../../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = m2ssci_fileslib
NAM = SCI/macros/m2sci/sci_files

PROTO0 = sci_abs.sci sci_cos.sci sci_cosh.sci sci_erf.sci sci_erfc.sci \
	 sci_erfcx.sci sci_gamma.sci sci_gammaln.sci sci_imag.sci sci_real.sci
PROTO1 = sci_max.sci sci_min.sci 
PROTO2 = sci_cumprod.sci sci_cumsum.sci
PROTO3 = sci_eye.sci sci_false.sci sci_ones.sci sci_rand.sci sci_randn.sci sci_true.sci sci_zeros.sci
PROTO4 = sci_acosh.sci sci_asinh.sci sci_atan.sci sci_conj.sci sci_cot.sci sci_coth.sci \
	 sci_double.sci sci_exp.sci sci_expm.sci sci_inv.sci sci_log.sci sci_log10.sci\
	 sci_sign.sci sci_sin.sci sci_sinh.sci sci_sqrt.sci sci_tan.sci sci_tanh.sci
PROTO5 = sci_asin.sci sci_atanh.sci
PROTO6 = sci_ceil.sci sci_fix.sci sci_floor.sci sci_round.sci
PROTO7 = sci_tril.sci sci_triu.sci
PROTO8 = sci_prod.sci sci_sum.sci
PROTO9 = sci_int8.sci sci_int16.sci sci_int32.sci sci_uint8.sci sci_uint16.sci sci_uint32.sci
PROTO10 = sci_lower.sci sci_upper.sci
PROTO11 = sci_dos.sci sci_unix.sci 
PROTO12 = sci_who.sci sci_whos.sci
PROTO13 = sci_all.sci sci_any.sci
PROTO14 = sci_acos.sci
PROTO15 = sci_nargin.sci sci_nargout.sci

OTHERS = sci_acot.sci sci_acoth.sci sci_acsc.sci sci_acsch.sci sci_angle.sci \
	 sci_asec.sci sci_asech.sci \
	 sci_atan2.sci sci_balance.sci sci_beep.sci \
	 sci_beta.sci sci_blanks.sci sci_break.sci sci_besseli.sci sci_besselj.sci sci_besselk.sci  sci_bessely.sci \
	 sci_cd.sci \
	 sci_cell.sci sci_char.sci sci_cell2mat.sci sci_cellstr.sci\
	 sci_chol.sci sci_clc.sci sci_clear.sci sci_clock.sci sci_continue.sci \
	 sci_conv.sci \
         sci_cputime.sci sci_csc.sci sci_csch.sci sci_date.sci sci_dec2hex.sci \
	 sci_delete.sci sci_det.sci sci_diag.sci sci_diary.sci \
	 sci_diff.sci sci_dir.sci sci_display.sci sci_disp.sci sci_doc.sci \
	 sci_docopt.sci sci_drawnow.sci sci_etime.sci \
         sci_eig.sci sci_error.sci sci_eval.sci sci_exist.sci sci_exit.sci \
	 sci_fclose.sci sci_feof.sci sci_ferror.sci sci_feval.sci sci_fft.sci \
         sci_fftshift.sci sci_fgetl.sci sci_fgets.sci sci_fileparts.sci sci_filesep.sci \
	 sci_find.sci sci_findstr.sci sci_fliplr.sci sci_flipud.sci \
	 sci_fopen.sci sci_format.sci \
	 sci_fprintf.sci sci_fread.sci sci_frewind.sci sci_fscanf.sci \
         sci_fseek.sci sci_ftell.sci sci_full.sci sci_fullfile.sci \
	 sci_fwrite.sci sci_getenv.sci \
	 sci_global.sci sci_hankel.sci sci_help.sci sci_helpbrowser.sci sci_helpdesk.sci\
	 sci_helpwin.sci sci_hess.sci sci_horzcat.sci sci_ifft.sci sci_input.sci sci_interp1.sci \
         sci_isa.sci sci_iscell.sci sci_ischar.sci sci_isdir.sci \
	 sci_isempty.sci sci_isequal.sci sci_isfield.sci sci_isfinite.sci sci_isglobal.sci \
	 sci_ishandle.sci sci_isinf.sci sci_isinteger.sci \
	 sci_isletter.sci sci_islogical.sci sci_isnan.sci sci_isnumeric.sci sci_ispc.sci\
         sci_isreal.sci sci_isscalar.sci \
	 sci_isspace.sci sci_issparse.sci sci_isstr.sci sci_isstruct.sci sci_isunix.sci \
	 sci_isvector.sci sci_keyboard.sci sci_kron.sci \
	 sci_length.sci sci_linspace.sci sci_load.sci sci_log2.sci \
         sci_logical.sci sci_lookfor.sci sci_lu.sci sci_makecell.sci sci_mkdir.sci \
	 sci_mod.sci \
	 sci_more.sci \
         sci_ndims.sci sci_norm.sci sci_num2str.sci \
	 sci_pause.sci sci_pow2.sci sci_qr.sci \
	 sci_quit.sci sci_rcond.sci sci_rem.sci sci_repmat.sci sci_realmax.sci sci_realmin.sci \
         sci_reshape.sci sci_return.sci sci_save.sci sci_schur.sci sci_setstr.sci \
	 sci_size.sci sci_sort.sci sci_sparse.sci \
         sci_strcmpi.sci sci_strcmp.sci sci_strfind.sci sci_strrep.sci sci_struct.sci \
	 sci_svd.sci sci_tic.sci sci_toc.sci sci_toeplitz.sci \
         sci_home.sci sci_type.sci sci_uigetdir.sci sci_vertcat.sci \
	 sci_waitforbuttonpress.sci sci_warning.sci sci_winqueryreg.sci

PLOT =  sci_axis.sci sci_box.sci sci_cla.sci sci_clf.sci sci_close.sci \
	sci_closereq.sci sci_colordef.sci \
	sci_graymon.sci sci_grid.sci sci_hold.sci \
	sci_ishold.sci sci_plot.sci 

MACROS = $(PROTO0) $(PROTO1) $(PROTO2) $(PROTO3) $(PROTO4) \
         $(PROTO5) $(PROTO6) $(PROTO7) $(PROTO8) $(PROTO9) \
         $(PROTO10) $(PROTO11) $(PROTO12) $(PROTO13) $(PROTO14) \
	 $(PROTO15) $(OTHERS) $(PLOT)




include ../../Make.lib
