/* Allan CORNET INRIA 2005 */
#ifndef TCL_ERRORSH
#define TCL_ERRORSH

#define TCL_ERROR1 "Tcl Error  : Tcl_CreateInterp\r\n"
#define TCL_ERROR2 "Tcl Error  : Tcl_Init\r\n"
#define TCL_ERROR3 "Tcl Error  : Tk_Init\r\n"
#define TCL_ERROR4 "Tcl Error %s\r\n"
#define TCL_ERROR5 "parameter must be >= 0\n"
#define TCL_ERROR6 "Invalid parameter type : must be a integer\n"
#define TCL_ERROR7 "Invalid parameter type : must be a integer\n"
#define TCL_ERROR8 "Invalid parameter(s) type.\n"
#define TCL_ERROR9 "argument type incorrect: Must be a string"
#define TCL_ERROR10 "%s, ScilabTclEval error at line %i \r\n"
#define TCL_ERROR11 "%s, %s at line %i \r\n"
#define TCL_ERROR12 "argument type incorrect: Must be a string or vector of strings"
#define TCL_ERROR13 "TCL_ExistVar : Error TCLinterp not Initialize\r\n"
#define TCL_ERROR14 "TCL_ExistVar : Argument type must be character string \r\n"
#define TCL_ERROR15 "Tcl Error : GetTclCurrentFigure.\r\n"
#define TCL_ERROR16 "Tcl Error : SetTclCurrentFigure.\r\n"
#define TCL_ERROR17 "TCL_GetVar : Error TCLinterp not Initialize\r\n"
#define TCL_ERROR18 "TCL_GetVar : Could not read Tcl Var \r\n"
#define TCL_ERROR19 "TCL_GetVar : Argument type must be character string \r\n"
#define TCL_ERROR20 "You have started Scilab in a mode in which TCL/TK not initialized.\n"
#define TCL_ERROR21 "Handle must be an integer.\n"
#define TCL_ERROR22 "Field parameter must be a string.\n"
#define TCL_ERROR23 "TCL_SetVar : Error TCLinterp not Initialize\r\n"
#define TCL_ERROR24 "TCL_SetVar : Invalid Argument type.\r\n"
#define TCL_ERROR25 "TCL_UnsetVar : Error TCLinterp not Initialize\r\n"
#define TCL_ERROR26 "TCL_UnsetVar : Argument type must be character string \r\n"
#define TCL_ERROR27 "TCL_UpVar : Invalid Argument type.\r\n"
#define TCL_ERROR28 "TCL_EvalScilabCmd: No more memory\r\n"
#define TCL_ERROR29 "ScilabTCLEval: at least one argument is required\r\n"
#define TCL_ERROR30 "Unknown property %s\r\n"
#define TCL_ERROR31 "Error property not found.\n"
#define TCL_ERROR32 "Tcl Command > %d characters \r\n"
#define TCL_ERROR33 "Invalid parameter(s) type (Style).\n"
#define TCL_ERROR34 "Invalid Handle. it must be > 0.\n"
#endif  /* TCL_ERRORSH */