SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include ../../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = scselectricallib
NAM = SCI/macros/scicos_blocks/Electrical

MACROS= Capacitor.sci Ground.sci NPN.sci VVsourceAC.sci \
	ConstantVoltage.sci Inductor.sci PotentialSensor.sci VariableResistor.sci \
	CurrentSensor.sci MOTOR.sci Resistor.sci VoltageSensor.sci \
	Diode.sci SineVoltage.sci VsourceAC.sci \


include ../../Make.lib
