.TH abort 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
abort - interupt evaluation.
.SH DESCRIPTION
\fVabort\fR interrupt current evaluation and gives the prompt. Within
a \fVpause\fR level  \fVabort\fR return to level 0 prompt.
.SH SEE ALSO
quit, pause, break, abort, quit


