.TH macroname 2 "April 1993" "Scilab Group" "Scilab Function"
.so sci.an
.SH NAME
macroname - keywords for whatis
.SH CALLING SEQUENCE
.nf
[out1,out2] = macroname(input1,input2, [optional])
.fi
.SH PARAMETERS
.TP 10
input1
: real matrix, meaning.
.TP 10 
input2
: character string, meaning.
.TP
out1
: polynomial matrix
.SH DESCRIPTION
\"LaTeX \ignore{
.nf
	Verbatim enclosed in ignore 
.fi
\"LaTeX }
.IG
.nf
	Verbatim ignored in LaTeX (IG/FI) 
.fi
.FI
.nf 
Real One Verbatim 
.fi 
.SH REMARK
Note that ...
.SH SEE ALSO
name1,name2,nam_e3
.SH AUTHOR
your name
