SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = utillib
NAM = SCI/macros/util

MACROS = sysconv.sci  lin.sci halt.sci bloc2exp.sci \
	pol2tex.sci texprint.sci bloc2ss.sci \
	cmb_lin.sci  solve.sci trianfml.sci trisolve.sci \
	sci2map.sci \
	logspace.sci linspace.sci ssprint.sci ssrand.sci \
	sysdiag.sci syslin.sci syssize.sci trfmod.sci manedit.sci \
	typeof.sci ndims.sci isdef.sci edit.sci \
	whereami.sci projaff.sci derivative.sci \
	unix_g.sci unix_s.sci unix_x.sci unix_w.sci \
	x_choices.sci x_matrix.sci getvalue.sci getclick.sci \
	odeoptions.sci whos.sci who_user.sci \
	excel2sci.sci sci2excel.sci\
	dec2hex.sci hex2dec.sci oct2dec.sci base2dec.sci\
	getd.sci genlib.sci macrovar.sci \
	G_make.sci hypermat.sci menubar.sci \
	mfile2sci.sci translatepaths.sci \
	adj2sp.sci sp2adj.sci mps2linpro.sci date.sci\
	initial_scicos_tables.sci initial_help_chapters.sci \
	initial_demos_tables.sci formatman.sci maxindex.sci  \
	ilib_gen_gateway.sci ilib_gen_loader.sci get_file_path.sci \
	ilib_gen_Make.sci ilib_compile.sci ilib_build.sci \
	get_absolute_file_path.sci get_function_path.sci \
	ilib_for_link.sci ilib_unix_soname.sci scitest.sci \
	tokenpos.sci tokens.sci justify.sci stripblanks.sci eval.sci evstr.sci \
	fun2string.sci sci2exp.sci ascii2string.sci createfun.sci \
	isdir.sci newest.sci mputl.sci dispfiles.sci input.sci readc_.sci\
	printf.sci fprintf.sci sprintf.sci scanf.sci fscanf.sci sscanf.sci \
	profile.sci get_profile.sci showprofile.sci plotprofile.sci \
	ilib_mex_build.sci listfiles.sci pathconvert.sci basename.sci \
	dirname.sci \
	apropos.sci help.sci find_links.sci editor.sci \
	xmltohtml.sci\
	loadmatfile.sci matfile2sci.sci ReadmiMatrix.sci toolboxes.sci\
	with_tk.sci with_gtk.sci with_pvm.sci with_texmacs.sci scipad.sci

include ../Make.lib
