SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = utillib
NAM = SCI/macros/util

MACROS = sysconv.sci readc_.sci lin.sci halt.sci bloc2exp.sci \
	pol2tex.sci texprint.sci bloc2ss.sci \
	cmb_lin.sci eval.sci evstr.sci solve.sci \
	trianfml.sci trisolve.sci sci2map.sci \
	logspace.sci linspace.sci ssprint.sci ssrand.sci \
	sysdiag.sci syslin.sci syssize.sci trfmod.sci manedit.sci \
	x_matrix.sci typeof.sci isdef.sci edit.sci \
	getvalue.sci  macrovar.sci input.sci sci2exp.sci \
	whereami.sci projaff.sci derivative.sci \
	printf.sci fprintf.sci sprintf.sci scanf.sci fscanf.sci sscanf.sci \
	unix_g.sci unix_s.sci unix_x.sci unix_w.sci \
	x_choices.sci odeoptions.sci whos.sci who_user.sci newest.sci\
	excel2sci.sci dec2hex.sci hex2dec.sci getd.sci genlib.sci\
	G_make.sci hypermat.sci menubar.sci \
	getclick.sci stripblanks.sci define.sci\
	mfile2sci.sci translatepaths.sci \
	adj2sp.sci sp2adj.sci mps2linpro.sci date.sci\
	initial_scicos_tables.sci initial_help_chapters.sci \
	initial_demos_tables.sci formatman.sci\
	ilib_gen_gateway.sci ilib_gen_loader.sci get_file_path.sci \
	ilib_gen_Make.sci ilib_compile.sci ilib_build.sci \
	get_absolute_file_path.sci get_function_path.sci\
	mputl.sci dispfiles.sci fun2string.sci \
	profile.sci get_profile.sci showprofile.sci plotprofile.sci \
	ilib_for_link.sci ilib_unix_soname.sci scitest.sci sci2excel.sci\
	maxindex.sci justify.sci ndims.sci oct2dec.sci base2dec.sci

include ../Make.lib
