SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = s2flib
NAM = SCI/macros/sci2for

MACROS = sci2for.sci adderr.sci basparam.sci cla2for.sci cod2for.sci \
	exp2for.sci f_argn.sci f_cos.sci f_ent.sci f_error.sci f_eye.sci \
	f_maxi.sci f_mini.sci f_norm.sci f_sin.sci f_size.sci forparam.sci \
	freewrk.sci getwrk.sci indent.sci indentfor.sci ins2for.sci \
	isnum.sci lin2for.sci makeargs.sci mltopsfor.sci \
	modlst.sci  op2for.sci outname.sci setparam.sci f_abs.sci newlab.sci\
	f_exp.sci f_gener.sci f_tan.sci typconv.sci warning.sci \
	get2f.sci num2f.sci func2f.sci str2f.sci getlocal.sci gencall.sci \
	genif.sci f_cond.sci f_rank.sci f_svd.sci dclfun.sci callfun.sci \
	f_log.sci f_ones.sci f_sqrt.sci f_type.sci f_max.sci f_min.sci \
	%a2for.sci %cc2for.sci %i2for.sci %log2for.sci %r2for.sci %s2for.sci \
	%c2for.sci %e2for.sci %imp2for.sci %m2for.sci %rc2for.sci %t2for.sci\
	%h2for.sci %p2for.sci\
	f_expm.sci f_zeros.sci
include ../Make.lib
