SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = metalib
NAM = SCI/macros/metanet

MACROS = adj_lists.sci add_edge.sci add_node.sci arc_graph.sci \
	arc_number.sci articul.sci bandwr.sci \
	best_match.sci chain_struct.sci \
	check_graph.sci circuit.sci con_nodes.sci connex.sci \
	contract_edge.sci convex_hull.sci \
	cycle_basis.sci delete_arcs.sci delete_nodes.sci \
	edge_number.sci find_path.sci gen_net.sci girth.sci graph_2_mat.sci \
	graph_center.sci graph_complement.sci \
	graph_diameter.sci \
	graph_power.sci graph_simp.sci \
	graph_sum.sci graph_union.sci hamilton.sci knapsack.sci \
	nodes_degrees.sci \
	is_connex.sci line_graph.sci load_graph.sci make_graph.sci \
	mat_2_graph.sci max_cap_path.sci max_clique.sci max_flow.sci \
	mesh2d.sci metanet.sci metanet_sync.sci min_lcost_cflow.sci \
	min_lcost_flow1.sci min_lcost_flow2.sci min_qcost_flow.sci \
	min_weight_tree.sci neighbors.sci node_number.sci \
	nodes_2_path.sci \
	path_2_nodes.sci perfect_match.sci pipe_network.sci plot_graph.sci \
	predecessors.sci qassign.sci \
	salesman.sci save_graph.sci shortest_path.sci \
	show_arcs.sci show_graph.sci show_nodes.sci split_edge.sci \
	strong_con_nodes.sci strong_connex.sci subgraph.sci \
	successors.sci \
	supernode.sci trans_closure.sci

include ../Make.lib
