SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

LIBRARY = $(SCIDIR)/libs/slicot.a

OBJSC =

OBJSF = ib01py.o mb01sd.o mb03od.o sb02ms.o sb02rd.o ib01bd.o \
	ma02ad.o mb02pd.o mb04kd.o sb02mt.o sb02ru.o \
	ib01pd.o ma02ed.o mb02qy.o sb02nd.o sb02sd.o \
	ib01px.o mb01ru.o mb02ud.o sb02mr.o sb02qd.o \
	mb01rx.o mb01ry.o mb01ud.o mb01vd.o mb03ud.o \
	mb04od.o mb04oy.o sb03mx.o sb03my.o sb03qx.o \
	sb03qy.o sb03sx.o sb03sy.o sb03mv.o sb03mw.o \
	sb04px.o select.o \
	ib01ad.o ib01cd.o \
	ib01nd.o ib01od.o ib01qd.o ib01rd.o tb01wd.o \
	ib01md.o ib01oy.o mb01td.o mb04id.o mb04iy.o \
	ib01my.o ma02fd.o \
	ab01od.o ab01nd.o mb01pd.o mb03oy.o mb01qd.o \
	ab13md.o sb10fd.o sb10dd.o sb10pd.o sb10qd.o \
	sb10rd.o sb02od.o sb02oy.o sb02ov.o sb02ou.o \
	\
	sb04pd.o sb04md.o sb04qd.o sb04py.o sb04nd.o \
	sb04rd.o sb03md.o sb03od.o sb03ov.o\
	mb01rd.o sb03ou.o sb04mu.o sb04my.o sb04nv.o \
	sb04nw.o sb04nx.o sb04ny.o sb04qu.o sb04qy.o \
	sb04rv.o sb04rw.o sb04rx.o sb04ry.o \
	sb03ot.o sb04mr.o sb04mw.o sb04qr.o \
	sb03oy.o sb03or.o mb04nd.o mb04ny.o

include ../../Makefile.incl

CFLAGS = $(CC_OPTIONS)

FFLAGS = $(FC_OPTIONS)

include ../Make.lib

