/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.renderer.jni;


 /** 
  * Call from the JoGL dislay thread to figure drawing code using JNI 
  * @author Jean-Baptiste Silvy
  * @copyright INRIA 2007 
  */
public class FigureScilabCall {

 /**
  * Constructor. Should not be called.
  */
 protected FigureScilabCall() {
	throw new UnsupportedOperationException();
 }
  
 /**
  * Draw a figure inside the OpenGL context
  * @param figureId index of the figure to redraw
  */
public static void displayFigure(int figureId) {
    FigureScilabCallJNI.displayFigure(figureId);
  }

  
 /**
  * Redraw a figure and its all children inside the OpenGL context
  * @param figureId index of the figure to redraw
  */
public static void redrawFigure(int figureId) {
    FigureScilabCallJNI.redrawFigure(figureId);
  }

  
 /**
  * Redraw all the subwindows inside a figure.
  * This should be called when the figure is resized.
  * @param figureId index of the figure to redraw
  */
public static void redrawSubwins(int figureId) {
    FigureScilabCallJNI.redrawSubwins(figureId);
  }

}
