                Changes between version 5.2.X and 5.3.0 of Scilab
               =================================================


Core:
=====

* Faster access to primitive table (internal). This change improves the overall
speed of Scilab.

Xcos:
=====

* The default palettes can now be manipulated by the user.
          
Bug fixes:
==========

* bug 6419 fixed - gstacksize() There was no way to retrieve minimum from scilab.
