                     Changes between version 5.5.1 and 5.6.0
                     =======================================

New Features
=============

* scatter plot with different mark colors is now available:
  TODO : save/load+display+doc of new properties

* name2rgb can now handle a single string and a matrix of strings.


Compilation
============

* --without-xcos now only disable Xcos compilation. Xcos Graphic interface is disabled
using --without-gui.
