/* Allan CORNET */
/* INRIA 2005 */
#ifndef _ERRORSH_
#define _ERRORSH_

#define MSG_ERROR1 "Floating Exception"
#define MSG_ERROR2 "IOT Trap"
#define MSG_ERROR3 "Quit signal"
#define MSG_ERROR4 "Interrupt"
#define MSG_ERROR5 "Killed"
#define MSG_ERROR6 "Trace trap"
#define MSG_ERROR7 "unknown first parameter.\r\n"
#define MSG_ERROR8 "type of second parameter incorrect.\r\n"
#define MSG_ERROR9 "unknown first parameter.\r\n"
#define MSG_ERROR10 "Only on Windows mode.\r\n"
#define MSG_ERROR11 "system() failed"
#define MSG_ERROR12 "Cannot remove directory %s\r\n"
#define MSG_ERROR13 "Error DDE.\r\n"
#define MSG_ERROR14 "parameter(s) type incorrect.\r\n"
#define MSG_ERROR15 "2 parameters required.\r\n"
#define MSG_ERROR16 "Error.\r\n"
#define MSG_ERROR17 "Cannot query value of this type.\r\n"
#define MSG_ERROR18 "Two arguments required\r\n"
#define MSG_ERROR19 "Incorrect SCI path. Please verify your SCI environment variable.\n"
#define MSG_ERROR20 "ERROR"
#define MSG_ERROR21 "Incorrect HOME path. Please verify your HOME environment variable.\n"
#define MSG_ERROR22 "Incorrect TCL_LIBRARY environment variable"
#define MSG_ERROR23 "Incorrect TK_LIBRARY environment variable"
#define MSG_ERROR24 "No PATH environment ..."
#define MSG_ERROR25 "Stdout pipe creation failed\n"
#define MSG_ERROR26 "Redirecting STDOUT failed\r\n"
#define MSG_ERROR27 "Stdin pipe creation failed\r\n"
#define MSG_ERROR28 "Redirecting Stdin failed\r\n"
#define MSG_ERROR29 "DuplicateHandle failed\r\n"
#define MSG_ERROR30 "Create process failed\r\n"
#define MSG_ERROR31 "Re-redirecting Stdin failed\r\n"
#define MSG_ERROR32 "Re-redirecting Stdout failed\r\n"
#define MSG_ERROR33 "Incorrect DLL version\nExpected version   %s\nThis is version   %s"
#define MSG_ERROR34 "Can't print : Error in SetWindowLong"
#define MSG_ERROR35 "xsnative: input argument incorrect\r\n"
#define MSG_ERROR36 "Error : GetDC fails"
#define MSG_ERROR37 "Error : GetDC Input don't handle NULL"
#define MSG_ERROR38 "GetScilabDirectory()"
#define MSG_ERROR39 "Do not find LibScilab.dll"
#define MSG_ERROR40 "out of memory"
#define MSG_ERROR41 "Scilab doesn''t support Windows NT 3.51 or 4.\n"
#define MSG_ERROR42 "Scilab supports only 256 colors or more.\n"
#define MSG_ERROR43 "Menu is too deep at line %d of %s\n"
#define MSG_ERROR44 "Too many buttons at line %d of %s\n"
#define MSG_ERROR45 "Problem on line %d of %s\n"
#define MSG_ERROR46 "Out of space for menu macros at line %d of %s\n"
#define MSG_ERROR47 "Error in .mnu file: %s"
#define MSG_ERROR48 "Error in .mnu file"
#define MSG_ERROR49 "Environment variable SCI must be defined\r\n"
#define MSG_ERROR50 " Can't open file %s\r\n"
#define MSG_ERROR51 "input file doesn't need to be changed to epsf \r\n"
#define MSG_ERROR52 "file %s not found \r\n"
#define MSG_ERROR53 "Parentwndclass Win32 error %ld occured"
#define MSG_ERROR54 "Couldn't open parent text window"
#define MSG_ERROR55 "Couldn't open text window"
#define MSG_ERROR56 "panic"
#define MSG_ERROR57 "\nCannot create file. It does not appear to be a valid name\n"
#define MSG_ERROR58 "Error %d invalid number\n"

#define MSG_ERROR59 "SIGINT Signal detected"
#define MSG_ERROR60 "SIGILL Signal detected"
#define MSG_ERROR61 "SIGFPE Signal detected"
#define MSG_ERROR62 "SIGSEGV Signal detected"
#define MSG_ERROR63 "SIGTERM Signal detected"
#define MSG_ERROR64 "SIGBREAK Signal detected"
#define MSG_ERROR65 "SIGABRT Signal detected"
#define MSG_ERROR66 "Unknow Signal detected"
#define MSG_ERROR67 "SIGSTP: aborting current computation\r\n"
#define MSG_ERROR68 "Input line too long"
#define MSG_ERROR69 "unable to spawn shell"
#define MSG_ERROR70 "EnumPrinters() failed, error code = %d"
#define MSG_ERROR71 "OpenPrinter() failed for \042%s\042, error code = %d"
#define MSG_ERROR72 "StartDocPrinter() failed, error code = %d"
#define MSG_ERROR73 "EndDocPrinter() failed, error code = %d"
#define MSG_ERROR74 "ClosePrinter() failed, error code = %d"
#define MSG_ERROR75 "out of memory for %s"
#define MSG_ERROR76 "SCI not defined"
#define MSG_ERROR77 "Out of memory"
#define MSG_ERROR78 "Error while printing\r\n"
#define MSG_ERROR79 "-nw or -nwni not found"
#define MSG_ERROR80 "Error no window num.\n"
#define MSG_ERROR81 "SCI has been redefined to "
#define MSG_ERROR82 "HOME has been redefined."
#define MSG_ERROR83 "TCL_LIBRARY has been redefined to "
#define MSG_ERROR84 "TK_LIBRARY has been redefined to "

#endif /*_ERRORSH_*/