//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Rscilab.rc
//
#define IDB_LOGO                        103
#define IDI_VIDE                        104
#define IDI_BIN                         105
#define IDI_COS                         106
#define IDI_COSF                        107
#define IDI_DEM                         108
#define IDI_GRAPH                       109
#define IDI_SAV                         110
#define IDI_SCE                         111
#define IDI_SCI                         112
#define IDI_TST                         113
#define IDC_VERSION_SPLASH              1000
#define IDC_COPYRIGHT_SPLASH            1001
#define IDC_STATIC_ABOUT_HTTP           1002
#define IDC_LICENCE                     1003
#define IDC_BUILD                       1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
