//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rscilab.rc
//
#define IDB_LOGO                        103
#define IDI_VIDE                        104
#define IDI_BIN                         105
#define IDI_COS                         106
#define IDI_COSF                        107
#define IDI_DEM                         108
#define IDI_GRAPH                       109
#define IDI_SAV                         110
#define IDI_SCE                         111
#define IDI_SCI                         112
#define IDI_TST                         113
#define IDI_SCILAB                      123
#define IDI_ZOOM                        125
#define IDI_3DROT                       126
#define IDI_CHDIR                       127
#define IDI_CONSOLE                     128
#define IDI_COPY                        129
#define IDI_EXIT24                      130
#define IDI_FONTS                       131
#define IDI_HELP                        132
#define IDI_METANET24                   133
#define IDI_NEWFILE                     134
#define IDI_PASTE                       135
#define IDI_PRINT                       136
#define IDI_SAVE                        137
#define IDI_SCICOS24                    138
#define IDI_SCILAB24                    139
#define IDI_UNZOOM                      140
#define IDI_ICON1                       141
#define IDI_OPEN                        141
#define IDD_CHOOSEASCILAB               142
#define IDC_VERSION_SPLASH              1000
#define IDC_COPYRIGHT_SPLASH            1001
#define IDC_STATIC_ABOUT_HTTP           1002
#define IDC_LICENCE                     1003
#define IDC_BUILD                       1004
#define IDC_CHECKNEWGRAPHIC             1005
#define IDC_NEWGRAPHICMESSAGE           1006
#define IDC_LISTCHOOSEASCILAB           1007
#define IDC_BUTTON1                     1008
#define IDC_OK                          1008
#define IDC_COMPILMODE                  1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
