//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rscilab.rc
//
#define IDB_LOGO                        103
#define IDI_VIDE                        104
#define IDI_BIN                         105
#define IDI_COS                         106
#define IDI_COSF                        107
#define IDI_DEM                         108
#define IDI_GRAPH                       109
#define IDI_SAV                         110
#define IDI_SCE                         111
#define IDI_SCI                         112
#define IDI_TST                         113
#define IDI_SCILAB                      123
#define IDI_ZOOM                        125
#define IDI_3DROT                       126
#define IDI_CHDIR                       127
#define IDI_CONSOLE                     128
#define IDI_COPY                        129
#define IDI_EXIT24                      130
#define IDI_FONTS                       131
#define IDI_HELP                        132
#define IDI_METANET24                   133
#define IDI_NEWFILE                     134
#define IDI_PASTE                       135
#define IDI_PRINT                       136
#define IDI_SAVE                        137
#define IDI_SCICOS24                    138
#define IDI_SCILAB24                    139
#define IDI_UNZOOM                      140
#define IDI_ICON1                       141
#define IDI_OPEN                        141
#define IDD_CHOOSEASCILAB               142
#define IDD_MDIALOG                     144
#define IDI_GED                         145
#define IDD_FILEASSOCIATION             147
#define ABOUTDLGBOX                     148
#define IDI_RECTANGLE                   149
#define IDI_TEXT                        150
#define IDI_ARROW                       151
#define IDI_DOUBLEARROW                 152
#define IDI_CIRCLE                      153
#define IDI_LINE                        154
#define IDI_POLYLINE                    155
#define IDI_PICKER                      156
#define IDI_PUFFIN                      157
#define IDC_VERSION_SPLASH              1000
#define IDC_COPYRIGHT_SPLASH            1001
#define IDC_STATIC_ABOUT_HTTP           1002
#define IDC_LICENCE                     1003
#define IDC_BUILD                       1004
#define IDC_CHECKNEWGRAPHIC             1005
#define IDC_NEWGRAPHICMESSAGE           1006
#define IDC_LISTCHOOSEASCILAB           1007
#define IDC_OK                          1008
#define IDC_COMPILMODE                  1009
#define IDC_EDITX0Y1                    1010
#define IDC_EDITX1Y0                    1011
#define IDC_EDITX2Y0                    1012
#define IDC_EDITX3Y0                    1013
#define IDC_EDITX4Y0                    1014
#define IDC_EDITX0Y0                    1015
#define IDC_EDITX1Y1                    1016
#define IDC_EDITX2Y1                    1017
#define IDC_EDITX3Y1                    1018
#define IDC_EDITX4Y1                    1019
#define IDC_EDITX0Y3                    1020
#define IDC_EDITX1Y2                    1021
#define IDC_EDITX2Y2                    1022
#define IDC_EDITX3Y2                    1023
#define IDC_EDITX4Y2                    1024
#define IDC_EDITX0Y2                    1025
#define IDC_EDITX1Y3                    1026
#define IDC_EDITX2Y3                    1027
#define IDC_EDITX3Y3                    1028
#define IDC_EDITX4Y3                    1029
#define IDC_SCROLLBARV                  1030
#define IDC_SCROLLBARH                  1031
#define IDC_STATIC_COL0                 1032
#define IDC_STATIC_COL1                 1033
#define IDC_STATIC_COL2                 1034
#define IDC_EDITX0Y4                    1035
#define IDC_EDITX1Y4                    1036
#define IDC_EDITX2Y4                    1037
#define IDC_EDITX3Y4                    1038
#define IDC_EDITX4Y4                    1039
#define IDC_STATIC_COL3                 1040
#define IDC_STATIC_COL4                 1041
#define IDC_STATIC_LIN0                 1042
#define IDC_STATIC_LIN1                 1043
#define IDC_STATIC_LIN2                 1044
#define IDC_STATIC_LIN3                 1045
#define IDC_STATIC_LIN4                 1046
#define IDC_ICONSCE                     1047
#define IDC_ICONSCI                     1048
#define IDC_ICONDEM                     1050
#define IDC_ICONBIN                     1051
#define IDC_ICONCOS                     1052
#define IDC_ICONCOSF                    1053
#define IDC_ICONGRAPH                   1054
#define IDC_ICONSAV                     1055
#define IDC_ICONGRAPHB                  1056
#define IDC_CHECKSCE                    1057
#define IDC_CHECKSCI                    1058
#define IDC_CHECKTST                    1059
#define IDC_CHECKDEM                    1060
#define IDC_CHECKBIN                    1061
#define IDC_CHECKCOS                    1062
#define IDC_CHECKCOSF                   1063
#define IDC_CHECKGRAPH                  1064
#define IDC_CHECKSAV                    1065
#define IDC_CHECKGRAPHB                 1066
#define IDC_STATICLOGO                  1067
#define IDC_OPENRELEASENOTES            1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
