SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = sparselib
NAM = SCI/macros/sparse

MACROS = pcg.sci gmres.sci qmr.sci

include ../Make.lib
