#!/bin/sh
Change Chap*.tex
cp Docu-html.tex manual/.
cp Chapters.tex manual/.
cd manual;
  hevea Docu-html.tex;
  sed -e "s/%/\\\%/g" Docu-html.haux>haux;
  mv haux Docu-html.haux;hevea Docu-html.tex 
  hacha Docu-html.html #execute setref.emacs to change the reference in Docu-html.html before
cd ..
tar czf ../manual-html.tar.gz manual/*.html manual/*.gif
