#!/bin/sh
modify()
{
FILE=`basename $1`
sed -e "s/Shead/subsubsection/g" \
	-e "s/Seealso/subsubsection/g" \
	-e "s/Sauthor/subsubsection/g" \
	-e "s/.phead/%phead/g" \
	-e "s/scitem/itemize/g" \
	-e "s/\\\ind{/%ind{/g"	\
	-e "s/\\\trait/%trait/g" \
	-e "s/\\\bs[ .]/$\\backslash$ /g" \
	-e "s/.begin{flush/%begin{flush/g" \
	-e "s/.end{flush/%end{flush/g" \
	-e "s/\\\label{.*}//g" \
	$1 > manual/$FILE
}

for i in $*
do
   modify $i
done 
