% Results of execution of ../../generated_files/ANGLE.m
% Copyright INRIA
% File generated by Matlab: PLEASE DO NOT EDIT !
% Matlab version: 7.0.0.19901 (R14)

% TEST 1
%res1|0 0|Double|Real
res1 = []
% TEST 2
%res2|0 0|Double|Real
res2 = []
% TEST 3
%res3|0 0|Double|Real
res3 = []
% TEST 4
%res4|1 1|Double|Real
res4 = 0
% TEST 5
%res5|1 3|Double|Real
res5 = [0 0 0]
% TEST 6
%res6|3 1|Double|Real
res6 = [0;0;0]
% TEST 7
%res7|2 3|Double|Real
res7 = [0 0 0;0 0 0]
% TEST 8
%res8|1 1|Double|Real
res8 = 0
% TEST 9
%res9|1 3|Double|Real
res9 = [0 0 0]
% TEST 10
%res10|3 1|Double|Real
res10 = [0;0;0]
% TEST 11
%res11|2 3|Double|Real
res11 = [0 0 0;0 0 0]
% TEST 12
%res12|1 1|Double|Real
res12 = 0
% TEST 13
%res13|1 3|Double|Real
res13 = [0 0 0]
% TEST 14
%res14|3 1|Double|Real
res14 = [0;0;0]
% TEST 15
%res15|2 3|Double|Real
res15 = [0 0 0;0 0 0]
% TEST 16
%res16|1 1|Double|Real
res16 = 1.5707963267949
% TEST 17
%res17|1 3|Double|Real
res17 = [1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 18
%res18|3 1|Double|Real
res18 = [1.5707963267949;1.5707963267949;1.5707963267949]
% TEST 19
%res19|2 3|Double|Real
res19 = [1.5707963267949 1.5707963267949 1.5707963267949;1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 20
%res20|1 1|Double|Real
res20 = 1.5707963267949
% TEST 21
%res21|1 3|Double|Real
res21 = [1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 22
%res22|3 1|Double|Real
res22 = [1.5707963267949;1.5707963267949;1.5707963267949]
% TEST 23
%res23|2 3|Double|Real
res23 = [1.5707963267949 1.5707963267949 1.5707963267949;1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 24
%res24|1 1|Double|Real
res24 = 1.5707963267949
% TEST 25
%res25|1 3|Double|Real
res25 = [1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 26
%res26|3 1|Double|Real
res26 = [1.5707963267949;1.5707963267949;1.5707963267949]
% TEST 27
%res27|2 3|Double|Real
res27 = [1.5707963267949 1.5707963267949 1.5707963267949;1.5707963267949 1.5707963267949 1.5707963267949]
% TEST 28
%res28|1 1|Double|Real
res28 = 0
% TEST 29
%res29|1 4|Double|Real
res29 = [0 0 0 0]
% TEST 30
%res30|1 12|Double|Real
res30 = [0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 31
%res31|3 4|Double|Real
res31 = [0 0 0 0;0 0 0 0;0 0 0 0]
% TEST 32
%res32|2 12|Double|Real
res32 = [0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 33
%res33|1 1|Double|Real
res33 = 0
% TEST 34
%res34|1 4|Double|Real
res34 = [0 0 0 0]
% TEST 35
%res35|1 12|Double|Real
res35 = [0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 36
%res36|3 4|Double|Real
res36 = [0 0 0 0;0 0 0 0;0 0 0 0]
% TEST 37
%res37|2 12|Double|Real
res37 = [0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 38
%res38|1 1|Double|Real
res38 = 0
% TEST 39
%res39|1 4|Double|Real
res39 = [0 0 0 0]
% TEST 40
%res40|1 12|Double|Real
res40 = [0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 41
%res41|3 4|Double|Real
res41 = [0 0 0 0;0 0 0 0;0 0 0 0]
% TEST 42
%res42|2 12|Double|Real
res42 = [0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0]
% TEST 43
%res43|1 1|Double|Real
res43 = 0
% TEST 44
%res44|1 3|Double|Real
res44 = [0 0 0]
% TEST 45
%res45|3 1|Double|Real
res45 = [0;0;0]
% TEST 46
%res46|2 3|Double|Real
res46 = [0 0 0;0 0 0]
% TEST 47
%res47|1 1|Double|Real
res47 = 0
% TEST 48
%res48|1 3|Double|Real
res48 = [0 0 0]
% TEST 49
%res49|3 1|Double|Real
res49 = [0;0;0]
% TEST 50
%res50|2 3|Double|Real
res50 = [0 0 0;0 0 0]
% TEST 51
%res51|1 1|Double|Real
res51 = 0
% TEST 52
%res52|1 3|Double|Real
res52 = [0 0 0]
% TEST 53
%res53|3 1|Double|Real
res53 = [0;0;0]
% TEST 54
%res54|2 3|Double|Real
res54 = [0 0 0;0 0 0]
