% Results of execution of ../../generated_files/FALSE.m
% Copyright INRIA
% File generated by Matlab: PLEASE DO NOT EDIT !
% Matlab version: 7.0.0.19901 (R14)

% TEST 1
%res1|2 2|Boolean|Real
res1 = [false false;false false]
% TEST 2
%res2|3 5|Boolean|Real
res2 = [false false false false false;false false false false false;false false false false false]
% TEST 3
%res3|4 4|Boolean|Real
res3 = [false false false false;false false false false;false false false false;false false false false]
% TEST 4
%res4|10 10|Boolean|Real
res4 = [false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false;false false false false false false false false false false]
% TEST 5
%res5|1 2|Boolean|Real
res5 = [false false]
% TEST 6
%res6|1 1|Boolean|Real
res6 = false
% TEST 7
%res7|1 2|Boolean|Real
res7 = [false false]
