% Test file for function gammaln()
% Copyright INRIA
% File generated by Matlab: PLEASE DO NOT EDIT !
% Matlab version: 7.0.0.19901 (R14)

% TEST 1
res1 = gammaln([]);
% TEST 2
res2 = gammaln(Unknown_Type([]));
% TEST 3
res3 = gammaln(Unknown_Dims([]));
% TEST 4
res4 = gammaln([1]);
% TEST 5
res5 = gammaln([1,2,3]);
% TEST 6
res6 = gammaln([1;2;3]);
% TEST 7
res7 = gammaln([1,2,3;4,5,6]);
% TEST 8
res8 = gammaln(Unknown_Type([1]));
% TEST 9
res9 = gammaln(Unknown_Type([1,2,3]));
% TEST 10
res10 = gammaln(Unknown_Type([1;2;3]));
% TEST 11
res11 = gammaln(Unknown_Type([1,2,3;4,5,6]));
% TEST 12
res12 = gammaln(Unknown_Dims([1]));
% TEST 13
res13 = gammaln(Unknown_Dims([1,2,3]));
% TEST 14
res14 = gammaln(Unknown_Dims([1;2;3]));
% TEST 15
res15 = gammaln(Unknown_Dims([1,2,3;4,5,6]));
