% Results of execution of ../../generated_files/ISFINITE.m
% File generated by Matlab: PLEASE DO NOT EDIT !
% Matlab version: 7.6.0.324 (R2008a)

% TEST 1
%res1|0 0|Boolean|Real
res1 = []
% TEST 2
%res2|0 0|Boolean|Real
res2 = []
% TEST 3
%res3|0 0|Boolean|Real
res3 = []
% TEST 4
%res4|1 1|Boolean|Real
res4 = true
% TEST 5
%res5|1 3|Boolean|Real
res5 = [true true true]
% TEST 6
%res6|3 1|Boolean|Real
res6 = [true;true;true]
% TEST 7
%res7|2 3|Boolean|Real
res7 = [true true true;true true true]
% TEST 8
%res8|1 1|Boolean|Real
res8 = true
% TEST 9
%res9|1 3|Boolean|Real
res9 = [true true true]
% TEST 10
%res10|3 1|Boolean|Real
res10 = [true;true;true]
% TEST 11
%res11|2 3|Boolean|Real
res11 = [true true true;true true true]
% TEST 12
%res12|1 1|Boolean|Real
res12 = true
% TEST 13
%res13|1 3|Boolean|Real
res13 = [true true true]
% TEST 14
%res14|3 1|Boolean|Real
res14 = [true;true;true]
% TEST 15
%res15|2 3|Boolean|Real
res15 = [true true true;true true true]
% TEST 16
%res16|1 1|Boolean|Real
res16 = true
% TEST 17
%res17|1 3|Boolean|Real
res17 = [true true true]
% TEST 18
%res18|3 1|Boolean|Real
res18 = [true;true;true]
% TEST 19
%res19|2 3|Boolean|Real
res19 = [true true true;true true true]
% TEST 20
%res20|1 1|Boolean|Real
res20 = true
% TEST 21
%res21|1 3|Boolean|Real
res21 = [true true true]
% TEST 22
%res22|3 1|Boolean|Real
res22 = [true;true;true]
% TEST 23
%res23|2 3|Boolean|Real
res23 = [true true true;true true true]
% TEST 24
%res24|1 1|Boolean|Real
res24 = true
% TEST 25
%res25|1 3|Boolean|Real
res25 = [true true true]
% TEST 26
%res26|3 1|Boolean|Real
res26 = [true;true;true]
% TEST 27
%res27|2 3|Boolean|Real
res27 = [true true true;true true true]
% TEST 28
%res28|1 1|Boolean|Real
res28 = true
% TEST 29
%res29|1 4|Boolean|Real
res29 = [true true true true]
% TEST 30
%res30|1 12|Boolean|Real
res30 = [true true true true true true true true true true true true]
% TEST 31
%res31|3 4|Boolean|Real
res31 = [true true true true;true true true true;true true true true]
% TEST 32
%res32|2 12|Boolean|Real
res32 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 33
%res33|1 1|Boolean|Real
res33 = true
% TEST 34
%res34|1 4|Boolean|Real
res34 = [true true true true]
% TEST 35
%res35|1 12|Boolean|Real
res35 = [true true true true true true true true true true true true]
% TEST 36
%res36|3 4|Boolean|Real
res36 = [true true true true;true true true true;true true true true]
% TEST 37
%res37|2 12|Boolean|Real
res37 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 38
%res38|1 1|Boolean|Real
res38 = true
% TEST 39
%res39|1 4|Boolean|Real
res39 = [true true true true]
% TEST 40
%res40|1 12|Boolean|Real
res40 = [true true true true true true true true true true true true]
% TEST 41
%res41|3 4|Boolean|Real
res41 = [true true true true;true true true true;true true true true]
% TEST 42
%res42|2 12|Boolean|Real
res42 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 43
%res43|1 1|Boolean|Real
res43 = true
% TEST 44
%res44|1 3|Boolean|Real
res44 = [true true true]
% TEST 45
%res45|3 1|Boolean|Real
res45 = [true;true;true]
% TEST 46
%res46|2 3|Boolean|Real
res46 = [true true true;true true true]
% TEST 47
%res47|1 1|Boolean|Real
res47 = true
% TEST 48
%res48|1 3|Boolean|Real
res48 = [true true true]
% TEST 49
%res49|3 1|Boolean|Real
res49 = [true;true;true]
% TEST 50
%res50|2 3|Boolean|Real
res50 = [true true true;true true true]
% TEST 51
%res51|1 1|Boolean|Real
res51 = true
% TEST 52
%res52|1 3|Boolean|Real
res52 = [true true true]
% TEST 53
%res53|3 1|Boolean|Real
res53 = [true;true;true]
% TEST 54
%res54|2 3|Boolean|Real
res54 = [true true true;true true true]
% TEST 55
%res55|1 1|Boolean|Real
res55 = false
% TEST 56
%res56|1 1|Boolean|Real
res56 = false
% TEST 57
%res57|1 1|Boolean|Real
res57 = false
% TEST 58
%res58|1 1|Boolean|Real
res58 = false
