% Results of execution of ../../generated_files/LOGICAL_AND.m
% Copyright INRIA
% File generated by Matlab: PLEASE DO NOT EDIT !
% Matlab version: 7.0.0.19901 (R14)

% TEST 1
%res1|0 0|Boolean|Real
res1 = []
% TEST 2
%res2|0 0|Boolean|Real
res2 = []
% TEST 3
%res3|0 0|Boolean|Real
res3 = []
% TEST 4
%res4|1 1|Boolean|Real
res4 = true
% TEST 5
%res5|1 3|Boolean|Real
res5 = [true true true]
% TEST 6
%res6|3 1|Boolean|Real
res6 = [true;true;true]
% TEST 7
%res7|2 3|Boolean|Real
res7 = [true true true;true true true]
% TEST 8
%res8|1 1|Boolean|Real
res8 = true
% TEST 9
%res9|1 3|Boolean|Real
res9 = [true true true]
% TEST 10
%res10|3 1|Boolean|Real
res10 = [true;true;true]
% TEST 11
%res11|2 3|Boolean|Real
res11 = [true true true;true true true]
% TEST 12
%res12|1 1|Boolean|Real
res12 = true
% TEST 13
%res13|1 3|Boolean|Real
res13 = [true true true]
% TEST 14
%res14|3 1|Boolean|Real
res14 = [true;true;true]
% TEST 15
%res15|2 3|Boolean|Real
res15 = [true true true;true true true]
% TEST 16
%res16|1 1|Boolean|Real
res16 = true
% TEST 17
%res17|1 4|Boolean|Real
res17 = [true true true true]
% TEST 18
%res18|1 12|Boolean|Real
res18 = [true true true true true true true true true true true true]
% TEST 19
%res19|3 4|Boolean|Real
res19 = [true true true true;true true true true;true true true true]
% TEST 20
%res20|2 12|Boolean|Real
res20 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 21
%res21|1 1|Boolean|Real
res21 = true
% TEST 22
%res22|1 4|Boolean|Real
res22 = [true true true true]
% TEST 23
%res23|1 12|Boolean|Real
res23 = [true true true true true true true true true true true true]
% TEST 24
%res24|3 4|Boolean|Real
res24 = [true true true true;true true true true;true true true true]
% TEST 25
%res25|2 12|Boolean|Real
res25 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 26
%res26|1 1|Boolean|Real
res26 = true
% TEST 27
%res27|1 4|Boolean|Real
res27 = [true true true true]
% TEST 28
%res28|1 12|Boolean|Real
res28 = [true true true true true true true true true true true true]
% TEST 29
%res29|3 4|Boolean|Real
res29 = [true true true true;true true true true;true true true true]
% TEST 30
%res30|2 12|Boolean|Real
res30 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 31
%res31|1 1|Boolean|Real
res31 = true
% TEST 32
%res32|1 3|Boolean|Real
res32 = [true false false]
% TEST 33
%res33|3 1|Boolean|Real
res33 = [true;false;false]
% TEST 34
%res34|2 3|Boolean|Real
res34 = [true false false;true false false]
% TEST 35
%res35|1 1|Boolean|Real
res35 = true
% TEST 36
%res36|1 3|Boolean|Real
res36 = [true false false]
% TEST 37
%res37|3 1|Boolean|Real
res37 = [true;false;false]
% TEST 38
%res38|2 3|Boolean|Real
res38 = [true false false;true false false]
% TEST 39
%res39|1 1|Boolean|Real
res39 = true
% TEST 40
%res40|1 3|Boolean|Real
res40 = [true false false]
% TEST 41
%res41|3 1|Boolean|Real
res41 = [true;false;false]
% TEST 42
%res42|2 3|Boolean|Real
res42 = [true false false;true false false]
% TEST 43
%res43|0 0|Boolean|Real
res43 = []
% TEST 44
%res44|0 0|Boolean|Real
res44 = []
% TEST 45
%res45|0 0|Boolean|Real
res45 = []
% TEST 46
%res46|1 1|Boolean|Real
res46 = true
% TEST 47
%res47|1 3|Boolean|Real
res47 = [true true true]
% TEST 48
%res48|3 1|Boolean|Real
res48 = [true;true;true]
% TEST 49
%res49|2 3|Boolean|Real
res49 = [true true true;true true true]
% TEST 50
%res50|1 1|Boolean|Real
res50 = true
% TEST 51
%res51|1 3|Boolean|Real
res51 = [true true true]
% TEST 52
%res52|3 1|Boolean|Real
res52 = [true;true;true]
% TEST 53
%res53|2 3|Boolean|Real
res53 = [true true true;true true true]
% TEST 54
%res54|1 1|Boolean|Real
res54 = true
% TEST 55
%res55|1 3|Boolean|Real
res55 = [true true true]
% TEST 56
%res56|3 1|Boolean|Real
res56 = [true;true;true]
% TEST 57
%res57|2 3|Boolean|Real
res57 = [true true true;true true true]
% TEST 58
%res58|1 1|Boolean|Real
res58 = true
% TEST 59
%res59|1 4|Boolean|Real
res59 = [true true true true]
% TEST 60
%res60|1 12|Boolean|Real
res60 = [true true true true true true true true true true true true]
% TEST 61
%res61|3 4|Boolean|Real
res61 = [true true true true;true true true true;true true true true]
% TEST 62
%res62|2 12|Boolean|Real
res62 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 63
%res63|1 1|Boolean|Real
res63 = true
% TEST 64
%res64|1 4|Boolean|Real
res64 = [true true true true]
% TEST 65
%res65|1 12|Boolean|Real
res65 = [true true true true true true true true true true true true]
% TEST 66
%res66|3 4|Boolean|Real
res66 = [true true true true;true true true true;true true true true]
% TEST 67
%res67|2 12|Boolean|Real
res67 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 68
%res68|1 1|Boolean|Real
res68 = true
% TEST 69
%res69|1 4|Boolean|Real
res69 = [true true true true]
% TEST 70
%res70|1 12|Boolean|Real
res70 = [true true true true true true true true true true true true]
% TEST 71
%res71|3 4|Boolean|Real
res71 = [true true true true;true true true true;true true true true]
% TEST 72
%res72|2 12|Boolean|Real
res72 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 73
%res73|1 1|Boolean|Real
res73 = true
% TEST 74
%res74|1 3|Boolean|Real
res74 = [true false true]
% TEST 75
%res75|3 1|Boolean|Real
res75 = [true;false;true]
% TEST 76
%res76|2 3|Boolean|Real
res76 = [true false true;true true false]
% TEST 77
%res77|1 1|Boolean|Real
res77 = true
% TEST 78
%res78|1 3|Boolean|Real
res78 = [true false true]
% TEST 79
%res79|3 1|Boolean|Real
res79 = [true;false;true]
% TEST 80
%res80|2 3|Boolean|Real
res80 = [true false true;true true false]
% TEST 81
%res81|1 1|Boolean|Real
res81 = true
% TEST 82
%res82|1 3|Boolean|Real
res82 = [true false true]
% TEST 83
%res83|3 1|Boolean|Real
res83 = [true;false;true]
% TEST 84
%res84|2 3|Boolean|Real
res84 = [true false true;true true false]
% TEST 85
%res85|0 0|Boolean|Real
res85 = []
% TEST 86
%res86|0 0|Boolean|Real
res86 = []
% TEST 87
%res87|0 0|Boolean|Real
res87 = []
% TEST 88
%res88|1 1|Boolean|Real
res88 = true
% TEST 89
%res89|1 3|Boolean|Real
res89 = [true true true]
% TEST 90
%res90|3 1|Boolean|Real
res90 = [true;true;true]
% TEST 91
%res91|2 3|Boolean|Real
res91 = [true true true;true true true]
% TEST 92
%res92|1 1|Boolean|Real
res92 = true
% TEST 93
%res93|1 3|Boolean|Real
res93 = [true true true]
% TEST 94
%res94|3 1|Boolean|Real
res94 = [true;true;true]
% TEST 95
%res95|2 3|Boolean|Real
res95 = [true true true;true true true]
% TEST 96
%res96|1 1|Boolean|Real
res96 = true
% TEST 97
%res97|1 3|Boolean|Real
res97 = [true true true]
% TEST 98
%res98|3 1|Boolean|Real
res98 = [true;true;true]
% TEST 99
%res99|2 3|Boolean|Real
res99 = [true true true;true true true]
% TEST 100
%res100|1 1|Boolean|Real
res100 = true
% TEST 101
%res101|1 4|Boolean|Real
res101 = [true true true true]
% TEST 102
%res102|1 12|Boolean|Real
res102 = [true true true true true true true true true true true true]
% TEST 103
%res103|3 4|Boolean|Real
res103 = [true true true true;true true true true;true true true true]
% TEST 104
%res104|2 12|Boolean|Real
res104 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 105
%res105|1 1|Boolean|Real
res105 = true
% TEST 106
%res106|1 4|Boolean|Real
res106 = [true true true true]
% TEST 107
%res107|1 12|Boolean|Real
res107 = [true true true true true true true true true true true true]
% TEST 108
%res108|3 4|Boolean|Real
res108 = [true true true true;true true true true;true true true true]
% TEST 109
%res109|2 12|Boolean|Real
res109 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 110
%res110|1 1|Boolean|Real
res110 = true
% TEST 111
%res111|1 4|Boolean|Real
res111 = [true true true true]
% TEST 112
%res112|1 12|Boolean|Real
res112 = [true true true true true true true true true true true true]
% TEST 113
%res113|3 4|Boolean|Real
res113 = [true true true true;true true true true;true true true true]
% TEST 114
%res114|2 12|Boolean|Real
res114 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 115
%res115|1 1|Boolean|Real
res115 = true
% TEST 116
%res116|1 3|Boolean|Real
res116 = [true false true]
% TEST 117
%res117|3 1|Boolean|Real
res117 = [true;false;true]
% TEST 118
%res118|2 3|Boolean|Real
res118 = [true false true;true true false]
% TEST 119
%res119|1 1|Boolean|Real
res119 = true
% TEST 120
%res120|1 3|Boolean|Real
res120 = [true false true]
% TEST 121
%res121|3 1|Boolean|Real
res121 = [true;false;true]
% TEST 122
%res122|2 3|Boolean|Real
res122 = [true false true;true true false]
% TEST 123
%res123|1 1|Boolean|Real
res123 = true
% TEST 124
%res124|1 3|Boolean|Real
res124 = [true false true]
% TEST 125
%res125|3 1|Boolean|Real
res125 = [true;false;true]
% TEST 126
%res126|2 3|Boolean|Real
res126 = [true false true;true true false]
% TEST 127
%res127|0 0|Boolean|Real
res127 = []
% TEST 128
%res128|0 0|Boolean|Real
res128 = []
% TEST 129
%res129|0 0|Boolean|Real
res129 = []
% TEST 130
%res130|1 1|Boolean|Real
res130 = true
% TEST 131
%res131|1 3|Boolean|Real
res131 = [true true true]
% TEST 132
%res132|3 1|Boolean|Real
res132 = [true;true;true]
% TEST 133
%res133|2 3|Boolean|Real
res133 = [true true true;true true true]
% TEST 134
%res134|1 1|Boolean|Real
res134 = true
% TEST 135
%res135|1 3|Boolean|Real
res135 = [true true true]
% TEST 136
%res136|3 1|Boolean|Real
res136 = [true;true;true]
% TEST 137
%res137|2 3|Boolean|Real
res137 = [true true true;true true true]
% TEST 138
%res138|1 1|Boolean|Real
res138 = true
% TEST 139
%res139|1 3|Boolean|Real
res139 = [true true true]
% TEST 140
%res140|3 1|Boolean|Real
res140 = [true;true;true]
% TEST 141
%res141|2 3|Boolean|Real
res141 = [true true true;true true true]
% TEST 142
%res142|1 1|Boolean|Real
res142 = true
% TEST 143
%res143|1 4|Boolean|Real
res143 = [true true true true]
% TEST 144
%res144|1 12|Boolean|Real
res144 = [true true true true true true true true true true true true]
% TEST 145
%res145|3 4|Boolean|Real
res145 = [true true true true;true true true true;true true true true]
% TEST 146
%res146|2 12|Boolean|Real
res146 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 147
%res147|1 1|Boolean|Real
res147 = true
% TEST 148
%res148|1 4|Boolean|Real
res148 = [true true true true]
% TEST 149
%res149|1 12|Boolean|Real
res149 = [true true true true true true true true true true true true]
% TEST 150
%res150|3 4|Boolean|Real
res150 = [true true true true;true true true true;true true true true]
% TEST 151
%res151|2 12|Boolean|Real
res151 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 152
%res152|1 1|Boolean|Real
res152 = true
% TEST 153
%res153|1 4|Boolean|Real
res153 = [true true true true]
% TEST 154
%res154|1 12|Boolean|Real
res154 = [true true true true true true true true true true true true]
% TEST 155
%res155|3 4|Boolean|Real
res155 = [true true true true;true true true true;true true true true]
% TEST 156
%res156|2 12|Boolean|Real
res156 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 157
%res157|1 1|Boolean|Real
res157 = true
% TEST 158
%res158|1 3|Boolean|Real
res158 = [true false true]
% TEST 159
%res159|3 1|Boolean|Real
res159 = [true;false;true]
% TEST 160
%res160|2 3|Boolean|Real
res160 = [true false true;true true false]
% TEST 161
%res161|1 1|Boolean|Real
res161 = true
% TEST 162
%res162|1 3|Boolean|Real
res162 = [true false true]
% TEST 163
%res163|3 1|Boolean|Real
res163 = [true;false;true]
% TEST 164
%res164|2 3|Boolean|Real
res164 = [true false true;true true false]
% TEST 165
%res165|1 1|Boolean|Real
res165 = true
% TEST 166
%res166|1 3|Boolean|Real
res166 = [true false true]
% TEST 167
%res167|3 1|Boolean|Real
res167 = [true;false;true]
% TEST 168
%res168|2 3|Boolean|Real
res168 = [true false true;true true false]
% TEST 169
%res169|0 0|Boolean|Real
res169 = []
% TEST 170
%res170|0 0|Boolean|Real
res170 = []
% TEST 171
%res171|0 0|Boolean|Real
res171 = []
% TEST 172
%res172|1 1|Boolean|Real
res172 = true
% TEST 173
%res173|1 3|Boolean|Real
res173 = [true true true]
% TEST 174
%res174|3 1|Boolean|Real
res174 = [true;true;true]
% TEST 175
%res175|2 3|Boolean|Real
res175 = [true true true;true true true]
% TEST 176
%res176|1 1|Boolean|Real
res176 = true
% TEST 177
%res177|1 3|Boolean|Real
res177 = [true true true]
% TEST 178
%res178|3 1|Boolean|Real
res178 = [true;true;true]
% TEST 179
%res179|2 3|Boolean|Real
res179 = [true true true;true true true]
% TEST 180
%res180|1 1|Boolean|Real
res180 = true
% TEST 181
%res181|1 3|Boolean|Real
res181 = [true true true]
% TEST 182
%res182|3 1|Boolean|Real
res182 = [true;true;true]
% TEST 183
%res183|2 3|Boolean|Real
res183 = [true true true;true true true]
% TEST 184
%res184|1 1|Boolean|Real
res184 = true
% TEST 185
%res185|1 4|Boolean|Real
res185 = [true true true true]
% TEST 186
%res186|1 12|Boolean|Real
res186 = [true true true true true true true true true true true true]
% TEST 187
%res187|3 4|Boolean|Real
res187 = [true true true true;true true true true;true true true true]
% TEST 188
%res188|2 12|Boolean|Real
res188 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 189
%res189|1 1|Boolean|Real
res189 = true
% TEST 190
%res190|1 4|Boolean|Real
res190 = [true true true true]
% TEST 191
%res191|1 12|Boolean|Real
res191 = [true true true true true true true true true true true true]
% TEST 192
%res192|3 4|Boolean|Real
res192 = [true true true true;true true true true;true true true true]
% TEST 193
%res193|2 12|Boolean|Real
res193 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 194
%res194|1 1|Boolean|Real
res194 = true
% TEST 195
%res195|1 4|Boolean|Real
res195 = [true true true true]
% TEST 196
%res196|1 12|Boolean|Real
res196 = [true true true true true true true true true true true true]
% TEST 197
%res197|3 4|Boolean|Real
res197 = [true true true true;true true true true;true true true true]
% TEST 198
%res198|2 12|Boolean|Real
res198 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 199
%res199|1 1|Boolean|Real
res199 = true
% TEST 200
%res200|1 3|Boolean|Real
res200 = [true false true]
% TEST 201
%res201|3 1|Boolean|Real
res201 = [true;false;true]
% TEST 202
%res202|2 3|Boolean|Real
res202 = [true false true;true true false]
% TEST 203
%res203|1 1|Boolean|Real
res203 = true
% TEST 204
%res204|1 3|Boolean|Real
res204 = [true false true]
% TEST 205
%res205|3 1|Boolean|Real
res205 = [true;false;true]
% TEST 206
%res206|2 3|Boolean|Real
res206 = [true false true;true true false]
% TEST 207
%res207|1 1|Boolean|Real
res207 = true
% TEST 208
%res208|1 3|Boolean|Real
res208 = [true false true]
% TEST 209
%res209|3 1|Boolean|Real
res209 = [true;false;true]
% TEST 210
%res210|2 3|Boolean|Real
res210 = [true false true;true true false]
% TEST 211
%res211|0 0|Boolean|Real
res211 = []
% TEST 212
%res212|0 0|Boolean|Real
res212 = []
% TEST 213
%res213|0 0|Boolean|Real
res213 = []
% TEST 214
%res214|1 1|Boolean|Real
res214 = true
% TEST 215
%res215|1 3|Boolean|Real
res215 = [true true true]
% TEST 216
%res216|3 1|Boolean|Real
res216 = [true;true;true]
% TEST 217
%res217|2 3|Boolean|Real
res217 = [true true true;true true true]
% TEST 218
%res218|1 1|Boolean|Real
res218 = true
% TEST 219
%res219|1 3|Boolean|Real
res219 = [true true true]
% TEST 220
%res220|3 1|Boolean|Real
res220 = [true;true;true]
% TEST 221
%res221|2 3|Boolean|Real
res221 = [true true true;true true true]
% TEST 222
%res222|1 1|Boolean|Real
res222 = true
% TEST 223
%res223|1 3|Boolean|Real
res223 = [true true true]
% TEST 224
%res224|3 1|Boolean|Real
res224 = [true;true;true]
% TEST 225
%res225|2 3|Boolean|Real
res225 = [true true true;true true true]
% TEST 226
%res226|1 1|Boolean|Real
res226 = true
% TEST 227
%res227|1 4|Boolean|Real
res227 = [true true true true]
% TEST 228
%res228|1 12|Boolean|Real
res228 = [true true true true true true true true true true true true]
% TEST 229
%res229|3 4|Boolean|Real
res229 = [true true true true;true true true true;true true true true]
% TEST 230
%res230|2 12|Boolean|Real
res230 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 231
%res231|1 1|Boolean|Real
res231 = true
% TEST 232
%res232|1 4|Boolean|Real
res232 = [true true true true]
% TEST 233
%res233|1 12|Boolean|Real
res233 = [true true true true true true true true true true true true]
% TEST 234
%res234|3 4|Boolean|Real
res234 = [true true true true;true true true true;true true true true]
% TEST 235
%res235|2 12|Boolean|Real
res235 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 236
%res236|1 1|Boolean|Real
res236 = true
% TEST 237
%res237|1 4|Boolean|Real
res237 = [true true true true]
% TEST 238
%res238|1 12|Boolean|Real
res238 = [true true true true true true true true true true true true]
% TEST 239
%res239|3 4|Boolean|Real
res239 = [true true true true;true true true true;true true true true]
% TEST 240
%res240|2 12|Boolean|Real
res240 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 241
%res241|1 1|Boolean|Real
res241 = true
% TEST 242
%res242|1 3|Boolean|Real
res242 = [true false true]
% TEST 243
%res243|3 1|Boolean|Real
res243 = [true;false;true]
% TEST 244
%res244|2 3|Boolean|Real
res244 = [true false true;true true false]
% TEST 245
%res245|1 1|Boolean|Real
res245 = true
% TEST 246
%res246|1 3|Boolean|Real
res246 = [true false true]
% TEST 247
%res247|3 1|Boolean|Real
res247 = [true;false;true]
% TEST 248
%res248|2 3|Boolean|Real
res248 = [true false true;true true false]
% TEST 249
%res249|1 1|Boolean|Real
res249 = true
% TEST 250
%res250|1 3|Boolean|Real
res250 = [true false true]
% TEST 251
%res251|3 1|Boolean|Real
res251 = [true;false;true]
% TEST 252
%res252|2 3|Boolean|Real
res252 = [true false true;true true false]
% TEST 253
%res253|0 0|Boolean|Real
res253 = []
% TEST 254
%res254|0 0|Boolean|Real
res254 = []
% TEST 255
%res255|0 0|Boolean|Real
res255 = []
% TEST 256
%res256|1 1|Boolean|Real
res256 = true
% TEST 257
%res257|1 3|Boolean|Real
res257 = [true true true]
% TEST 258
%res258|3 1|Boolean|Real
res258 = [true;true;true]
% TEST 259
%res259|2 3|Boolean|Real
res259 = [true true true;true true true]
% TEST 260
%res260|1 1|Boolean|Real
res260 = true
% TEST 261
%res261|1 3|Boolean|Real
res261 = [true true true]
% TEST 262
%res262|3 1|Boolean|Real
res262 = [true;true;true]
% TEST 263
%res263|2 3|Boolean|Real
res263 = [true true true;true true true]
% TEST 264
%res264|1 1|Boolean|Real
res264 = true
% TEST 265
%res265|1 3|Boolean|Real
res265 = [true true true]
% TEST 266
%res266|3 1|Boolean|Real
res266 = [true;true;true]
% TEST 267
%res267|2 3|Boolean|Real
res267 = [true true true;true true true]
% TEST 268
%res268|1 1|Boolean|Real
res268 = true
% TEST 269
%res269|1 4|Boolean|Real
res269 = [true true true true]
% TEST 270
%res270|1 12|Boolean|Real
res270 = [true true true true true true true true true true true true]
% TEST 271
%res271|3 4|Boolean|Real
res271 = [true true true true;true true true true;true true true true]
% TEST 272
%res272|2 12|Boolean|Real
res272 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 273
%res273|1 1|Boolean|Real
res273 = true
% TEST 274
%res274|1 4|Boolean|Real
res274 = [true true true true]
% TEST 275
%res275|1 12|Boolean|Real
res275 = [true true true true true true true true true true true true]
% TEST 276
%res276|3 4|Boolean|Real
res276 = [true true true true;true true true true;true true true true]
% TEST 277
%res277|2 12|Boolean|Real
res277 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 278
%res278|1 1|Boolean|Real
res278 = true
% TEST 279
%res279|1 4|Boolean|Real
res279 = [true true true true]
% TEST 280
%res280|1 12|Boolean|Real
res280 = [true true true true true true true true true true true true]
% TEST 281
%res281|3 4|Boolean|Real
res281 = [true true true true;true true true true;true true true true]
% TEST 282
%res282|2 12|Boolean|Real
res282 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 283
%res283|1 1|Boolean|Real
res283 = true
% TEST 284
%res284|1 3|Boolean|Real
res284 = [true false true]
% TEST 285
%res285|3 1|Boolean|Real
res285 = [true;false;true]
% TEST 286
%res286|2 3|Boolean|Real
res286 = [true false true;true true false]
% TEST 287
%res287|1 1|Boolean|Real
res287 = true
% TEST 288
%res288|1 3|Boolean|Real
res288 = [true false true]
% TEST 289
%res289|3 1|Boolean|Real
res289 = [true;false;true]
% TEST 290
%res290|2 3|Boolean|Real
res290 = [true false true;true true false]
% TEST 291
%res291|1 1|Boolean|Real
res291 = true
% TEST 292
%res292|1 3|Boolean|Real
res292 = [true false true]
% TEST 293
%res293|3 1|Boolean|Real
res293 = [true;false;true]
% TEST 294
%res294|2 3|Boolean|Real
res294 = [true false true;true true false]
% TEST 295
%res295|0 0|Boolean|Real
res295 = []
% TEST 296
%res296|0 0|Boolean|Real
res296 = []
% TEST 297
%res297|0 0|Boolean|Real
res297 = []
% TEST 298
%res298|1 1|Boolean|Real
res298 = true
% TEST 299
%res299|1 3|Boolean|Real
res299 = [true true true]
% TEST 300
%res300|3 1|Boolean|Real
res300 = [true;true;true]
% TEST 301
%res301|2 3|Boolean|Real
res301 = [true true true;true true true]
% TEST 302
%res302|1 1|Boolean|Real
res302 = true
% TEST 303
%res303|1 3|Boolean|Real
res303 = [true true true]
% TEST 304
%res304|3 1|Boolean|Real
res304 = [true;true;true]
% TEST 305
%res305|2 3|Boolean|Real
res305 = [true true true;true true true]
% TEST 306
%res306|1 1|Boolean|Real
res306 = true
% TEST 307
%res307|1 3|Boolean|Real
res307 = [true true true]
% TEST 308
%res308|3 1|Boolean|Real
res308 = [true;true;true]
% TEST 309
%res309|2 3|Boolean|Real
res309 = [true true true;true true true]
% TEST 310
%res310|1 1|Boolean|Real
res310 = true
% TEST 311
%res311|1 4|Boolean|Real
res311 = [true true true true]
% TEST 312
%res312|1 12|Boolean|Real
res312 = [true true true true true true true true true true true true]
% TEST 313
%res313|3 4|Boolean|Real
res313 = [true true true true;true true true true;true true true true]
% TEST 314
%res314|2 12|Boolean|Real
res314 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 315
%res315|1 1|Boolean|Real
res315 = true
% TEST 316
%res316|1 4|Boolean|Real
res316 = [true true true true]
% TEST 317
%res317|1 12|Boolean|Real
res317 = [true true true true true true true true true true true true]
% TEST 318
%res318|3 4|Boolean|Real
res318 = [true true true true;true true true true;true true true true]
% TEST 319
%res319|2 12|Boolean|Real
res319 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 320
%res320|1 1|Boolean|Real
res320 = true
% TEST 321
%res321|1 4|Boolean|Real
res321 = [true true true true]
% TEST 322
%res322|1 12|Boolean|Real
res322 = [true true true true true true true true true true true true]
% TEST 323
%res323|3 4|Boolean|Real
res323 = [true true true true;true true true true;true true true true]
% TEST 324
%res324|2 12|Boolean|Real
res324 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 325
%res325|1 1|Boolean|Real
res325 = true
% TEST 326
%res326|1 3|Boolean|Real
res326 = [true false true]
% TEST 327
%res327|3 1|Boolean|Real
res327 = [true;false;true]
% TEST 328
%res328|2 3|Boolean|Real
res328 = [true false true;true true false]
% TEST 329
%res329|1 1|Boolean|Real
res329 = true
% TEST 330
%res330|1 3|Boolean|Real
res330 = [true false true]
% TEST 331
%res331|3 1|Boolean|Real
res331 = [true;false;true]
% TEST 332
%res332|2 3|Boolean|Real
res332 = [true false true;true true false]
% TEST 333
%res333|1 1|Boolean|Real
res333 = true
% TEST 334
%res334|1 3|Boolean|Real
res334 = [true false true]
% TEST 335
%res335|3 1|Boolean|Real
res335 = [true;false;true]
% TEST 336
%res336|2 3|Boolean|Real
res336 = [true false true;true true false]
% TEST 337
%res337|0 0|Boolean|Real
res337 = []
% TEST 338
%res338|0 0|Boolean|Real
res338 = []
% TEST 339
%res339|0 0|Boolean|Real
res339 = []
% TEST 340
%res340|1 1|Boolean|Real
res340 = true
% TEST 341
%res341|1 3|Boolean|Real
res341 = [true true true]
% TEST 342
%res342|3 1|Boolean|Real
res342 = [true;true;true]
% TEST 343
%res343|2 3|Boolean|Real
res343 = [true true true;true true true]
% TEST 344
%res344|1 1|Boolean|Real
res344 = true
% TEST 345
%res345|1 3|Boolean|Real
res345 = [true true true]
% TEST 346
%res346|3 1|Boolean|Real
res346 = [true;true;true]
% TEST 347
%res347|2 3|Boolean|Real
res347 = [true true true;true true true]
% TEST 348
%res348|1 1|Boolean|Real
res348 = true
% TEST 349
%res349|1 3|Boolean|Real
res349 = [true true true]
% TEST 350
%res350|3 1|Boolean|Real
res350 = [true;true;true]
% TEST 351
%res351|2 3|Boolean|Real
res351 = [true true true;true true true]
% TEST 352
%res352|1 1|Boolean|Real
res352 = true
% TEST 353
%res353|1 4|Boolean|Real
res353 = [true true true true]
% TEST 354
%res354|1 12|Boolean|Real
res354 = [true true true true true true true true true true true true]
% TEST 355
%res355|3 4|Boolean|Real
res355 = [true true true true;true true true true;true true true true]
% TEST 356
%res356|2 12|Boolean|Real
res356 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 357
%res357|1 1|Boolean|Real
res357 = true
% TEST 358
%res358|1 4|Boolean|Real
res358 = [true true true true]
% TEST 359
%res359|1 12|Boolean|Real
res359 = [true true true true true true true true true true true true]
% TEST 360
%res360|3 4|Boolean|Real
res360 = [true true true true;true true true true;true true true true]
% TEST 361
%res361|2 12|Boolean|Real
res361 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 362
%res362|1 1|Boolean|Real
res362 = true
% TEST 363
%res363|1 4|Boolean|Real
res363 = [true true true true]
% TEST 364
%res364|1 12|Boolean|Real
res364 = [true true true true true true true true true true true true]
% TEST 365
%res365|3 4|Boolean|Real
res365 = [true true true true;true true true true;true true true true]
% TEST 366
%res366|2 12|Boolean|Real
res366 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 367
%res367|1 1|Boolean|Real
res367 = true
% TEST 368
%res368|1 3|Boolean|Real
res368 = [true false true]
% TEST 369
%res369|3 1|Boolean|Real
res369 = [true;false;true]
% TEST 370
%res370|2 3|Boolean|Real
res370 = [true false true;true true false]
% TEST 371
%res371|1 1|Boolean|Real
res371 = true
% TEST 372
%res372|1 3|Boolean|Real
res372 = [true false true]
% TEST 373
%res373|3 1|Boolean|Real
res373 = [true;false;true]
% TEST 374
%res374|2 3|Boolean|Real
res374 = [true false true;true true false]
% TEST 375
%res375|1 1|Boolean|Real
res375 = true
% TEST 376
%res376|1 3|Boolean|Real
res376 = [true false true]
% TEST 377
%res377|3 1|Boolean|Real
res377 = [true;false;true]
% TEST 378
%res378|2 3|Boolean|Real
res378 = [true false true;true true false]
% TEST 379
%res379|0 0|Boolean|Real
res379 = []
% TEST 380
%res380|0 0|Boolean|Real
res380 = []
% TEST 381
%res381|0 0|Boolean|Real
res381 = []
% TEST 382
%res382|1 1|Boolean|Real
res382 = true
% TEST 383
%res383|1 3|Boolean|Real
res383 = [true true true]
% TEST 384
%res384|3 1|Boolean|Real
res384 = [true;true;true]
% TEST 385
%res385|2 3|Boolean|Real
res385 = [true true true;true true true]
% TEST 386
%res386|1 1|Boolean|Real
res386 = true
% TEST 387
%res387|1 3|Boolean|Real
res387 = [true true true]
% TEST 388
%res388|3 1|Boolean|Real
res388 = [true;true;true]
% TEST 389
%res389|2 3|Boolean|Real
res389 = [true true true;true true true]
% TEST 390
%res390|1 1|Boolean|Real
res390 = true
% TEST 391
%res391|1 3|Boolean|Real
res391 = [true true true]
% TEST 392
%res392|3 1|Boolean|Real
res392 = [true;true;true]
% TEST 393
%res393|2 3|Boolean|Real
res393 = [true true true;true true true]
% TEST 394
%res394|1 1|Boolean|Real
res394 = true
% TEST 395
%res395|1 4|Boolean|Real
res395 = [true true true true]
% TEST 396
%res396|1 12|Boolean|Real
res396 = [true true true true true true true true true true true true]
% TEST 397
%res397|3 4|Boolean|Real
res397 = [true true true true;true true true true;true true true true]
% TEST 398
%res398|2 12|Boolean|Real
res398 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 399
%res399|1 1|Boolean|Real
res399 = true
% TEST 400
%res400|1 4|Boolean|Real
res400 = [true true true true]
% TEST 401
%res401|1 12|Boolean|Real
res401 = [true true true true true true true true true true true true]
% TEST 402
%res402|3 4|Boolean|Real
res402 = [true true true true;true true true true;true true true true]
% TEST 403
%res403|2 12|Boolean|Real
res403 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 404
%res404|1 1|Boolean|Real
res404 = true
% TEST 405
%res405|1 4|Boolean|Real
res405 = [true true true true]
% TEST 406
%res406|1 12|Boolean|Real
res406 = [true true true true true true true true true true true true]
% TEST 407
%res407|3 4|Boolean|Real
res407 = [true true true true;true true true true;true true true true]
% TEST 408
%res408|2 12|Boolean|Real
res408 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 409
%res409|1 1|Boolean|Real
res409 = true
% TEST 410
%res410|1 3|Boolean|Real
res410 = [true false true]
% TEST 411
%res411|3 1|Boolean|Real
res411 = [true;false;true]
% TEST 412
%res412|2 3|Boolean|Real
res412 = [true false true;true true false]
% TEST 413
%res413|1 1|Boolean|Real
res413 = true
% TEST 414
%res414|1 3|Boolean|Real
res414 = [true false true]
% TEST 415
%res415|3 1|Boolean|Real
res415 = [true;false;true]
% TEST 416
%res416|2 3|Boolean|Real
res416 = [true false true;true true false]
% TEST 417
%res417|1 1|Boolean|Real
res417 = true
% TEST 418
%res418|1 3|Boolean|Real
res418 = [true false true]
% TEST 419
%res419|3 1|Boolean|Real
res419 = [true;false;true]
% TEST 420
%res420|2 3|Boolean|Real
res420 = [true false true;true true false]
% TEST 421
%res421|0 0|Boolean|Real
res421 = []
% TEST 422
%res422|0 0|Boolean|Real
res422 = []
% TEST 423
%res423|0 0|Boolean|Real
res423 = []
% TEST 424
%res424|1 1|Boolean|Real
res424 = true
% TEST 425
%res425|1 3|Boolean|Real
res425 = [true true true]
% TEST 426
%res426|3 1|Boolean|Real
res426 = [true;true;true]
% TEST 427
%res427|2 3|Boolean|Real
res427 = [true true true;true true true]
% TEST 428
%res428|1 1|Boolean|Real
res428 = true
% TEST 429
%res429|1 3|Boolean|Real
res429 = [true true true]
% TEST 430
%res430|3 1|Boolean|Real
res430 = [true;true;true]
% TEST 431
%res431|2 3|Boolean|Real
res431 = [true true true;true true true]
% TEST 432
%res432|1 1|Boolean|Real
res432 = true
% TEST 433
%res433|1 3|Boolean|Real
res433 = [true true true]
% TEST 434
%res434|3 1|Boolean|Real
res434 = [true;true;true]
% TEST 435
%res435|2 3|Boolean|Real
res435 = [true true true;true true true]
% TEST 436
%res436|1 1|Boolean|Real
res436 = true
% TEST 437
%res437|1 4|Boolean|Real
res437 = [true true true true]
% TEST 438
%res438|1 12|Boolean|Real
res438 = [true true true true true true true true true true true true]
% TEST 439
%res439|3 4|Boolean|Real
res439 = [true true true true;true true true true;true true true true]
% TEST 440
%res440|2 12|Boolean|Real
res440 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 441
%res441|1 1|Boolean|Real
res441 = true
% TEST 442
%res442|1 4|Boolean|Real
res442 = [true true true true]
% TEST 443
%res443|1 12|Boolean|Real
res443 = [true true true true true true true true true true true true]
% TEST 444
%res444|3 4|Boolean|Real
res444 = [true true true true;true true true true;true true true true]
% TEST 445
%res445|2 12|Boolean|Real
res445 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 446
%res446|1 1|Boolean|Real
res446 = true
% TEST 447
%res447|1 4|Boolean|Real
res447 = [true true true true]
% TEST 448
%res448|1 12|Boolean|Real
res448 = [true true true true true true true true true true true true]
% TEST 449
%res449|3 4|Boolean|Real
res449 = [true true true true;true true true true;true true true true]
% TEST 450
%res450|2 12|Boolean|Real
res450 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 451
%res451|1 1|Boolean|Real
res451 = true
% TEST 452
%res452|1 3|Boolean|Real
res452 = [true false true]
% TEST 453
%res453|3 1|Boolean|Real
res453 = [true;false;true]
% TEST 454
%res454|2 3|Boolean|Real
res454 = [true false true;true true false]
% TEST 455
%res455|1 1|Boolean|Real
res455 = true
% TEST 456
%res456|1 3|Boolean|Real
res456 = [true false true]
% TEST 457
%res457|3 1|Boolean|Real
res457 = [true;false;true]
% TEST 458
%res458|2 3|Boolean|Real
res458 = [true false true;true true false]
% TEST 459
%res459|1 1|Boolean|Real
res459 = true
% TEST 460
%res460|1 3|Boolean|Real
res460 = [true false true]
% TEST 461
%res461|3 1|Boolean|Real
res461 = [true;false;true]
% TEST 462
%res462|2 3|Boolean|Real
res462 = [true false true;true true false]
% TEST 463
%res463|0 0|Boolean|Real
res463 = []
% TEST 464
%res464|0 0|Boolean|Real
res464 = []
% TEST 465
%res465|0 0|Boolean|Real
res465 = []
% TEST 466
%res466|1 1|Boolean|Real
res466 = true
% TEST 467
%res467|1 3|Boolean|Real
res467 = [true true true]
% TEST 468
%res468|3 1|Boolean|Real
res468 = [true;true;true]
% TEST 469
%res469|2 3|Boolean|Real
res469 = [true true true;true true true]
% TEST 470
%res470|1 1|Boolean|Real
res470 = true
% TEST 471
%res471|1 3|Boolean|Real
res471 = [true true true]
% TEST 472
%res472|3 1|Boolean|Real
res472 = [true;true;true]
% TEST 473
%res473|2 3|Boolean|Real
res473 = [true true true;true true true]
% TEST 474
%res474|1 1|Boolean|Real
res474 = true
% TEST 475
%res475|1 3|Boolean|Real
res475 = [true true true]
% TEST 476
%res476|3 1|Boolean|Real
res476 = [true;true;true]
% TEST 477
%res477|2 3|Boolean|Real
res477 = [true true true;true true true]
% TEST 478
%res478|1 1|Boolean|Real
res478 = true
% TEST 479
%res479|1 4|Boolean|Real
res479 = [true true true true]
% TEST 480
%res480|1 12|Boolean|Real
res480 = [true true true true true true true true true true true true]
% TEST 481
%res481|3 4|Boolean|Real
res481 = [true true true true;true true true true;true true true true]
% TEST 482
%res482|2 12|Boolean|Real
res482 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 483
%res483|1 1|Boolean|Real
res483 = true
% TEST 484
%res484|1 4|Boolean|Real
res484 = [true true true true]
% TEST 485
%res485|1 12|Boolean|Real
res485 = [true true true true true true true true true true true true]
% TEST 486
%res486|3 4|Boolean|Real
res486 = [true true true true;true true true true;true true true true]
% TEST 487
%res487|2 12|Boolean|Real
res487 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 488
%res488|1 1|Boolean|Real
res488 = true
% TEST 489
%res489|1 4|Boolean|Real
res489 = [true true true true]
% TEST 490
%res490|1 12|Boolean|Real
res490 = [true true true true true true true true true true true true]
% TEST 491
%res491|3 4|Boolean|Real
res491 = [true true true true;true true true true;true true true true]
% TEST 492
%res492|2 12|Boolean|Real
res492 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 493
%res493|1 1|Boolean|Real
res493 = true
% TEST 494
%res494|1 3|Boolean|Real
res494 = [true false true]
% TEST 495
%res495|3 1|Boolean|Real
res495 = [true;false;true]
% TEST 496
%res496|2 3|Boolean|Real
res496 = [true false true;true true false]
% TEST 497
%res497|1 1|Boolean|Real
res497 = true
% TEST 498
%res498|1 3|Boolean|Real
res498 = [true false true]
% TEST 499
%res499|3 1|Boolean|Real
res499 = [true;false;true]
% TEST 500
%res500|2 3|Boolean|Real
res500 = [true false true;true true false]
% TEST 501
%res501|1 1|Boolean|Real
res501 = true
% TEST 502
%res502|1 3|Boolean|Real
res502 = [true false true]
% TEST 503
%res503|3 1|Boolean|Real
res503 = [true;false;true]
% TEST 504
%res504|2 3|Boolean|Real
res504 = [true false true;true true false]
% TEST 505
%res505|0 0|Boolean|Real
res505 = []
% TEST 506
%res506|0 0|Boolean|Real
res506 = []
% TEST 507
%res507|0 0|Boolean|Real
res507 = []
% TEST 508
%res508|1 1|Boolean|Real
res508 = true
% TEST 509
%res509|1 3|Boolean|Real
res509 = [true true true]
% TEST 510
%res510|3 1|Boolean|Real
res510 = [true;true;true]
% TEST 511
%res511|2 3|Boolean|Real
res511 = [true true true;true true true]
% TEST 512
%res512|1 1|Boolean|Real
res512 = true
% TEST 513
%res513|1 3|Boolean|Real
res513 = [true true true]
% TEST 514
%res514|3 1|Boolean|Real
res514 = [true;true;true]
% TEST 515
%res515|2 3|Boolean|Real
res515 = [true true true;true true true]
% TEST 516
%res516|1 1|Boolean|Real
res516 = true
% TEST 517
%res517|1 3|Boolean|Real
res517 = [true true true]
% TEST 518
%res518|3 1|Boolean|Real
res518 = [true;true;true]
% TEST 519
%res519|2 3|Boolean|Real
res519 = [true true true;true true true]
% TEST 520
%res520|1 1|Boolean|Real
res520 = true
% TEST 521
%res521|1 4|Boolean|Real
res521 = [true true true true]
% TEST 522
%res522|1 12|Boolean|Real
res522 = [true true true true true true true true true true true true]
% TEST 523
%res523|3 4|Boolean|Real
res523 = [true true true true;true true true true;true true true true]
% TEST 524
%res524|2 12|Boolean|Real
res524 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 525
%res525|1 1|Boolean|Real
res525 = true
% TEST 526
%res526|1 4|Boolean|Real
res526 = [true true true true]
% TEST 527
%res527|1 12|Boolean|Real
res527 = [true true true true true true true true true true true true]
% TEST 528
%res528|3 4|Boolean|Real
res528 = [true true true true;true true true true;true true true true]
% TEST 529
%res529|2 12|Boolean|Real
res529 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 530
%res530|1 1|Boolean|Real
res530 = true
% TEST 531
%res531|1 4|Boolean|Real
res531 = [true true true true]
% TEST 532
%res532|1 12|Boolean|Real
res532 = [true true true true true true true true true true true true]
% TEST 533
%res533|3 4|Boolean|Real
res533 = [true true true true;true true true true;true true true true]
% TEST 534
%res534|2 12|Boolean|Real
res534 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 535
%res535|1 1|Boolean|Real
res535 = true
% TEST 536
%res536|1 3|Boolean|Real
res536 = [true false true]
% TEST 537
%res537|3 1|Boolean|Real
res537 = [true;false;true]
% TEST 538
%res538|2 3|Boolean|Real
res538 = [true false true;true true false]
% TEST 539
%res539|1 1|Boolean|Real
res539 = true
% TEST 540
%res540|1 3|Boolean|Real
res540 = [true false true]
% TEST 541
%res541|3 1|Boolean|Real
res541 = [true;false;true]
% TEST 542
%res542|2 3|Boolean|Real
res542 = [true false true;true true false]
% TEST 543
%res543|1 1|Boolean|Real
res543 = true
% TEST 544
%res544|1 3|Boolean|Real
res544 = [true false true]
% TEST 545
%res545|3 1|Boolean|Real
res545 = [true;false;true]
% TEST 546
%res546|2 3|Boolean|Real
res546 = [true false true;true true false]
% TEST 547
%res547|0 0|Boolean|Real
res547 = []
% TEST 548
%res548|0 0|Boolean|Real
res548 = []
% TEST 549
%res549|0 0|Boolean|Real
res549 = []
% TEST 550
%res550|1 1|Boolean|Real
res550 = true
% TEST 551
%res551|1 3|Boolean|Real
res551 = [true true true]
% TEST 552
%res552|3 1|Boolean|Real
res552 = [true;true;true]
% TEST 553
%res553|2 3|Boolean|Real
res553 = [true true true;true true true]
% TEST 554
%res554|1 1|Boolean|Real
res554 = true
% TEST 555
%res555|1 3|Boolean|Real
res555 = [true true true]
% TEST 556
%res556|3 1|Boolean|Real
res556 = [true;true;true]
% TEST 557
%res557|2 3|Boolean|Real
res557 = [true true true;true true true]
% TEST 558
%res558|1 1|Boolean|Real
res558 = true
% TEST 559
%res559|1 3|Boolean|Real
res559 = [true true true]
% TEST 560
%res560|3 1|Boolean|Real
res560 = [true;true;true]
% TEST 561
%res561|2 3|Boolean|Real
res561 = [true true true;true true true]
% TEST 562
%res562|1 1|Boolean|Real
res562 = true
% TEST 563
%res563|1 4|Boolean|Real
res563 = [true true true true]
% TEST 564
%res564|1 12|Boolean|Real
res564 = [true true true true true true true true true true true true]
% TEST 565
%res565|3 4|Boolean|Real
res565 = [true true true true;true true true true;true true true true]
% TEST 566
%res566|2 12|Boolean|Real
res566 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 567
%res567|1 1|Boolean|Real
res567 = true
% TEST 568
%res568|1 4|Boolean|Real
res568 = [true true true true]
% TEST 569
%res569|1 12|Boolean|Real
res569 = [true true true true true true true true true true true true]
% TEST 570
%res570|3 4|Boolean|Real
res570 = [true true true true;true true true true;true true true true]
% TEST 571
%res571|2 12|Boolean|Real
res571 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 572
%res572|1 1|Boolean|Real
res572 = true
% TEST 573
%res573|1 4|Boolean|Real
res573 = [true true true true]
% TEST 574
%res574|1 12|Boolean|Real
res574 = [true true true true true true true true true true true true]
% TEST 575
%res575|3 4|Boolean|Real
res575 = [true true true true;true true true true;true true true true]
% TEST 576
%res576|2 12|Boolean|Real
res576 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 577
%res577|1 1|Boolean|Real
res577 = true
% TEST 578
%res578|1 3|Boolean|Real
res578 = [true false true]
% TEST 579
%res579|3 1|Boolean|Real
res579 = [true;false;true]
% TEST 580
%res580|2 3|Boolean|Real
res580 = [true false true;true true false]
% TEST 581
%res581|1 1|Boolean|Real
res581 = true
% TEST 582
%res582|1 3|Boolean|Real
res582 = [true false true]
% TEST 583
%res583|3 1|Boolean|Real
res583 = [true;false;true]
% TEST 584
%res584|2 3|Boolean|Real
res584 = [true false true;true true false]
% TEST 585
%res585|1 1|Boolean|Real
res585 = true
% TEST 586
%res586|1 3|Boolean|Real
res586 = [true false true]
% TEST 587
%res587|3 1|Boolean|Real
res587 = [true;false;true]
% TEST 588
%res588|2 3|Boolean|Real
res588 = [true false true;true true false]
% TEST 589
%res589|0 0|Boolean|Real
res589 = []
% TEST 590
%res590|0 0|Boolean|Real
res590 = []
% TEST 591
%res591|0 0|Boolean|Real
res591 = []
% TEST 592
%res592|1 1|Boolean|Real
res592 = true
% TEST 593
%res593|1 3|Boolean|Real
res593 = [true true true]
% TEST 594
%res594|3 1|Boolean|Real
res594 = [true;true;true]
% TEST 595
%res595|2 3|Boolean|Real
res595 = [true true true;true true true]
% TEST 596
%res596|1 1|Boolean|Real
res596 = true
% TEST 597
%res597|1 3|Boolean|Real
res597 = [true true true]
% TEST 598
%res598|3 1|Boolean|Real
res598 = [true;true;true]
% TEST 599
%res599|2 3|Boolean|Real
res599 = [true true true;true true true]
% TEST 600
%res600|1 1|Boolean|Real
res600 = true
% TEST 601
%res601|1 3|Boolean|Real
res601 = [true true true]
% TEST 602
%res602|3 1|Boolean|Real
res602 = [true;true;true]
% TEST 603
%res603|2 3|Boolean|Real
res603 = [true true true;true true true]
% TEST 604
%res604|1 1|Boolean|Real
res604 = true
% TEST 605
%res605|1 4|Boolean|Real
res605 = [true true true true]
% TEST 606
%res606|1 12|Boolean|Real
res606 = [true true true true true true true true true true true true]
% TEST 607
%res607|3 4|Boolean|Real
res607 = [true true true true;true true true true;true true true true]
% TEST 608
%res608|2 12|Boolean|Real
res608 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 609
%res609|1 1|Boolean|Real
res609 = true
% TEST 610
%res610|1 4|Boolean|Real
res610 = [true true true true]
% TEST 611
%res611|1 12|Boolean|Real
res611 = [true true true true true true true true true true true true]
% TEST 612
%res612|3 4|Boolean|Real
res612 = [true true true true;true true true true;true true true true]
% TEST 613
%res613|2 12|Boolean|Real
res613 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 614
%res614|1 1|Boolean|Real
res614 = true
% TEST 615
%res615|1 4|Boolean|Real
res615 = [true true true true]
% TEST 616
%res616|1 12|Boolean|Real
res616 = [true true true true true true true true true true true true]
% TEST 617
%res617|3 4|Boolean|Real
res617 = [true true true true;true true true true;true true true true]
% TEST 618
%res618|2 12|Boolean|Real
res618 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 619
%res619|1 1|Boolean|Real
res619 = true
% TEST 620
%res620|1 3|Boolean|Real
res620 = [true false true]
% TEST 621
%res621|3 1|Boolean|Real
res621 = [true;false;true]
% TEST 622
%res622|2 3|Boolean|Real
res622 = [true false true;true true false]
% TEST 623
%res623|1 1|Boolean|Real
res623 = true
% TEST 624
%res624|1 3|Boolean|Real
res624 = [true false true]
% TEST 625
%res625|3 1|Boolean|Real
res625 = [true;false;true]
% TEST 626
%res626|2 3|Boolean|Real
res626 = [true false true;true true false]
% TEST 627
%res627|1 1|Boolean|Real
res627 = true
% TEST 628
%res628|1 3|Boolean|Real
res628 = [true false true]
% TEST 629
%res629|3 1|Boolean|Real
res629 = [true;false;true]
% TEST 630
%res630|2 3|Boolean|Real
res630 = [true false true;true true false]
% TEST 631
%res631|0 0|Boolean|Real
res631 = []
% TEST 632
%res632|0 0|Boolean|Real
res632 = []
% TEST 633
%res633|0 0|Boolean|Real
res633 = []
% TEST 634
%res634|1 1|Boolean|Real
res634 = true
% TEST 635
%res635|1 3|Boolean|Real
res635 = [true true true]
% TEST 636
%res636|3 1|Boolean|Real
res636 = [true;true;true]
% TEST 637
%res637|2 3|Boolean|Real
res637 = [true true true;true true true]
% TEST 638
%res638|1 1|Boolean|Real
res638 = true
% TEST 639
%res639|1 3|Boolean|Real
res639 = [true true true]
% TEST 640
%res640|3 1|Boolean|Real
res640 = [true;true;true]
% TEST 641
%res641|2 3|Boolean|Real
res641 = [true true true;true true true]
% TEST 642
%res642|1 1|Boolean|Real
res642 = true
% TEST 643
%res643|1 3|Boolean|Real
res643 = [true true true]
% TEST 644
%res644|3 1|Boolean|Real
res644 = [true;true;true]
% TEST 645
%res645|2 3|Boolean|Real
res645 = [true true true;true true true]
% TEST 646
%res646|1 1|Boolean|Real
res646 = true
% TEST 647
%res647|1 4|Boolean|Real
res647 = [true true true true]
% TEST 648
%res648|1 12|Boolean|Real
res648 = [true true true true true true true true true true true true]
% TEST 649
%res649|3 4|Boolean|Real
res649 = [true true true true;true true true true;true true true true]
% TEST 650
%res650|2 12|Boolean|Real
res650 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 651
%res651|1 1|Boolean|Real
res651 = true
% TEST 652
%res652|1 4|Boolean|Real
res652 = [true true true true]
% TEST 653
%res653|1 12|Boolean|Real
res653 = [true true true true true true true true true true true true]
% TEST 654
%res654|3 4|Boolean|Real
res654 = [true true true true;true true true true;true true true true]
% TEST 655
%res655|2 12|Boolean|Real
res655 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 656
%res656|1 1|Boolean|Real
res656 = true
% TEST 657
%res657|1 4|Boolean|Real
res657 = [true true true true]
% TEST 658
%res658|1 12|Boolean|Real
res658 = [true true true true true true true true true true true true]
% TEST 659
%res659|3 4|Boolean|Real
res659 = [true true true true;true true true true;true true true true]
% TEST 660
%res660|2 12|Boolean|Real
res660 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 661
%res661|1 1|Boolean|Real
res661 = true
% TEST 662
%res662|1 3|Boolean|Real
res662 = [true false true]
% TEST 663
%res663|3 1|Boolean|Real
res663 = [true;false;true]
% TEST 664
%res664|2 3|Boolean|Real
res664 = [true false true;true true false]
% TEST 665
%res665|1 1|Boolean|Real
res665 = true
% TEST 666
%res666|1 3|Boolean|Real
res666 = [true false true]
% TEST 667
%res667|3 1|Boolean|Real
res667 = [true;false;true]
% TEST 668
%res668|2 3|Boolean|Real
res668 = [true false true;true true false]
% TEST 669
%res669|1 1|Boolean|Real
res669 = true
% TEST 670
%res670|1 3|Boolean|Real
res670 = [true false true]
% TEST 671
%res671|3 1|Boolean|Real
res671 = [true;false;true]
% TEST 672
%res672|2 3|Boolean|Real
res672 = [true false true;true true false]
% TEST 673
%res673|0 0|Boolean|Real
res673 = []
% TEST 674
%res674|0 0|Boolean|Real
res674 = []
% TEST 675
%res675|0 0|Boolean|Real
res675 = []
% TEST 676
%res676|1 1|Boolean|Real
res676 = true
% TEST 677
%res677|1 3|Boolean|Real
res677 = [true true true]
% TEST 678
%res678|3 1|Boolean|Real
res678 = [true;true;true]
% TEST 679
%res679|2 3|Boolean|Real
res679 = [true true true;true true true]
% TEST 680
%res680|1 1|Boolean|Real
res680 = true
% TEST 681
%res681|1 3|Boolean|Real
res681 = [true true true]
% TEST 682
%res682|3 1|Boolean|Real
res682 = [true;true;true]
% TEST 683
%res683|2 3|Boolean|Real
res683 = [true true true;true true true]
% TEST 684
%res684|1 1|Boolean|Real
res684 = true
% TEST 685
%res685|1 3|Boolean|Real
res685 = [true true true]
% TEST 686
%res686|3 1|Boolean|Real
res686 = [true;true;true]
% TEST 687
%res687|2 3|Boolean|Real
res687 = [true true true;true true true]
% TEST 688
%res688|1 1|Boolean|Real
res688 = true
% TEST 689
%res689|1 4|Boolean|Real
res689 = [true true true true]
% TEST 690
%res690|1 12|Boolean|Real
res690 = [true true true true true true true true true true true true]
% TEST 691
%res691|3 4|Boolean|Real
res691 = [true true true true;true true true true;true true true true]
% TEST 692
%res692|2 12|Boolean|Real
res692 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 693
%res693|1 1|Boolean|Real
res693 = true
% TEST 694
%res694|1 4|Boolean|Real
res694 = [true true true true]
% TEST 695
%res695|1 12|Boolean|Real
res695 = [true true true true true true true true true true true true]
% TEST 696
%res696|3 4|Boolean|Real
res696 = [true true true true;true true true true;true true true true]
% TEST 697
%res697|2 12|Boolean|Real
res697 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 698
%res698|1 1|Boolean|Real
res698 = true
% TEST 699
%res699|1 4|Boolean|Real
res699 = [true true true true]
% TEST 700
%res700|1 12|Boolean|Real
res700 = [true true true true true true true true true true true true]
% TEST 701
%res701|3 4|Boolean|Real
res701 = [true true true true;true true true true;true true true true]
% TEST 702
%res702|2 12|Boolean|Real
res702 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 703
%res703|1 1|Boolean|Real
res703 = true
% TEST 704
%res704|1 3|Boolean|Real
res704 = [true false true]
% TEST 705
%res705|3 1|Boolean|Real
res705 = [true;false;true]
% TEST 706
%res706|2 3|Boolean|Real
res706 = [true false true;true true false]
% TEST 707
%res707|1 1|Boolean|Real
res707 = true
% TEST 708
%res708|1 3|Boolean|Real
res708 = [true false true]
% TEST 709
%res709|3 1|Boolean|Real
res709 = [true;false;true]
% TEST 710
%res710|2 3|Boolean|Real
res710 = [true false true;true true false]
% TEST 711
%res711|1 1|Boolean|Real
res711 = true
% TEST 712
%res712|1 3|Boolean|Real
res712 = [true false true]
% TEST 713
%res713|3 1|Boolean|Real
res713 = [true;false;true]
% TEST 714
%res714|2 3|Boolean|Real
res714 = [true false true;true true false]
% TEST 715
%res715|0 0|Boolean|Real
res715 = []
% TEST 716
%res716|0 0|Boolean|Real
res716 = []
% TEST 717
%res717|0 0|Boolean|Real
res717 = []
% TEST 718
%res718|1 1|Boolean|Real
res718 = true
% TEST 719
%res719|1 3|Boolean|Real
res719 = [true true true]
% TEST 720
%res720|3 1|Boolean|Real
res720 = [true;true;true]
% TEST 721
%res721|2 3|Boolean|Real
res721 = [true true true;true true true]
% TEST 722
%res722|1 1|Boolean|Real
res722 = true
% TEST 723
%res723|1 3|Boolean|Real
res723 = [true true true]
% TEST 724
%res724|3 1|Boolean|Real
res724 = [true;true;true]
% TEST 725
%res725|2 3|Boolean|Real
res725 = [true true true;true true true]
% TEST 726
%res726|1 1|Boolean|Real
res726 = true
% TEST 727
%res727|1 3|Boolean|Real
res727 = [true true true]
% TEST 728
%res728|3 1|Boolean|Real
res728 = [true;true;true]
% TEST 729
%res729|2 3|Boolean|Real
res729 = [true true true;true true true]
% TEST 730
%res730|1 1|Boolean|Real
res730 = true
% TEST 731
%res731|1 4|Boolean|Real
res731 = [true true true true]
% TEST 732
%res732|1 12|Boolean|Real
res732 = [true true true true true true true true true true true true]
% TEST 733
%res733|3 4|Boolean|Real
res733 = [true true true true;true true true true;true true true true]
% TEST 734
%res734|2 12|Boolean|Real
res734 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 735
%res735|1 1|Boolean|Real
res735 = true
% TEST 736
%res736|1 4|Boolean|Real
res736 = [true true true true]
% TEST 737
%res737|1 12|Boolean|Real
res737 = [true true true true true true true true true true true true]
% TEST 738
%res738|3 4|Boolean|Real
res738 = [true true true true;true true true true;true true true true]
% TEST 739
%res739|2 12|Boolean|Real
res739 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 740
%res740|1 1|Boolean|Real
res740 = true
% TEST 741
%res741|1 4|Boolean|Real
res741 = [true true true true]
% TEST 742
%res742|1 12|Boolean|Real
res742 = [true true true true true true true true true true true true]
% TEST 743
%res743|3 4|Boolean|Real
res743 = [true true true true;true true true true;true true true true]
% TEST 744
%res744|2 12|Boolean|Real
res744 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 745
%res745|1 1|Boolean|Real
res745 = true
% TEST 746
%res746|1 3|Boolean|Real
res746 = [true false true]
% TEST 747
%res747|3 1|Boolean|Real
res747 = [true;false;true]
% TEST 748
%res748|2 3|Boolean|Real
res748 = [true false true;true true false]
% TEST 749
%res749|1 1|Boolean|Real
res749 = true
% TEST 750
%res750|1 3|Boolean|Real
res750 = [true false true]
% TEST 751
%res751|3 1|Boolean|Real
res751 = [true;false;true]
% TEST 752
%res752|2 3|Boolean|Real
res752 = [true false true;true true false]
% TEST 753
%res753|1 1|Boolean|Real
res753 = true
% TEST 754
%res754|1 3|Boolean|Real
res754 = [true false true]
% TEST 755
%res755|3 1|Boolean|Real
res755 = [true;false;true]
% TEST 756
%res756|2 3|Boolean|Real
res756 = [true false true;true true false]
% TEST 757
%res757|0 0|Boolean|Real
res757 = []
% TEST 758
%res758|0 0|Boolean|Real
res758 = []
% TEST 759
%res759|0 0|Boolean|Real
res759 = []
% TEST 760
%res760|1 1|Boolean|Real
res760 = true
% TEST 761
%res761|1 3|Boolean|Real
res761 = [true true true]
% TEST 762
%res762|3 1|Boolean|Real
res762 = [true;true;true]
% TEST 763
%res763|2 3|Boolean|Real
res763 = [true true true;true true true]
% TEST 764
%res764|1 1|Boolean|Real
res764 = true
% TEST 765
%res765|1 3|Boolean|Real
res765 = [true true true]
% TEST 766
%res766|3 1|Boolean|Real
res766 = [true;true;true]
% TEST 767
%res767|2 3|Boolean|Real
res767 = [true true true;true true true]
% TEST 768
%res768|1 1|Boolean|Real
res768 = true
% TEST 769
%res769|1 3|Boolean|Real
res769 = [true true true]
% TEST 770
%res770|3 1|Boolean|Real
res770 = [true;true;true]
% TEST 771
%res771|2 3|Boolean|Real
res771 = [true true true;true true true]
% TEST 772
%res772|1 1|Boolean|Real
res772 = true
% TEST 773
%res773|1 4|Boolean|Real
res773 = [true true true true]
% TEST 774
%res774|1 12|Boolean|Real
res774 = [true true true true true true true true true true true true]
% TEST 775
%res775|3 4|Boolean|Real
res775 = [true true true true;true true true true;true true true true]
% TEST 776
%res776|2 12|Boolean|Real
res776 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 777
%res777|1 1|Boolean|Real
res777 = true
% TEST 778
%res778|1 4|Boolean|Real
res778 = [true true true true]
% TEST 779
%res779|1 12|Boolean|Real
res779 = [true true true true true true true true true true true true]
% TEST 780
%res780|3 4|Boolean|Real
res780 = [true true true true;true true true true;true true true true]
% TEST 781
%res781|2 12|Boolean|Real
res781 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 782
%res782|1 1|Boolean|Real
res782 = true
% TEST 783
%res783|1 4|Boolean|Real
res783 = [true true true true]
% TEST 784
%res784|1 12|Boolean|Real
res784 = [true true true true true true true true true true true true]
% TEST 785
%res785|3 4|Boolean|Real
res785 = [true true true true;true true true true;true true true true]
% TEST 786
%res786|2 12|Boolean|Real
res786 = [true true true true true true true true true true true true;true true true true true true true true true true true true]
% TEST 787
%res787|1 1|Boolean|Real
res787 = true
% TEST 788
%res788|1 3|Boolean|Real
res788 = [true false true]
% TEST 789
%res789|3 1|Boolean|Real
res789 = [true;false;true]
% TEST 790
%res790|2 3|Boolean|Real
res790 = [true false true;true true false]
% TEST 791
%res791|1 1|Boolean|Real
res791 = true
% TEST 792
%res792|1 3|Boolean|Real
res792 = [true false true]
% TEST 793
%res793|3 1|Boolean|Real
res793 = [true;false;true]
% TEST 794
%res794|2 3|Boolean|Real
res794 = [true false true;true true false]
% TEST 795
%res795|1 1|Boolean|Real
res795 = true
% TEST 796
%res796|1 3|Boolean|Real
res796 = [true false true]
% TEST 797
%res797|3 1|Boolean|Real
res797 = [true;false;true]
% TEST 798
%res798|2 3|Boolean|Real
res798 = [true false true;true true false]
