all1:: $(LIBRARY)
# options compilation a modifier sous hp & solaris
$(LIBRARY): $(OBJS)
	@echo Creation of $(LIBRARY)
	@$(RM) $@;
	@echo "linking";
	#-lnsl -lU77 not defined on solaris
	@$(LD) -b -o  -ldld -lm $@ $(OBJS) $(DEFAULTS) $(LIBR) $(TCLTK_LIBS) $(XLIBS)  $(TERMCAPLIB);
