SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include ../../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = scsbranchinglib
NAM = SCI/macros/scicos_blocks/Branching

MACROS= MUX_f.sci SWITCH_f.sci DEMUX_f.sci IFTHEL_f.sci  RELAY_f.sci \
	ESELECT_f.sci ISELECT_f.sci NRMSOM_f.sci SELECT_f.sci


include ../../Make.lib
